window.FI = window.FI || { chapters: [] };

FI.chapters.push({
  id: "c1", n: 1, note: "฿20",
  title: "Why Are Financial Institutions Special?",
  short: "Why FIs exist",
  thesis: "Households and firms could deal directly. FIs exist because doing that is expensive, illiquid and risky, and regulators watch FIs because their failure hurts everyone else too.",
  lab: "dpa", labName: "Deposit Cover Check",
  concepts: [
    { h: "A world without FIs",
      b: "Picture households lending straight to corporations. Each saver would pay <b>monitoring costs</b> to check the borrower, carry <b>liquidity costs</b> (long-term claims are hard to sell), and bear <b>price risk</b> (sell early and the price may have dropped). The result is a low flow of funds and expensive corporate financing.",
      th: "A rice farmer in Suphan Buri with ฿50,000 is not going to analyse CP ALL's balance sheet. They put it in a GSB or BAAC savings account, and the bank does the analysis." },
    { h: "Two jobs: broker and asset transformer",
      b: "As a <b>broker</b>, an FI acts as the saver's agent: it cuts transaction and information costs but holds no position. As an <b>asset transformer</b>, it issues its own claims (deposits, insurance policies) that are more attractive to savers, and uses the money to buy primary securities (loans, bonds).",
      th: "A securities company (บล.) running your SET order earns a commission as a broker. Kasikornbank taking your savings deposit and lending it to an SME is asset transformation." },
    { h: "Delegated monitor",
      b: "When thousands of small investors hold a firm's debt, each has little incentive to monitor it. That is the free-rider problem, and it creates agency costs. An FI with one large loan has every incentive to monitor, enjoys <b>economies of scale</b> in gathering information, and can use short-term, renewable loan contracts to keep control. Its relationship gives it inside information, which reduces information asymmetry." },
    { h: "Liquidity and price risk",
      b: "Claims issued by FIs, such as demand deposits, are more liquid and carry less price risk than the primary securities behind them. The FI can offer this because size lets it diversify: across thousands of borrowers, losses become predictable." },
    { h: "Other special services",
      b: "Reduced transaction costs · <b>maturity intermediation</b> (funding long loans with short deposits) · <b>denomination intermediation</b> (small savers own slices of large assets) · time and intergenerational intermediation · credit allocation to priority sectors · transmission of monetary policy · payment services.",
      th: "The US payment rails in the slides are Fedwire and CHIPS. Thailand's equivalents are BAHTNET, the Bank of Thailand's real-time gross settlement system for large-value transfers, and PromptPay, the retail instant-payment layer launched in 2017." },
    { h: "Why FIs get special regulation",
      b: "Failure of an FI creates <b>negative externalities</b>: runs spread by contagion, credit dries up for firms that did nothing wrong, and payment chains break. Regulation is not costless, though. The <b>net regulatory burden</b> is the private cost of complying minus the private benefits (such as deposit insurance and lender-of-last-resort access)." },
    { h: "Safety and soundness: four layers",
      b: "1) Diversification rules that limit exposure to a single borrower. 2) Minimum capital requirements. 3) Guaranty funds: in the US, the Deposit Insurance Fund (FDIC) and SIPC. 4) Monitoring and surveillance, including on-site examinations and review of accounting statements.",
      th: "Thai equivalents: the BOT's single lending limit (broadly 25% of a bank's capital), Basel III capital rules, the <b>Deposit Protection Agency (DPA)</b> covering up to ฿1 million per depositor per bank since August 2021, and BOT on-site examinations." },
    { h: "Five other kinds of regulation",
      b: "<b>Monetary policy</b>: the central bank controls outside money, while most money is inside money (deposits). <b>Credit allocation</b>: pushing funds to sectors like housing or farming. <b>Consumer protection</b>: the CRA and HMDA in the US. <b>Investor protection</b>: the Securities Acts of 1933 and 1934, the Investment Company Act of 1940, and Dodd-Frank (2010). <b>Entry regulation</b>: charters, which make a licence valuable.",
      th: "Credit allocation in Thailand runs largely through Specialized Financial Institutions: GH Bank for housing, BAAC for farmers, SME D Bank for small firms. Entry regulation shows up in new licensing rounds, such as the BOT's virtual-bank framework." },
    { h: "Changing dynamics and the crisis",
      b: "After the 1999 Financial Services Modernization Act, US banks shifted from <b>originate-and-hold</b> to <b>originate-and-distribute</b>: make loans, securitize them, sell them. That weakened incentives to screen and monitor borrowers, pushed risk off balance sheet, and fed the subprime housing bubble. The lasting lesson is <b>enterprise risk management (ERM)</b>: manage risks as one interrelated portfolio, backed by a strong risk culture rather than processes alone." },
    { h: "Monetary policy tools",
      b: "Open market operations · the discount rate · reserve requirements. <b>Expansionary</b> policy (buy securities, cut rates, lower reserve ratios) adds reserves and pushes rates down. <b>Contractionary</b> policy does the reverse.",
      th: "The BOT's Monetary Policy Committee sets the <b>policy rate</b>, the 1-day bilateral repurchase rate, under a headline inflation target of 1–3%. Its main operating tools are repo operations and BOT bonds." }
  ],
  formulas: [
    ["Net regulatory burden", "Private costs of regulation − private benefits"],
    ["DPA coverage (Thailand)", "Covered = min(total deposits at bank, ฿1,000,000), per depositor per bank"]
  ],
  cards: [
    ["Delegated monitor", "An FI that monitors borrowers on behalf of many small savers. It solves the free-rider problem and has scale economies in information."],
    ["Asset transformer vs broker", "A broker acts as the saver's agent and holds no position. An asset transformer issues its own claims (deposits) and buys primary securities (loans)."],
    ["Net regulatory burden", "The private cost of complying with regulation minus the private benefits it brings, such as deposit insurance."],
    ["Outside vs inside money", "Outside money is the monetary base the central bank controls directly (notes, reserves). Inside money is created by banks, mainly deposits."],
    ["Maturity intermediation", "Funding long-term assets with short-term liabilities. Profitable, but it creates interest-rate and liquidity risk."],
    ["Denomination intermediation", "Letting small savers own a slice of large, indivisible assets, as a mutual fund does."],
    ["Originate-and-distribute", "Making loans in order to sell or securitize them. It weakens incentives to screen and monitor, a root of the 2007–09 crisis."],
    ["DPA", "Thailand's Deposit Protection Agency (สถาบันคุ้มครองเงินฝาก). Covers up to ฿1 million per depositor per bank. Savings cooperatives are outside it."],
    ["BAHTNET", "The Bank of Thailand's real-time gross settlement system for large-value interbank payments, the local counterpart to Fedwire."],
    ["ERM", "Enterprise risk management: prioritising and managing risks as an interrelated portfolio, anchored by risk culture."]
  ],
  quiz: [
    { t: "mcq", q: "Without FIs, which of these is <em>not</em> a reason households hold few corporate securities directly?",
      o: ["Monitoring costs", "Liquidity costs", "Price risk", "Reserve requirements"], a: 3,
      x: "Monitoring costs, liquidity costs and price risk are the three frictions in the slides. Reserve requirements apply to banks, not households." },
    { t: "mcq", q: "A Thai securities company executes a client's order on the SET for a commission and takes no position itself. Which function is this?",
      o: ["Asset transformation", "Brokerage", "Maturity intermediation", "Credit allocation"], a: 1,
      x: "It is acting purely as the saver's agent. No new claim is issued and nothing sits on its balance sheet." },
    { t: "mcq", q: "Government Savings Bank takes savings deposits and uses them to buy Thai government bonds. What is it doing?",
      o: ["Brokerage", "Asset transformation", "Underwriting", "Denomination arbitrage"], a: 1,
      x: "GSB issues a secondary claim (the deposit) that suits savers better, and holds the primary security (the bond)." },
    { t: "mcq", q: "Somchai keeps ฿1.3 million at Bank A and ฿400,000 at Bank B. What does the DPA's ฿1 million per depositor per bank rule mean for him?",
      o: ["Only ฿1 million of his ฿1.7 million is protected, because the cap is per person", "Everything is protected, because the cap applies to each account separately", "฿1.4 million is protected: Bank A is capped at ฿1 million, Bank B is fully covered, and the ฿300,000 excess at Bank A is exposed", "Nothing is protected, because he holds more than ฿1 million in total"], a: 2,
      x: "The cap is per depositor <em>per bank</em>. Spreading money across banks raises the cover; piling it into one bank leaves the excess as an unsecured claim if that bank fails." },
    { t: "mcq", q: "Why can a bank monitor a borrower better than 10,000 individual bondholders?",
      o: ["Banks are legally required to receive audited accounts first", "It removes the free-rider problem and has economies of scale in information", "Bondholders cannot read financial statements", "Loans are always secured by collateral"], a: 1,
      x: "Each small holder hopes someone else will do the monitoring. One lender with a large stake has the incentive, and spreads its fixed information costs across many loans." },
    { t: "mcq", q: "Net regulatory burden is best defined as:",
      o: ["The total fines paid by an FI", "Private costs of regulation minus private benefits", "Capital held above the minimum", "The central bank's operating budget"], a: 1,
      x: "The benefits (deposit insurance, lender-of-last-resort access, charter value) are offset against compliance costs. A rising burden pushes activity to less-regulated FIs." },
    { t: "mcq", q: "Which of these is <em>outside money</em> in Thailand?",
      o: ["Your savings deposit at Kasikornbank", "Commercial banks' reserve balances at the Bank of Thailand", "A money market fund unit", "A credit card limit"], a: 1,
      x: "Outside money is the monetary base the central bank controls directly: notes and reserves at the BOT. Deposits are inside money created by banks." },
    { t: "mcq", q: "Headline inflation is running well above the BOT's 1–3% target. Which move is contractionary?",
      o: ["Cutting the policy rate", "Buying government bonds in open market operations", "Raising the policy rate", "Lowering reserve requirements"], a: 2,
      x: "Raising the policy rate tightens financial conditions. The other three options all add liquidity." },
    { t: "mcq", q: "GH Bank's mandate to provide housing finance to lower-income households is an example of which type of regulation?",
      o: ["Credit allocation", "Entry regulation", "Investor protection", "Monetary policy"], a: 0,
      x: "Directing credit toward a socially important sector is credit allocation, the counterpart to US housing and farm credit policies." },
    { t: "mcq", q: "Why did the shift to originate-and-distribute increase risk before 2008?",
      o: ["Banks had to hold more mortgages to maturity", "Originators had less incentive to screen and monitor loans they planned to sell", "Securitization was banned for subprime loans", "It raised capital requirements"], a: 1,
      x: "If you sell the loan within weeks, its later default is someone else's problem. Screening quality degraded and risk moved off balance sheet." }
  ]
});

FI.chapters.push({
  id: "c2", n: 2, note: "฿50",
  title: "Financial Services: Depository Institutions",
  short: "Banks & depositories",
  thesis: "A depository sells products on both sides of its balance sheet: loans and deposits. That makes it profitable, and it also exposes the bank to credit, interest-rate and liquidity risk at the same time.",
  lab: "dupont", labName: "DuPont Bench",
  concepts: [
    { h: "What makes depositories special",
      b: "They offer products on both sides of the balance sheet: <b>loans</b> on the asset side and <b>deposits</b> on the liability side. In 1950, US FI types were sharply distinct. By 2021 product lines had blurred: banks underwrite, sell insurance and offer risk-management products." },
    { h: "Three US groups, and consolidation",
      b: "Commercial banks, savings institutions and credit unions. US commercial banks shrank from 14,416 (1985) to 4,231 (2021), mostly through M&A. Banks with over $10B in assets held <b>86.9%</b> of industry assets in 2021, against 34.5% in 1984.",
      th: "Thailand never had thousands of banks. A small group of large banks (Bangkok Bank, Kasikornbank, Krungthai, SCB, Krungsri, ttb) dominates, sitting alongside foreign bank subsidiaries and branches, retail banks, and the state-owned SFIs. The BOT designates the largest as domestic systemically important banks (D-SIBs)." },
    { h: "Community, regional, money center",
      b: "<b>Community banks</b> are small and local, and real-estate heavy. <b>Regional and superregional banks</b> use the federal funds market to fund their lending. <b>Money center banks</b> (Citigroup, JPMorgan Chase, BNY Mellon) rely heavily on wholesale funding and compete globally.",
      th: "Tiering in Thailand runs through business model more than geography: universal banks, niche banks (Kiatnakin Phatra, Tisco) and foreign exits, such as Citi selling its Thai consumer business to UOB in 2022." },
    { h: "The balance sheet tells you the risks",
      b: "US commercial banks, December 2021. Assets: real estate loans $4,813.8B, C&I loans $2,266.0B, loans to individuals $1,744.7B, securities $5,587.1B. Liabilities: deposits $18,410.3B, borrowings $591.5B. The inferences: <b>credit risk</b> from loans, and <b>interest-rate and liquidity risk</b> from the maturity mismatch between long assets and short deposits.",
      th: "Thai banks are more loan-heavy and deposit-funded. The number to watch is household debt, which has sat near 90% of GDP in recent years. That is credit risk concentrated in mortgages, auto hire-purchase and personal loans." },
    { h: "Equity capital",
      b: "US bank equity was about 10% of total liabilities and equity in 2021. TARP (2008–09) injected capital directly (Citigroup $25B, Bank of America $20B), with about $245B in injections through 2015.",
      th: "Under the BOT's Basel III rules the minimum total capital ratio is 8.5%, plus a 2.5% conservation buffer and an extra 1% for D-SIBs. Large Thai banks typically hold far more, often near 20% of risk-weighted assets." },
    { h: "Off-balance-sheet activities",
      b: "Contingent items that can move onto the balance sheet: <b>guarantees</b> such as letters of credit (a built-in insurance element), <b>loan commitments</b>, and <b>derivatives</b> (futures, forwards, options, swaps). They earn fees and can hedge risk, or create it, as mortgage-backed \"toxic assets\" showed. Fee businesses also include trust services and correspondent banking.",
      th: "A classic Thai OBS item is the bank <b>letter of guarantee</b> that a construction contractor posts for a government tender. Bancassurance commissions are a major fee line for Thai banks." },
    { h: "US regulators and the dual banking system",
      b: "<b>FDIC</b>: deposit insurance (DIF) and preventing runs. <b>OCC</b>: charters and closes national banks. <b>Federal Reserve</b>: monetary policy and lender of last resort; national banks are automatically members. <b>State regulators</b>: state-chartered banks. The coexistence of national and state charters is the <b>dual banking system</b>.",
      th: "Thailand has a single-track system. Under the Financial Institutions Businesses Act B.E. 2551 (2008), the Ministry of Finance grants licences on the BOT's recommendation, and the BOT supervises. The DPA handles deposit protection. SFIs answer to the Ministry of Finance, with inspection delegated to the BOT." },
    { h: "US legislation you must be able to date",
      b: "1927 McFadden (branching limits) · 1933 Glass-Steagall (separated banking and securities, created the FDIC) · 1956 BHC Act · 1978 International Banking Act · 1980 DIDMCA and 1982 Garn-St Germain (deregulation, phased out Regulation Q) · 1987 CEBA · 1989 FIRREA (created the RTC, abolished FSLIC) · 1991 FDICIA (prompt corrective action, risk-based premiums) · 1994 Riegle-Neal (interstate banking) · 1999 FSMA (repealed the Glass-Steagall separation) · 2010 Dodd-Frank (FSOC, CFPB).",
      th: "Thai timeline: 1942 Bank of Thailand founded · 1962 Commercial Banking Act · 1985 FIDF created · 1993 BIBF offshore banking licences · 1997 crisis · 2008 FIBA, the DPA Act and the amended BOT Act · 2017 PromptPay · 2021 DPA cover falls to ฿1M." },
    { h: "Savings institutions and credit unions",
      b: "<b>Thrifts</b> (savings associations and savings banks) were built around mortgages. Fed rate targeting combined with Regulation Q caused disintermediation, and moral hazard plus regulator forbearance deepened the S&L crisis. The QTL test keeps them mortgage-focused. <b>Credit unions</b> are nonprofit, owned by members with a <b>common bond</b>, tax-exempt and CRA-exempt.",
      th: "Thailand's closest counterpart to a credit union is the <b>savings cooperative</b> (สหกรณ์ออมทรัพย์), such as a teachers' or state-employees' co-op. It has a common bond and member ownership, and it sits outside BOT supervision and DPA protection, overseen by the Ministry of Agriculture and Cooperatives." },
    { h: "Reading performance: the DuPont chain",
      b: "Return on equity splits into how profitable the assets are and how much leverage is applied. Profitability splits again into margin and asset use. A high ROE earned purely through a high equity multiplier is a warning sign, not a strength." },
    { h: "Technology in banking",
      b: "<b>Wholesale</b>: account reconciliation, electronic funds transfer, electronic billing, cloud services. <b>Retail</b>: ATMs, smart cards, online and mobile banking, loyalty programmes.",
      th: "Thailand is a global leader in mobile banking and QR payments through PromptPay and Thai QR. The BOT's virtual-bank licences push competition toward digital-only lenders serving the underbanked." },
    { h: "Global issues",
      b: "The US crisis spread worldwide. Many European banks survived only with government and central-bank support, policy rates were pushed to 1% or lower, and bank health became tightly linked to macroeconomic performance." }
  ],
  formulas: [
    ["ROE", "Net income ÷ Total equity"],
    ["ROA", "Net income ÷ Total assets"],
    ["Equity multiplier (EM)", "Total assets ÷ Total equity"],
    ["Profit margin (PM)", "Net income ÷ Total operating income (interest + non-interest income)"],
    ["Asset utilisation (AU)", "Total operating income ÷ Total assets"],
    ["The chain", "ROE = ROA × EM = PM × AU × EM"],
    ["Total capital ratio", "Total capital ÷ Risk-weighted assets"]
  ],
  cards: [
    ["Dual banking system", "National banks (chartered by the OCC) and state-chartered banks coexisting in the US. Thailand has no equivalent."],
    ["Glass-Steagall (1933)", "Separated commercial and investment banking, created the FDIC, and banned interest on demand deposits."],
    ["FDICIA (1991)", "Introduced prompt corrective action and risk-based deposit insurance premiums, and limited too-big-to-fail bailouts."],
    ["Riegle-Neal (1994)", "Allowed interstate bank acquisitions and branching."],
    ["FSMA / Gramm-Leach-Bliley (1999)", "Let banks, insurers and securities firms enter each other's businesses."],
    ["Dodd-Frank (2010)", "Created the FSOC and CFPB, gave power to break up systemic FIs, and required central clearing for some derivatives."],
    ["Regulation Q", "US ceilings on deposit rates. When market rates rose above them, savers fled to money market funds (disintermediation)."],
    ["Regulatory forbearance", "Regulators delaying the closure of insolvent institutions. It deepened the S&L crisis through moral hazard."],
    ["Letter of guarantee (Thailand)", "An off-balance-sheet bank promise to pay if a client fails an obligation, such as a construction tender bond."],
    ["Savings cooperative", "Thailand's credit-union analogue: member-owned, common bond, outside BOT supervision and DPA protection."]
  ],
  quiz: [
    { t: "mcq", q: "Two banks report the same ROE. Bank X gets there with a high ROA and little leverage; Bank Y with a low ROA and a high equity multiplier. Which statement is right?",
      o: ["They are equally safe, because ROE is identical", "Bank Y's return is more fragile: the same ROE rests on a thinner equity cushion, so a small asset loss hurts its owners far more", "Bank X must be taking more credit risk to earn the higher ROA", "ROE cannot be equal if ROA differs"], a: 1,
      x: "ROE = ROA × EM. A high multiplier borrows the return: it magnifies a good year and magnifies a bad one, which is why the DuPont split matters more than the headline ROE." },
    { t: "mcq", q: "In the DuPont identity ROE = ROA × EM, what does the equity multiplier actually measure?",
      o: ["How efficiently the bank's assets generate operating income", "How many baht of assets each baht of equity supports, in other words leverage", "The share of operating income kept as profit after costs", "The bank's capital ratio under Basel III"], a: 1,
      x: "EM = total assets ÷ total equity. A multiplier of 10 means equity funds only a tenth of the balance sheet; the rest is deposits and borrowing." },
    { t: "mcq", q: "A bank's profit margin (net income ÷ total operating income) falls while its asset utilisation is unchanged. What most plausibly happened?",
      o: ["It grew its loan book faster than deposits", "Costs, loan-loss provisions or taxes took a bigger share of each baht of income", "It raised more equity", "Fee income rose"], a: 1,
      x: "ROA = PM × AU. Asset utilisation is the revenue lever (income per baht of assets); profit margin is the cost-control lever (income kept per baht of revenue). Unchanged AU and lower PM points at expenses, provisions or tax." },
    { t: "mcq", q: "Why do Basel rules measure a bank's capital against <em>risk-weighted</em> assets rather than total assets?",
      o: ["Because risk-weighted assets are always larger, which makes banks hold more capital", "So that riskier exposures require more capital behind them than safe ones such as government bonds", "Because total assets are not disclosed", "To make the ratio easier to compute"], a: 1,
      x: "A government bond and an unsecured SME loan should not need the same cushion. Thailand's minimum is 8.5% of risk-weighted assets plus a 2.5% conservation buffer, and another 1% for a D-SIB." },
    { t: "mcq", q: "A bank funds 25-year mortgages with savings deposits. Which risks does the slide deck infer from this balance sheet?",
      o: ["Only credit risk", "Interest-rate and liquidity risk from the maturity mismatch", "Foreign-exchange risk", "Underwriting risk"], a: 1,
      x: "Short, withdrawable liabilities funding long, fixed assets means rising rates squeeze the margin, and withdrawals can force asset sales." },
    { t: "mcq", q: "Which Act introduced prompt corrective action?",
      o: ["Glass-Steagall, 1933", "FIRREA, 1989", "FDICIA, 1991", "Riegle-Neal, 1994"], a: 2,
      x: "FDICIA (1991) introduced PCA and risk-based insurance premiums in response to the S&L and bank failures of the 1980s." },
    { t: "mcq", q: "A contractor bidding on a Bangkok expressway tender gets a letter of guarantee from its bank. On the bank's books this is:",
      o: ["A loan on the asset side", "A deposit liability", "An off-balance-sheet contingent liability", "Equity capital"], a: 2,
      x: "Nothing moves unless the contractor defaults, when the guarantee becomes an on-balance-sheet claim. It carries the insurance-underwriting element the slides mention." },
    { t: "mcq", q: "A teacher keeps ฿2 million at a teachers' savings cooperative that later collapses. What does the DPA pay?",
      o: ["฿1,000,000", "฿2,000,000", "Nothing, because cooperatives are outside DPA protection", "฿100,000"], a: 2,
      x: "The DPA covers deposits at DPA-member financial institutions, which are banks. Cooperatives sit under a different ministry with no deposit insurance." },
    { t: "mcq", q: "What does the \"dual banking system\" refer to?",
      o: ["Banks offering both deposits and loans", "Coexistence of national and state-chartered banks in the US", "Separation of commercial and investment banking", "Banks regulated by both the Fed and the SEC"], a: 1,
      x: "It describes charter choice. Thailand has no counterpart: all commercial bank licences come from the Ministry of Finance, supervised by the BOT." },
    { t: "mcq", q: "Which institution supervises Thai commercial banks day to day?",
      o: ["SEC Thailand", "Office of Insurance Commission", "Bank of Thailand", "Deposit Protection Agency"], a: 2,
      x: "The BOT supervises under FIBA B.E. 2551. The Ministry of Finance grants licences, and the DPA protects deposits but does not supervise." },
    { t: "mcq", q: "During the S&L crisis, what was the effect of regulatory forbearance?",
      o: ["It closed insolvent thrifts quickly", "It let insolvent thrifts keep gambling for resurrection, raising final losses", "It raised Regulation Q ceilings", "It created credit unions"], a: 1,
      x: "Zombie thrifts with nothing to lose took big risks backed by deposit insurance. That is moral hazard." },
    { t: "mcq", q: "Bank X has ROE of 15%, but only because its equity multiplier is 20. What is the right interpretation?",
      o: ["It is the best-run bank in the sample", "Its ROA is only 0.75%, so the return is leverage-driven and fragile", "Its profit margin must be above 50%", "It has more capital than peers"], a: 1,
      x: "ROA = 15% ÷ 20 = 0.75%. Equity of 5% of assets means a 5% asset loss wipes it out." }
  ]
});
