FI.chapters.push({
  id: "c3", n: 3, note: "฿100",
  title: "Financial Services: Finance Companies",
  short: "Finance companies",
  thesis: "A finance company lends like a bank but takes no deposits. It funds itself in capital markets, has to earn market trust without a safety net, and often serves the borrowers banks turn away.",
  lab: "flat", labName: "Flat-Rate X-Ray",
  concepts: [
    { h: "History",
      b: "Finance companies grew out of Depression-era <b>installment credit</b>. GE Capital and GMAC expanded into broad product lines, and bank competition grew from the 1950s. In the crisis, the Fed controversially approved <b>GMAC</b> (now Ally) as a bank holding company. That opened access to about $6B in government bailout funds, on condition that GM cut its stake from 49% to under 10%." },
    { h: "Lending without deposits",
      b: "Their activities resemble banks' but there is <b>no depository function</b>. Some specialise (auto installment loans), others diversify into consumer loans and corporate finance, especially <b>factoring</b>: buying receivables at a discount. <b>Commercial paper</b> is the key funding source. The industry is highly concentrated, with the largest 20 firms holding about 65% of assets." },
    { h: "Three types, plus captives",
      b: "<b>Sales finance</b>: loans to customers of a particular retailer or manufacturer (Ford Motor Credit). <b>Personal credit</b>: consumer loans (HSBC Finance, AIG American General). <b>Business credit</b>: equipment leasing and factoring (CIT Group). A <b>captive</b> finance company is wholly owned by a manufacturer to finance its own products.",
      th: "Thai examples of each type. Captives: <b>Toyota Leasing (Thailand)</b> and other carmakers' finance arms. Personal credit: card and personal-loan companies such as KTC and AEON Thana Sinsap. Title loans (using a car or motorbike registration book as collateral): Muangthai Capital and Srisawad." },
    { h: "Consumer loans: riskier borrowers",
      b: "Mainly motor vehicle loans and leases. After 9/11, captives offered 0% financing to move cars, a promotion that ran into 2005. In general, finance companies serve riskier, often subprime, customers. The slides' extremes are <b>payday loans</b> at around <b>390% APR</b>, regulated by states through usury limits and dodged by partnering with national banks in states without caps.",
      th: "Thai rate ceilings are set by product and regulator. BOT-supervised credit cards are capped at 16% a year, personal loans at 25%, and vehicle title loans at 24%. The OCPB caps hire-purchase at 10% (new cars), 15% (used cars) and 23% (motorcycles) as effective rates. Informal loan sharks, including daily-repayment \"helmet loans\", are the payday-loan counterpart." },
    { h: "Mortgages and home equity",
      b: "Mortgages, both direct and securitized, became a major asset class. US home equity lending boomed after the Tax Reform Act of 1986 kept interest deductible on those loans. Defaults on subprime and even prime mortgages in 2007–08 were the root of the 2008–09 crisis." },
    { h: "Business loans",
      b: "These are the largest share of finance company loans, about 30%. The edge over banks: fewer regulatory limits on products, no depository status (so lower overheads and less scrutiny), deep specialist expertise, and a greater willingness to take risky clients. Subcategories: motor vehicle loans and leases, equipment loans and leases (with tax advantages when the finance company owns the asset), and securitized business assets." },
    { h: "Liabilities and liquidity",
      b: "The main liabilities are commercial paper and longer-term notes and bonds. Finance companies are the largest issuers of CP, often through direct sale. With no deposits and no lender of last resort, liquidity risk is managed differently: they depend on rolling over market funding.",
      th: "Thai non-bank lenders fund themselves mainly with bank loans and <b>debentures sold to investors</b>, often retail high-net-worth buyers. When the corporate bond market freezes, as in March 2020, these firms face refinancing risk." },
    { h: "Performance and crisis",
      b: "Early 2000s: strong demand and low rates made the best firms takeover targets (Citigroup bought Associates First Capital, AIG bought American General, HSBC bought Household). In 2005–06, falling home prices and rising rates hit hard and subprime lending was cut back. Mortgage delinquencies reached an all-time high of 6.89% at the end of 2009. Countrywide and CIT Group failed." },
    { h: "Regulation",
      b: "The Fed defines a finance company as a non-depository firm whose primary assets are loans to individuals and businesses. Finance companies face state usury ceilings, are not subject to the CRA, and carry a lighter burden than depositories. Scrutiny rose after the Fed rescued several of them, and under Dodd-Frank. Without a safety net they must <b>signal soundness</b> to markets: their capital-to-assets ratio was 14.3% versus 11.5% for banks in 2012, and captives may use parent guarantees or letters of credit.",
      th: "In Thailand, the legal category of <b>finance company</b> (บริษัทเงินทุน) is licensed under FIBA. It was all but wiped out in 1997, when 56 of these firms were closed. Today's non-bank lenders sit under a patchwork: the BOT (cards, personal and title loans), the OCPB (hire-purchase contracts), and the Ministry of Finance (nano and pico finance)." },
    { h: "Global issues",
      b: "Outside the US, finance companies are usually subsidiaries of commercial banks or industrial groups. Non-bank FIs grew in Latin America and Europe. New Zealand saw consolidation, collapses and restructuring among its finance companies." }
  ],
  formulas: [
    ["Payday APR (simple)", "Fee per period ÷ amount borrowed × periods per year"],
    ["Flat-rate installment", "(Principal + Principal × flat rate × years) ÷ number of months"],
    ["Effective rate", "The monthly rate r that solves Principal = Installment × [1 − (1+r)^−n] ÷ r, times 12"],
    ["Factoring cost (annualised)", "Discount ÷ cash advanced × 365 ÷ days to collection"]
  ],
  cards: [
    ["Finance company (Fed definition)", "A firm, other than a depository institution, whose primary assets are loans to individuals and businesses."],
    ["Captive finance company", "A wholly owned subsidiary that finances the parent manufacturer's products, such as Ford Credit or Toyota Leasing (Thailand)."],
    ["Factoring", "Buying a firm's accounts receivable at a discount and taking over collection."],
    ["Sales vs personal vs business credit", "Sales finance lends to a retailer's customers, personal credit makes consumer loans, and business credit does leasing and factoring."],
    ["Why more capital than banks?", "No deposit insurance or lender of last resort, so they must signal soundness to CP and bond investors."],
    ["Flat rate trap", "A flat rate charges interest on the original principal for the whole term. The effective rate is nearly double."],
    ["Payday loan", "A short-term, small-dollar loan against the next paycheque. In the slides: about 390% APR."],
    ["Thailand's 1997 finance companies", "58 suspended in 1997 (16 in June, 42 in August) and 56 permanently closed in December."]
  ],
  quiz: [
    { t: "mcq", q: "What most clearly separates a finance company from a commercial bank?",
      o: ["It cannot make business loans", "It does not take deposits", "It is exempt from all regulation", "It only lends to governments"], a: 1,
      x: "Finance companies lend much like banks but have no depository function, so they need market funding and have no deposit insurance." },
    { t: "mcq", q: "What is the key funding source for US finance companies?",
      o: ["Demand deposits", "Commercial paper", "Central bank reserves", "Insurance premiums"], a: 1,
      x: "Finance companies are the largest CP issuers, often through direct placement." },
    { t: "mcq", q: "A payday lender quotes “฿15 per ฿100 for two weeks”. Why do the slides translate that into an APR near 390%?",
      o: ["Because the fee compounds daily", "Because annualising the per-period fee (15% × 26 periods) exposes a cost that the small-sounding fee hides", "Because payday loans above 390% are illegal", "Because the borrower must repay 390% of the principal"], a: 1,
      x: "Fee per period × periods per year is the simple APR. It is the only honest way to compare a two-week loan with an annual rate, and it is why state usury laws bite these lenders." },
    { t: "mcq", q: "Why does a 3% <em>flat</em> rate on a car loan cost far more than a 3% effective rate?",
      o: ["Flat interest is charged on the original principal for the whole term, even as the balance is repaid month by month", "Flat rates compound monthly", "Flat rates include a hidden fee", "They cost the same; flat is just another name for effective"], a: 0,
      x: "Over a 48-month contract the average balance outstanding is only about half the original loan, yet the interest is computed on the full amount. That is why 3% flat is roughly 5.7% effective." },
    { t: "mcq", q: "For Nok's loan (3% flat, 48 months), roughly what is the true effective annual rate?",
      o: ["3.0%", "About 4.0%", "About 5.7%", "About 12%"], a: 2,
      x: "Solving ฿500,000 = ฿11,666.67 × annuity factor gives about 0.47% a month, or <b>≈5.7% a year</b>. Nok repays principal every month but pays interest as if the full ฿500,000 were outstanding for four years. Try it in the Flat-Rate X-Ray lab." },
    { t: "mcq", q: "A factor pays an exporter 97% of an invoice today and collects the full amount in 60 days. Why is the true annual cost much higher than 3%?",
      o: ["Because the factor also charges interest on top of the discount", "Because the 3% discount is earned in just 60 days, so annualised it is roughly six times larger", "Because the exporter pays tax on the advance", "It is not; 3% is the annual cost"], a: 1,
      x: "Any discount for early cash is a rate over a short period. Scale it to a year and factoring starts to look like an 18 to 19% loan, which is the price of not waiting for the customer to pay." },
    { t: "mcq", q: "Toyota Leasing (Thailand) financing Toyota vehicles for Thai buyers is best described as:",
      o: ["A business credit institution", "A captive finance company", "A savings institution", "A personal credit institution"], a: 1,
      x: "It is owned by the manufacturer and exists to finance the parent's products, the same model as Ford Motor Credit." },
    { t: "mcq", q: "In 2012, US finance companies held more capital relative to assets than commercial banks (14.3% vs 11.5%). Why?",
      o: ["Regulators impose stricter capital rules on them", "Without deposit insurance or a lender of last resort, they must signal safety to market lenders", "They have no credit risk", "Their loans are all government-guaranteed"], a: 1,
      x: "Less regulation means less implicit support, so market discipline does the job: CP buyers demand a thicker equity cushion." },
    { t: "mcq", q: "How many Thai finance companies did the Bank of Thailand suspend in 1997?",
      o: ["16", "42", "58", "91"], a: 2,
      x: "16 in June and 42 in August, 58 in total. Of those, 56 were permanently closed in December 1997." },
    { t: "mcq", q: "Why did the Fed's approval of GMAC as a bank holding company matter in 2008?",
      o: ["GMAC could then accept deposits from GM dealers only", "It gave GMAC access to government bailout money (about $6B)", "It exempted GMAC from Dodd-Frank", "It forced GMAC to stop auto lending"], a: 1,
      x: "BHC status brought GMAC inside the safety net, conditional on GM cutting its stake to below 10%." }
  ]
});
