FI.chapters.push({
  id: "c4", n: 4, note: "฿500",
  title: "Financial Services: Securities Brokerage and Investment Banking",
  short: "Securities & IBs",
  thesis: "Securities firms earn their living by moving risk: underwriting it, making markets in it, and advising on it. They do this on thin capital and overnight repo funding, which is exactly why 2008 destroyed the stand-alone model.",
  lab: "underwrite", labName: "Underwriting Desk",
  concepts: [
    { h: "The three core businesses",
      b: "<b>Underwriting</b> new securities, <b>market making</b> (quoting bid and ask prices, holding inventory), and <b>advising</b> on M&A and restructurings. US domestic M&A went from under $200B (1990) to $1.83T (2000), down to $458B (2002), up to $1.7T (2007), and back to $687B (2010)." },
    { h: "How underwriting works",
      b: "<b>Public offerings</b> (IPOs and seasoned issues) or <b>private placements</b>. In a <b>firm commitment</b> the IB buys the whole issue at the bid price and resells at the offer price; the gross spread is its reward and unsold stock is its loss. In a <b>best-efforts</b> deal the IB acts as agent and returns unsold securities to the issuer.",
      th: "On the SET, IPO lead underwriters are securities companies (บล.) or the securities arms of bank groups. Bond underwriting for Thai corporates is dominated by the big banks, which also distribute debentures to their own high-net-worth clients. That concentrates reputational risk when an issuer defaults." },
    { h: "The 2008 restructuring",
      b: "Bear Stearns was sold to JPMorgan Chase. Lehman Brothers went bankrupt. Merrill Lynch was acquired by Bank of America. <b>Goldman Sachs and Morgan Stanley</b>, the only two major survivors, converted to bank holding companies in 2008, trading heavier regulation for access to the Fed's safety net." },
    { h: "Types of firms",
      b: "<b>National full-line firms</b> (BofA Merrill, Morgan Stanley) · <b>national full-line firms specialising in corporate finance</b> (Goldman Sachs) · large investment banks and boutiques (Lazard, Greenhill) · regional securities firms · specialised discount brokers, electronic trading firms and venture capital firms. The number of firms grew sharply from 1980 to 1987, then fell 37% after the 1987 crash." },
    { h: "Activities in full",
      b: "Investment banking · venture capital · market making (online trading, decimalisation, technology risk) · <b>trading</b>: position trading, <b>pure arbitrage</b> (locking in a riskless price gap), <b>risk arbitrage</b> (taking positions on announced events such as mergers), program trading · investing and fund management · cash management · M&A · back-office services." },
    { h: "Trends",
      b: "Commissions have fallen since 1987. There were record volumes from 1995 to 2000, and pretax profits hit $31.6B in 2000. Profits dropped in 2001–02 after the dot-com crash, 9/11 and the scandals, recovered in the mid-2000s, hit new lows in 2008, and rebounded in 2009. The broker model is shifting from <b>commission-based to fee-based</b> services.",
      th: "Thai brokerage commissions were liberalised in the 2010s. Retail brokers now compete on app-based trading with minimal commissions, pushing them toward wealth management, margin lending and fund distribution." },
    { h: "Balance sheet",
      b: "<b>Assets</b>: reverse repurchase agreements, receivables from other broker-dealers, and long positions in securities and commodities. That means market, interest-rate and FX risk. <b>Liabilities</b>: <b>repos</b> (the major funding source), payables to customers and other broker-dealers, and securities sold short. <b>Capital is much thinner than at banks.</b>" },
    { h: "US regulation",
      b: "The SEC is the primary regulator (confirmed by NSMIA, 1996). In the early 2000s state attorneys general gained ground, notably New York vs Merrill Lynch, and the 2003 settlement brought $1.4B in penalties over analyst conflicts. <b>Sarbanes-Oxley (2002)</b>, prompted by Enron, WorldCom, Tyco and Global Crossing, created an independent audit oversight board. <b>FINRA</b> handles day-to-day oversight: trading abuses, rule violations and capital. Dodd-Frank added the FSOC, Fed supervision of systemic firms, and securitisation and credit rating agency rules.",
      th: "<b>SEC Thailand</b> (ก.ล.ต.) licenses and supervises securities companies under the Securities and Exchange Act B.E. 2535 (1992). The SET runs market surveillance of its members, and SEC Thailand also regulates digital asset exchanges under the 2018 Digital Asset Decree." },
    { h: "Investor protection",
      b: "<b>SIPC</b> protects customers up to $500,000 if a broker-dealer fails and client assets go missing. It does <b>not</b> cover market losses. After October 2003, Patriot Act provisions imposed anti-money-laundering identity checks.",
      th: "The core Thai protection is <b>segregation of client assets</b>: brokers must keep client cash and securities separate from their own. Market losses are never covered, anywhere." },
    { h: "Global issues",
      b: "Competition between US and European firms, and growing cross-border trading in both directions. After the crisis, global concern over capital, liquidity and leverage led to strategic alliances and exits from foreign markets." }
  ],
  formulas: [
    ["Gross spread (per share)", "Offer price − bid price paid to issuer"],
    ["Firm commitment P/L", "(Actual sale price − bid price) × shares"],
    ["Issuer proceeds, best efforts", "Shares actually sold × offer price − fees"],
    ["Pure arbitrage profit", "(Higher price − lower price) × quantity"]
  ],
  cards: [
    ["Firm commitment", "The underwriter buys the whole issue at the bid price and resells it, bearing the risk of unsold or underpriced securities."],
    ["Best efforts", "The underwriter sells as the issuer's agent. Unsold securities go back to the issuer, and the underwriter has no price risk."],
    ["Private placement", "Securities sold directly to a small number of large investors, with no public offering."],
    ["Pure vs risk arbitrage", "Pure arbitrage locks in a riskless price gap. Risk arbitrage takes positions on announced events such as mergers."],
    ["Repo (for a broker-dealer)", "Selling securities with an agreement to repurchase them: short-term secured borrowing and the main funding source."],
    ["SIPC", "Covers up to $500,000 of missing customer assets if a broker fails. Market losses are not covered."],
    ["NSMIA (1996)", "Confirmed the SEC as primary regulator of securities firms, pre-empting most state oversight."],
    ["Sarbanes-Oxley (2002)", "The response to Enron and WorldCom: an independent auditing oversight board under the SEC."]
  ],
  quiz: [
    { t: "mcq", q: "Under a firm commitment underwriting, where does the underwriter's profit come from?",
      o: ["A commission per share sold, paid by investors", "The spread between the price paid to the issuer and the public offer price, on every share in the issue", "Interest earned on the issuer's proceeds", "A listing fee shared with the exchange"], a: 1,
      x: "The underwriter buys the whole issue and resells it. The spread is its gross profit, and the issuer's proceeds are fixed the moment the shares are bought." },
    { t: "mcq", q: "Demand turns weak and the shares can only be sold below the price the underwriter paid the issuer. Under a firm commitment, who bears the loss?",
      o: ["The issuer, who receives less than planned", "The underwriter: the issuer's proceeds were fixed when the shares were bought, so the price risk sits with the underwriter", "The investors, who are refunded the difference", "The stock exchange"], a: 1,
      x: "That is the whole meaning of “firm”. It is also why underwriters syndicate large deals: to share exactly this risk." },
    { t: "mcq", q: "In a best-efforts offering, who bears the risk that shares remain unsold?",
      o: ["The underwriter", "The issuer", "SIPC", "The stock exchange"], a: 1,
      x: "The underwriter acts only as agent. Unsold securities go back to the issuer, which is why weaker issuers get best-efforts deals." },
    { t: "mcq", q: "A trader buys shares of a target company right after a takeover announcement, betting that the deal completes. This is:",
      o: ["Pure arbitrage", "Risk arbitrage", "Program trading", "Market making"], a: 1,
      x: "There is real risk the deal fails, so it is not riskless. That makes it risk arbitrage." },
    { t: "mcq", q: "A desk buys a bond from one dealer and at the same moment sells it to another at a higher price. What makes this pure arbitrage rather than a bet?",
      o: ["It uses borrowed money", "Both legs happen at once, so there is never an open position and no price risk", "It relies on the price rising later", "It requires a takeover announcement"], a: 1,
      x: "Pure arbitrage is simultaneous and riskless; it exists only while prices are inconsistent across dealers. Risk arbitrage, by contrast, holds a position and waits." },
    { t: "mcq", q: "What is the major source of funds for a securities firm?",
      o: ["Retail deposits", "Repurchase agreements", "Insurance premiums", "Central bank loans"], a: 1,
      x: "Overnight and short-term repos. That funding vanished for Bear Stearns and Lehman in 2008." },
    { t: "mcq", q: "Which firms survived 2008 as independent major investment banks, converting to bank holding companies?",
      o: ["Lehman Brothers and Bear Stearns", "Merrill Lynch and Lehman", "Goldman Sachs and Morgan Stanley", "Citigroup and JPMorgan"], a: 2,
      x: "Bear went to JPMorgan, Merrill to Bank of America, and Lehman failed. GS and MS became BHCs in September 2008." },
    { t: "mcq", q: "A brokerage client's shares fall 40% in a market crash, and separately a broker fails with client assets missing. SIPC helps with:",
      o: ["Both", "Only the 40% market loss", "Only the missing assets, up to $500,000", "Neither"], a: 2,
      x: "SIPC restores missing customer property when a broker fails. It never insures investment losses." },
    { t: "mcq", q: "Which legislation created an independent auditing oversight board after Enron and WorldCom?",
      o: ["NSMIA 1996", "Sarbanes-Oxley 2002", "Dodd-Frank 2010", "Securities Act 1933"], a: 1,
      x: "SOX (2002) created the PCAOB under the SEC." },
    { t: "mcq", q: "Which body is the primary regulator of securities companies in Thailand?",
      o: ["Bank of Thailand", "SEC Thailand (ก.ล.ต.)", "Office of Insurance Commission", "Ministry of Commerce"], a: 1,
      x: "SEC Thailand licenses and supervises securities businesses under the SEC Act B.E. 2535. The SET conducts member market surveillance." }
  ]
});

FI.chapters.push({
  id: "c5", n: 5, note: "฿1000",
  title: "Financial Services: Mutual Funds and Hedge Funds",
  short: "Mutual & hedge funds",
  thesis: "A mutual fund sells small savers diversification at scale and marks it to market every day. A hedge fund sells skill with leverage and little transparency. Their failures look very different, and so does their regulation.",
  lab: "fees", labName: "Fee Drag",
  concepts: [
    { h: "Why mutual funds exist",
      b: "They give small investors <b>diversification</b> and <b>economies of scale</b> in trading and management. Most are <b>open-ended</b>. By asset size, mutual funds are the second most important FI group. In 2020 there were more than 7,636 funds with $23.89T in assets." },
    { h: "Growth",
      b: "The first fund was in Boston in 1924. <b>Money market mutual funds</b> arrived in 1972 as a way around <b>Regulation Q</b> deposit caps. Net assets: 1990 $1,065.2B · 2000 $6,964.6B · 2007 $12,001.5B · 2008 $9,603.6B (a 20% drop) · 2020 $23,895.8B. Growth slowed in the early 2000s partly because of trading abuses.",
      th: "Thai funds are run by <b>asset management companies</b> (บลจ.) under SEC Thailand. Much of the growth came from tax-advantaged products: RMF for retirement, SSF (2020–24), and the <b>Thai ESG</b> fund (from 2023)." },
    { h: "Long-term funds vs money market funds",
      b: "Long-term funds (equity, bond, hybrid) were 81.9% of assets in 2020, and MMMFs 18.1%. The MMMF share swings with the interest-rate spread: 25.7% (1999), 40.9% (2008 flight to safety), 18.1% (2020). MMMFs are <b>uninsured</b>, which is why they pay more than deposits. In September 2008 the <b>Reserve Primary Fund</b> suffered a run because of its Lehman exposure, and the government temporarily extended insurance to MMMFs." },
    { h: "Returns and NAV",
      b: "Investors earn in three ways: income and dividends, capital gains realised on trades, and capital appreciation on holdings. Holdings are <b>marked to market</b> daily to compute <b>net asset value</b>. Open-end funds issue and redeem units at NAV." },
    { h: "Open-end, closed-end, ETFs",
      b: "<b>Open-end</b> funds create and redeem units at NAV. <b>Closed-end</b> funds have a fixed number of shares that trade on an exchange, often at a <b>premium or discount</b> to NAV; REITs are an example. <b>ETFs</b> trade intraday on exchanges.",
      th: "SET-listed property funds, REITs and infrastructure funds are closed-end vehicles. Their price can sit well below NAV when investors doubt the valuation or the tenants." },
    { h: "Costs: loads and expenses",
      b: "<b>Sales loads</b>: front-end (charged on purchase) or back-end (deferred, on redemption). Their drag usually outweighs the benefit, especially for short horizons. <b>Operating expenses</b>: management fees and <b>12b-1</b> distribution fees. Share classes A (front load), B (back load) and C (level fees) spread these differently. Fees fell sharply in 2005–06 under SEC pressure.",
      th: "Thai funds commonly show a front-end fee, a back-end fee and switching fees in the fund fact sheet. The annual total expense ratio is the silent drag, and over 20 years it matters far more than the load." },
    { h: "Balance sheet",
      b: "<b>MMMFs</b> hold short-term securities, consistent with their deposit-like role. Most keep a $1 share price and adjust the number of shares instead, which gives them significant liquidity risk. <b>Long-term funds</b> were over 53.3% stocks in 2020, with credit market instruments next. They shift toward credit when equities disappoint.",
      th: "In March 2020, Thai daily fixed-income funds were hit by redemptions as the corporate bond market froze. The BOT opened a Mutual Fund Liquidity Facility through banks and created a ฿400bn Corporate Bond Stabilization Fund. This is a direct test of the MMMF liquidity risk described in the slides." },
    { h: "Regulation",
      b: "Mutual funds are among the most closely regulated non-depository FIs. The SEC focuses on disclosure and anti-fraud, and NASD (now FINRA) supervised distribution. The early-2000s scandals involved <b>market timing</b>, <b>late trading</b>, directed brokerage and improper fees. The responses: independent directors, more disclosure, and a mandatory <b>chief compliance officer</b> from 2004 who reports to the fund's board. Key laws: 1933 and 1934 Acts, 1940 Investment Company Act, 1988 Insider Trading Act, 1990 Market Reform Act (circuit breakers), 1996 NSMIA, 2002 SOX." },
    { h: "Global",
      b: "Worldwide fund assets rose from $4.545T (1999) to $14.130T (2007), up 211%, then fell to $9.316T in 2008. Growth is greatest in advanced markets. Japan declined in the late 1990s, and barriers to US sponsors fell in Europe, China and the rest of Asia." },
    { h: "Hedge funds",
      b: "Hedge funds are not mutual funds. Before 2010 they were largely unregulated, using exemptions for fewer than 100 investors or accredited investors only. Styles: <b>market directional</b> (higher risk), <b>market neutral or value</b> (moderate risk), and <b>risk avoidance</b>. Fees are a management fee plus a performance fee (classically \"2 and 20\"). Offshore centres include the Cayman Islands, Bermuda, Dublin and Luxembourg, offering light rules, anonymity and tax advantages." },
    { h: "Hedge fund failures and Dodd-Frank",
      b: "<b>LTCM</b> (1998) needed a $3.6B rescue. Later scandals: illegal trading with mutual funds, UBS and Morgan Stanley (2007), <b>Madoff</b>'s Ponzi scheme (2008), Galleon insider trading (2009). <b>Dodd-Frank</b> requires advisers with assets over $100M to register with the SEC; smaller ones are overseen by states, and the largest face Fed oversight." }
  ],
  formulas: [
    ["NAV", "(Market value of assets − liabilities) ÷ units outstanding"],
    ["Units bought with a front-end load", "Investment × (1 − load) ÷ NAV"],
    ["Premium / discount", "(Market price − NAV) ÷ NAV"],
    ["Hedge fund fees (2 and 20)", "2% × assets + 20% × profits (check the fund's hurdle and high-water mark)"],
    ["Fee drag", "Final value = Investment × (1 + gross return − expense ratio)^years"]
  ],
  cards: [
    ["Net asset value", "The market value of a fund's assets (minus liabilities) per unit, marked to market daily. Open-end funds trade at NAV."],
    ["Closed-end fund", "A fixed number of shares traded on an exchange, which may sit at a premium or discount to NAV. REITs are an example."],
    ["Breaking the buck", "An MMMF's NAV falling below $1.00. Reserve Primary fell to $0.97 in September 2008 after Lehman defaulted."],
    ["Market timing vs late trading", "Market timing is rapid in-and-out trading that exploits stale NAVs. Late trading is illegally buying at today's NAV after the 4pm close."],
    ["12b-1 fee", "An annual fee charged to fund assets to pay for marketing and distribution."],
    ["Load vs no-load", "A load fund charges a sales commission on purchase (front) or redemption (back). A no-load fund does not."],
    ["Chief compliance officer (2004)", "Reports to the fund's directors, not its executives. Polices personal trading and ensures accurate reporting."],
    ["Hedge fund registration (Dodd-Frank)", "Advisers with over $100M in assets register with the SEC and report to it. Smaller advisers are overseen by states."],
    ["Thai ESG fund", "A Thai tax-deductible fund investing in Thai ESG-rated equities and bonds, launched in 2023."]
  ],
  quiz: [
    { t: "mcq", q: "What is an open-end fund's NAV per unit?",
      o: ["The price at which units last traded on the exchange", "(Market value of assets − liabilities) ÷ units outstanding, marked to market every day", "The original subscription price of the fund", "Total assets ÷ number of investors"], a: 1,
      x: "Open-end funds issue and redeem at NAV, so the number has to be honest and current. That is why funds mark to market daily." },
    { t: "mcq", q: "One of a fund's holdings rises in price and nothing else changes. What happens to the NAV per unit?",
      o: ["Nothing until the fund actually sells the shares", "It rises, because assets are marked to market whether or not anything is sold", "It falls, because units are diluted", "It depends on how many investors the fund has"], a: 1,
      x: "Mark-to-market means unrealised gains and losses flow straight into NAV. Investors who redeem today get today's prices, not the fund's purchase prices." },
    { t: "mcq", q: "How does a front-end load affect a new investor?",
      o: ["It reduces the amount actually invested, so fewer units are bought at the same NAV", "It raises the NAV of the fund", "It is refunded when the investor exits", "It is charged every year the investment is held"], a: 0,
      x: "A 1.5% load on ฿100,000 means only ฿98,500 buys units. The fund's NAV is untouched; the cost is borne entirely by the investor on the way in." },
    { t: "mcq", q: "A closed-end fund's units trade below its NAV. Why can that discount persist?",
      o: ["Because the fund must redeem units at the market price", "Because the fund does not redeem units; the price is set by supply and demand on the exchange, not by NAV", "Because the NAV is calculated wrongly", "Because closed-end funds hold no real assets"], a: 1,
      x: "With a fixed number of units there is no arbitrage that forces price to NAV. Discounts of 8 to 10% are normal for listed property funds and REITs on the SET." },
    { t: "mcq", q: "“2 and 20” means a hedge fund charges 2% of assets plus 20% of profits. Which incentive does the performance fee create?",
      o: ["To keep the fund as small as possible", "To take more risk, because the manager shares the gains but not the losses, which is why hurdles and high-water marks exist", "To hold only cash", "To lower the management fee"], a: 1,
      x: "Investors keep a large majority of gains but carry all of the losses. A hurdle rate and a high-water mark are the contract's way of tempering the manager's option-like payoff." },
    { t: "mcq", q: "Fund A charges 1.5% a year, Fund B 0.25%, on the same gross return. Why is the gap in final wealth after 20 years so large?",
      o: ["Fees are deducted from principal only", "The fee difference compounds: every year's fee removes money that would itself have earned returns for the remaining years", "Fund B takes more risk", "Fees are charged only in the last year"], a: 1,
      x: "A 1.25-point gap sounds trivial and ends up costing roughly a quarter of the final sum over two decades. The Fee Drag lab lets you watch it happen." },
    { t: "mcq", q: "Why did the Reserve Primary Fund break the buck in September 2008?",
      o: ["It held Lehman Brothers commercial paper that became worthless", "It invested in Thai government bonds", "The SEC banned money market funds", "Interest rates rose sharply"], a: 0,
      x: "Its roughly $785m of Lehman paper was written down, NAV fell to $0.97, and redemptions surged across the MMMF industry." },
    { t: "mcq", q: "An investor places an order at 5:30pm but is illegally given that day's 4:00pm NAV. This is:",
      o: ["Market timing", "Late trading", "Directed brokerage", "Front running"], a: 1,
      x: "Late trading exploits news released after the close at a stale price. Market timing is legal but abusive rapid trading." },
    { t: "mcq", q: "Which of these is a closed-end investment vehicle?",
      o: ["A daily fixed-income fund", "A REIT listed on the SET", "An RMF that redeems at NAV", "A money market fund"], a: 1,
      x: "REITs and property funds have a fixed number of units that trade on the exchange, so their price can differ from NAV." },
    { t: "mcq", q: "Under Dodd-Frank, which hedge fund advisers must register with the SEC?",
      o: ["All of them", "Those with over $100 million in assets", "Only offshore funds", "Only funds with over 100 investors"], a: 1,
      x: "Over $100M: SEC registration and reporting. Under $100M: the states oversee. Systemically large funds face Fed oversight." }
  ]
});
