FI.chapters.push({
  id: "c6", n: 6, note: "฿10",
  title: "Financial Services: Insurance",
  short: "Insurance companies",
  thesis: "Insurers sell a promise to pay later and invest the money in the meantime. Life insurers manage long, predictable obligations; property-casualty insurers manage short, violent ones. Both fail the same way: when the risks they pooled turn out to move together.",
  lab: "combined", labName: "Underwriting Ledger",
  concepts: [
    { h: "Two industries under one word",
      b: "The chapter splits insurance into <b>life</b> and <b>property and casualty (P&amp;C)</b>. Life insurers underwrite the timing of death, sickness and retirement: obligations that are long, statistically smooth and payable in cash. P&amp;C insurers underwrite fire, motor, liability and catastrophe: obligations that are short, lumpy and sometimes all triggered at once. The difference in the risks drives every difference in the balance sheets.",
      th: "Thailand keeps the split in law as well as in practice: life insurers sit under the Life Insurance Act and non-life insurers under the Non-Life Insurance Act (both B.E. 2535 / 1992), with the <b>OIC</b> (คปภ., Office of Insurance Commission) supervising both. \"Non-life\" (วินาศภัย) is the local term for what the textbook calls property and casualty." },
    { h: "Insurance and the financial crisis",
      b: "Insurers matter to a crisis as <b>investors in securities</b>. Their subprime mortgage pools fell in value and their <b>credit default swaps</b> fell with them. <b>AIG</b> was a major writer of CDS protection, and the potential impact on the companies that had bought that protection was used to justify its bailout. The lesson of the slides is blunt: the risk exposure of insurers had increased, and it sat outside the business of underwriting policies.",
      th: "The Thai parallel is not AIG but the <b>Jer-Jai-Jop</b> (เจอ จ่าย จบ) COVID policies of 2021–22, where four non-life insurers lost their licences. Different mechanism, same principle: an exposure that looked diversified was in fact one single risk, held many times over." },
    { h: "Size, structure and composition",
      b: "The life industry has consolidated hard. In <b>1988</b> there were about <b>2,300</b> US life insurance companies with aggregate assets of <b>$1.1 trillion</b>. By <b>2012</b> there were about <b>1,000</b> with <b>$5.6 trillion</b>, and by <b>2020</b> about <b>750</b> with <b>$8.1 trillion</b>. Fewer firms, far more assets each. The slides note the consolidation is real but <b>not on the scale seen in banking</b>, and that competition comes from inside the industry and from other FIs." },
    { h: "Mutual, stock, and the move between them",
      b: "A <b>mutual</b> insurer is owned by its policyholders; a <b>stock</b> insurer is owned by shareholders. The trend in the slides is <b>conversion to stockholder-controlled companies</b> (demutualization), which buys access to equity capital markets and an acquisition currency, at the cost of a new set of owners whose interests are not identical to the policyholders'.",
      th: "Most Thai life insurers are stock companies, often with a foreign parent or partner: AIA, FWD, Muang Thai Life with Ageas, Thai Life with Meiji Yasuda. Distribution runs heavily through <b>bancassurance</b>, which is where this chapter meets Chapter 2." },
    { h: "Adverse selection",
      b: "The people most eager to buy insurance are the people most likely to claim, so the <b>insured population carries higher risk than the general population</b>. Price from general-population tables and you lose money. The standard remedy in the slides is <b>grouping policyholders into risk pools</b> and pricing each pool separately, supported by underwriting questions, medical evidence and waiting periods." },
    { h: "Life insurance products",
      b: "<b>Ordinary life</b> is the individual market: <b>term</b> (pure protection for a period), <b>whole</b> (protection plus a savings element for life), <b>endowment</b> (pays on death or at a set date), and the investment-linked generation of <b>variable</b>, <b>universal</b> and <b>variable universal</b> life, which unbundle the savings and let the policyholder vary premiums or investment allocation. <b>Group life</b> covers an employer's whole workforce under one contract. <b>Industrial life</b> is the historical small-premium, door-collected policy. <b>Credit life</b> pays off a loan if the borrower dies.",
      th: "Endowments have long dominated Thai life sales, helped by the tax deduction for qualifying premiums. Credit life is routinely bundled with Thai mortgages and hire-purchase contracts, which is why Chapter 3's lenders keep appearing in insurance statistics." },
    { h: "Other life insurer activities",
      b: "<b>Annuities</b> are described in the slides as the <b>reverse of life insurance</b>: instead of accumulating a fund that pays out on death, the insurer takes a fund and pays it out over a life. <b>Private pension funds</b> put life insurers in direct competition with other financial service companies. <b>Accident and health</b> cover, also called <b>morbidity</b> insurance, insures sickness and injury rather than death.",
      th: "Thailand's RMF and provident funds are the pension layer, run mostly by asset management companies under SEC Thailand rather than by insurers, so the competition the slides describe plays out across two regulators here." },
    { h: "The life balance sheet",
      b: "Assets are <b>long-term</b>, because the savings component of policies has to earn a competitive return: bonds, equities, government securities and <b>policy loans</b> (lending the policyholder their own accumulated value). Liabilities are long-term too, dominated by <b>net policy reserves</b>, the amount set aside to meet expected future claims. Long assets against long liabilities is a deliberate match, and it is the opposite of a bank's position." },
    { h: "Life insurers in the crisis and after",
      b: "The crisis hit through the asset side: falling securities values produced <b>capital losses on bonds and stocks</b>, while historically low short-term interest rates made it hard to keep paying the rates promised on existing policies and to price new ones attractively. That combination gives policyholders an <b>incentive to surrender existing policies</b>, which turns a slow liability into a fast one. Dwindling reserves led the Treasury to extend bailout funds to insurers; conditions improved from late 2009.",
      th: "Thai life insurers met the same squeeze in the low-rate years after 2015: long-dated guaranteed endowments written when yields were high, funded by reinvesting at much lower Thai government bond yields. The OIC's response was the <b>risk-based capital</b> framework, which charges capital for exactly that mismatch." },
    { h: "Regulating life insurance: the states won",
      b: "The <b>McCarran-Ferguson Act of 1945</b> confirms the <b>primacy of state over federal regulation</b>. <b>State insurance commissions</b> license and examine, coordinated through the <b>National Association of Insurance Commissioners (NAIC)</b> and its common examination system. States also run <b>life insurance guarantee funds</b>, and the slides stress the contrast with the FDIC: these are <b>not permanent funds</b>. There is no pot of money sitting there. When a firm fails, the surviving insurers in that state are <b>required to contribute</b>.",
      th: "Thailand's counterparts are permanent standing funds rather than after-the-fact levies: the <b>Life Insurance Fund</b> and the <b>General Insurance Fund</b> (กองทุนประกันวินาศภัย), both funded by ongoing contributions from licensed insurers. The Jer-Jai-Jop failures showed the weakness that both designs share: a fund sized for one failure cannot absorb a whole sector's correlated loss." },
    { h: "Recent regulatory issues",
      b: "AIG created a <b>fear of systemic risk</b> in an industry that had always been treated as locally regulated and non-systemic. In <b>2009</b> came proposals for an <b>optional federal charter</b>, alongside complaints that state-by-state regulation was inconsistent and a barrier to innovation. The <b>Wall Street Reform and Consumer Protection Act of 2010</b> (Dodd-Frank) established the <b>Federal Insurance Office</b>: a monitoring and information body, not a replacement for state regulation." },
    { h: "Property and casualty: size and structure",
      b: "The slides count about <b>2,476</b> P&amp;C companies, a highly concentrated market in which the <b>top 10 firms write 47.6%</b> of premiums, with M&amp;A pushing concentration higher. The product lines are <b>fire insurance and allied lines</b>, <b>homeowners multiple-peril</b>, <b>commercial multiple-peril</b>, <b>automobile liability and physical damage</b>, and <b>other liability</b>.",
      th: "Thailand's non-life market is dominated by motor, largely because of compulsory third-party cover under the Protection for Motor Vehicle Accident Victims Act B.E. 2535, universally known as <b>Por Ror Bor</b> (พ.ร.บ.). It is the textbook's automobile liability line, made compulsory." },
    { h: "The P&C balance sheet",
      b: "The asset side resembles a life insurer's, with long-term securities, but with one crucial difference: P&amp;C insurers need <b>liquid assets</b>, because claims can arrive suddenly and in bulk. The major liabilities are <b>loss reserves</b> (estimated cost of claims incurred), <b>loss adjustment expenses</b> (the cost of investigating and settling them), and <b>unearned premiums</b> (premium collected for cover not yet provided)." },
    { h: "Loss risk: underwriting, severity and frequency",
      b: "<b>Underwriting risk</b> arises from unexpected increases in loss rates, unexpected increases in expenses, or unexpected decreases in investment yields. Property losses are more predictable than <b>liability</b> losses, where asbestos claims against workers' health are the slides' example. The deeper split is <b>severity versus frequency</b>: loss rates are predictable on <b>low-severity, high-frequency</b> lines such as fire, auto and homeowners, and unpredictable on <b>high-severity, low-frequency</b> lines such as earthquake, hurricane and financial guaranty. Worse, claims in those lines <b>may not be independent</b>. That uncertainty is why P&amp;C firms hold more short-term assets and larger capital and reserves than life insurers.",
      th: "The <b>2011 Thai floods</b> are the textbook case of a high-severity, low-frequency, non-independent loss: one monsoon season inundated seven industrial estates in Ayutthaya and Pathum Thani at once, so thousands of separate policies became a single event. Insured losses of roughly $15–16bn, against economic losses of about $45bn, landed largely on global reinsurers." },
    { h: "Terrorism, and the long tail",
      b: "The 2001 attacks forced the creation of a federal terrorism insurance programme: the <b>Terrorism Risk Insurance Act of 2002 (TRIA)</b> provides government backstop coverage and <b>caps losses</b> for insurance companies. Separately, <b>long-tail</b> risk arises where the peril occurs during the coverage period but the <b>claim is made many years later</b>: asbestos and the Dalkon Shield are the slides' examples, and firms have tried to <b>contain long-tail risks within subsidiaries</b>, as Halliburton did." },
    { h: "Inflation, social inflation and reinsurance",
      b: "Claims costs rise with <b>product inflation</b>, which may be systematic across the economy or specific to one line. <b>Social inflation</b> is different and harder: <b>unexpected changes in awards by juries</b>, which raise the cost of yesterday's policies after they were priced. Insurers pass part of the risk on through <b>reinsurance</b>, and roughly <b>75% of the reinsurance bought by US firms is written by non-US firms</b> such as Munich Re.",
      th: "Thai non-life insurers cede heavily to the same global reinsurers, which is why the 2011 flood bill was paid largely offshore, and why Thai flood cover repriced sharply when those reinsurers renewed their treaties." },
    { h: "Reading the ratios",
      b: "<b>Loss ratio</b> compares losses and loss adjustment expenses with premiums; <b>expense ratio</b> compares underwriting expenses with premiums. The slides' trend is that loss ratios have generally <b>increased</b> and expense ratios have generally <b>decreased</b>, helped by a shift toward selling through insurers' own brokers rather than independent ones. The <b>combined ratio</b> puts both together: <b>above 100, premiums are insufficient to cover losses and expenses</b>. The <b>operating ratio</b> is the combined ratio after dividends <b>minus the investment yield</b>, and it is the number that decides whether the year made money. Because investment income matters that much, P&amp;C managers must measure and manage credit risk and interest rate risk as carefully as underwriting risk." },
    { h: "Catastrophes and the limits of the market",
      b: "The slides list a run of catastrophes from 1985 to 2012: Hurricane Hugo, a San Francisco earthquake, the Oakland fires, Hurricane Andrew, then in 2004 Hurricanes Charley, Frances, Ivan and Jeanne in rapid succession, generating claims comparable to Andrew, then Hurricane Katrina in 2005. The 2001 attacks created an insurance crisis and, at the same time, heightened demand. A recurring worry is that government action <b>crowds out market solutions</b> such as <b>catastrophe bonds</b>, which transfer catastrophe risk to capital markets instead of to taxpayers.",
      th: "Thailand did exactly this after 2011: the <b>National Catastrophe Insurance Fund</b> was set up with government backing to provide flood cover when private capacity withdrew. It is the crowding-out question in practice, and it eventually wound down as private capacity returned." },
    { h: "P&C regulation and global reach",
      b: "P&amp;C insurers are <b>chartered and regulated by state commissions</b>, backed by <b>state guaranty funds</b>. The NAIC provides services to those commissions, including the <b>Insurance Regulatory Information System (IRIS)</b>, a ratio-based early-warning screen. Some lines face <b>rate regulation</b>, and the industry drew heavy criticism over its handling of Katrina-related claims. The industry is increasingly global: <b>2011</b> was a bad year worldwide, with Japan's earthquake and tsunami, earthquakes in New Zealand, <b>floods in Thailand</b> and severe US tornadoes." }
  ],
  formulas: [
    ["Loss ratio", "(Losses + loss adjustment expenses) ÷ premiums earned"],
    ["Expense ratio", "Underwriting expenses ÷ premiums written"],
    ["Dividend ratio", "Dividends to policyholders ÷ premiums earned"],
    ["Combined ratio", "Loss ratio + expense ratio"],
    ["Combined ratio after dividends", "Loss ratio + expense ratio + dividend ratio"],
    ["Underwriting profit margin", "100% − combined ratio after dividends"],
    ["Operating ratio", "Combined ratio after dividends − investment yield"],
    ["Overall profit margin", "100% − operating ratio"],
    ["Unearned premium (pro rata)", "Annual premium × months of cover remaining ÷ 12"]
  ],
  cards: [
    ["Adverse selection", "The people most likely to claim are the most eager to buy, so the insured pool is riskier than the general population. Managed by sorting applicants into priced risk pools."],
    ["Ordinary vs group vs industrial vs credit life", "Ordinary is the individual market (term, whole, endowment, variable, universal, variable universal). Group covers an employer's workforce. Industrial is the small door-collected policy. Credit life repays a loan on death."],
    ["Annuity", "The reverse of life insurance: the insurer takes a fund and pays it out over a life, instead of building a fund that pays out on death."],
    ["Morbidity insurance", "Accident and health cover: it insures sickness and injury, not death."],
    ["Net policy reserves", "The dominant liability of a life insurer: the amount set aside to meet expected future policyholder claims."],
    ["Why P&C holds more liquid assets", "Claims are lumpy and can all arrive at once. Life claims are slow and statistically smooth, so life insurers can stay long."],
    ["Loss reserves vs unearned premiums", "Loss reserves are money owed for claims already incurred. Unearned premium is money collected for cover not yet provided."],
    ["Severity vs frequency", "Low-severity, high-frequency lines (fire, auto, homeowners) are predictable. High-severity, low-frequency lines (earthquake, hurricane, financial guaranty) are not, and their claims may not be independent."],
    ["Long-tail risk", "The peril happens during the coverage period but the claim arrives years later. Asbestos and the Dalkon Shield are the classic examples."],
    ["Social inflation", "Unexpected increases in jury awards, which raise the cost of policies after they have been priced. Distinct from ordinary product inflation."],
    ["Combined ratio", "Loss ratio + expense ratio. Above 100 the underwriting business is losing money before any investment income."],
    ["Operating ratio", "Combined ratio after dividends minus the investment yield. This is the number that says whether the year was profitable overall."],
    ["McCarran-Ferguson Act 1945", "Confirms the primacy of state over federal insurance regulation. The NAIC coordinates the states; Dodd-Frank added only a Federal Insurance Office in 2010."],
    ["State guarantee funds vs the FDIC", "State insurance guarantee funds are not permanent funds. When an insurer fails, the surviving firms in that state are assessed to pay the claims."],
    ["Why AIG was rescued", "It was a major writer of credit default swaps. The potential impact on the counterparties that had bought that protection was used to justify the bailout."],
    ["TRIA 2002", "The federal terrorism insurance programme created after 9/11. The government provides backstop coverage and caps insurers' losses."],
    ["Catastrophe bonds", "A market transfer of catastrophe risk to capital market investors. Government schemes risk crowding them out."],
    ["Thailand's 2011 floods", "The chapter's global-issues slide lists them beside Japan's tsunami and the New Zealand earthquakes: roughly $15–16bn insured out of about $45bn of economic losses, paid largely by global reinsurers."]
  ],
  quiz: [
    { t: "mcq", q: "The chapter divides the industry into which two groups?",
      o: ["Mutual and stock", "Life, and property and casualty", "Domestic and foreign", "Retail and commercial"], a: 1,
      x: "Life versus property and casualty is the organising split of the whole chapter. Mutual versus stock is a question of ownership, which cuts across both." },
    { t: "mcq", q: "Why does the chapter say adverse selection is a problem for insurers?",
      o: ["Insurers cannot invest premiums", "Those who buy insurance tend to be higher risk than the general population", "Regulators set premiums too low", "Claims are always fraudulent"], a: 1,
      x: "Price from general-population tables and you underprice the people who actually buy. The remedy in the slides is grouping policyholders into risk pools." },
    { t: "num", q: "A non-life insurer earns ฿1,000m of premiums, pays ฿780m in losses and loss adjustment expenses, and incurs ฿250m of underwriting expenses. What is its combined ratio, in %?",
      a: 103, tol: 0.1, unit: "%",
      x: "Loss ratio = 780 ÷ 1,000 = 78%. Expense ratio = 250 ÷ 1,000 = 25%. Combined = 78 + 25 = <b>103%</b>. Above 100, so the underwriting business lost money before any investment income." },
    { t: "num", q: "The same insurer pays ฿20m of dividends to policyholders and earns an investment yield of 9%. What is its operating ratio, in %?",
      a: 96, tol: 0.1, unit: "%",
      x: "Dividend ratio = 20 ÷ 1,000 = 2%, so the combined ratio after dividends is 103 + 2 = 105%. Operating ratio = 105 − 9 = <b>96%</b>. Investment income turned an underwriting loss into an overall profit, which is exactly why the slides say P&amp;C managers must manage credit and interest rate risk." },
    { t: "mcq", q: "What did the McCarran-Ferguson Act of 1945 establish?",
      o: ["Federal chartering of insurers", "The primacy of state over federal regulation of insurance", "Deposit insurance for policyholders", "A national catastrophe fund"], a: 1,
      x: "It confirmed state primacy. The NAIC coordinates the states, and Dodd-Frank added only a Federal Insurance Office in 2010, not federal regulation." },
    { t: "mcq", q: "Asbestos claims filed decades after the policies were written are the standard example of:",
      o: ["Short-tail risk", "Long-tail risk", "Adverse selection", "Social inflation"], a: 1,
      x: "Long-tail risk: the peril occurs during the coverage period but the claim arrives many years later. The Dalkon Shield is the slides' other example, and Halliburton the example of containing such risk inside a subsidiary." },
    { t: "mcq", q: "According to the slides, why was AIG's bailout justified?",
      o: ["It was the largest life insurer in the world", "It was a major writer of credit default swaps, so its failure would have hit the companies that bought that protection", "It held most US bank deposits", "It ran the state guarantee funds"], a: 1,
      x: "The argument was about counterparties, not policyholders. AIG's CDS book, not its insurance underwriting, is what made it systemic." },
    { t: "num", q: "The US life industry had about 2,300 companies in 1988 and about 750 in 2020. By what percentage did the number of companies fall?",
      a: 67.39, tol: 0.1, unit: "%",
      x: "(2,300 − 750) ÷ 2,300 = <b>67.39%</b>. Over the same period aggregate assets rose from $1.1tn to $8.1tn: far fewer firms, each far larger." },
    { t: "mcq", q: "How do state insurance guarantee funds differ from the FDIC?",
      o: ["They are larger", "They are not permanent funds; surviving firms in the state are required to contribute after a failure", "They are funded by federal taxes", "They cover only commercial policies"], a: 1,
      x: "There is no standing pot of money. The assessment arrives after the failure, from the firms that are still solvent, which is precisely when they can least afford it." },
    { t: "mcq", q: "\"Social inflation\" in the chapter means:",
      o: ["General price inflation across the economy", "Unexpected changes in awards handed down by juries", "Rising reinsurance premiums", "Wage growth among claims adjusters"], a: 1,
      x: "It is a legal-environment cost, not a monetary one, and it raises the cost of policies that were priced years earlier." }
  ]
});
