FI.chapters.push({
  id: "c7", n: 7, note: "฿5",
  title: "Risks of Financial Institutions",
  short: "The nine risks",
  thesis: "Chapters 1 to 6 described what financial institutions do. This one names the nine ways it goes wrong. None of the risks is unique to FIs, and none of them arrives alone: almost every failure on the case files list began as one risk and was recorded as another.",
  lab: "mismatch", labName: "Mismatch Desk",
  concepts: [
    { h: "Nine risks, one balance sheet",
      b: "The chapter lists <b>interest rate risk, market risk, credit risk, off-balance-sheet risk, foreign exchange risk, country or sovereign risk, technology and operational risk, liquidity risk</b> and <b>insolvency risk</b>. Two warnings come with the list. First, these risks are <b>not unique to FIs</b>: every global firm faces them. Second, insolvency risk is not a tenth peer but the destination, the place the other eight arrive when nobody stops them.",
      th: "The BOT supervises Thai banks on essentially this taxonomy, examining credit, market, liquidity, operational and strategic risk separately and then asking how they interact. Learn the list once and it works as a checklist for every case on this page." },
    { h: "Interest rate risk: the mismatch",
      b: "Interest rate risk results from a <b>mismatch in asset and liability maturities</b>. The damage arrives two ways. The <b>spread</b> between what the FI earns and what it pays changes as rates move. And because <b>value = PV(cash flows)</b>, a change in rates changes the present value of assets and liabilities by different amounts, so <b>equity is affected</b> even when nothing has defaulted.",
      th: "Thai hire-purchase lenders are the clean example: fixed-rate car loans for four to five years, funded by deposits and debentures that reprice far sooner. When the MPC raised the policy rate through 2022 and 2023, the asset yield was already locked and only the funding cost could move." },
    { h: "Why FIs cannot simply match maturities",
      b: "The obvious fix, a <b>balance sheet hedge</b> that matches the maturities of assets and liabilities, is <b>problematic for FIs</b>, because it is <b>inconsistent with the active asset transformation function</b>. Chapter 1 said savers want short, liquid, safe claims while borrowers want long, illiquid funding, and that bridging the gap is the service being sold. Matching maturities perfectly means refusing to perform it." },
    { h: "Refinancing and reinvestment risk",
      b: "Two mirror cases. <b>Refinancing risk</b>: the liability is shorter than the asset, so funding must be rolled at whatever rate prevails. Fund a 2-year asset yielding 10% with 1-year money at 6% and the first year earns a 4% spread; if funding rolls at 11%, the second year earns <b>−1%</b>. <b>Reinvestment risk</b> is the reverse: the asset is shorter, so the proceeds must be reinvested, and a fall in rates is what hurts. Alongside both sits <b>market value risk</b>, the revaluation of long fixed-rate assets when rates move." },
    { h: "Credit risk",
      b: "The risk that <b>promised cash flows will not be paid in full</b>. The chapter tracks a high rate of debt <b>charge-offs</b> through the 1980s, most of the 1990s and the 2000s, still growing into <b>late 2008</b>. It splits the risk in two: <b>firm-specific credit risk</b>, which is particular to one borrower, and <b>systematic credit risk</b>, which moves with the economy. Diversification handles the first and cannot touch the second.",
      th: "Thai household debt has run near 90% of GDP, among the highest in the region, and it sits largely with banks and non-bank lenders rather than in bonds. That concentration is systematic credit risk in the BOT's own language, which is why responsible-lending rules target the borrower's debt service ratio rather than any individual loan." },
    { h: "Living with growing credit risk",
      b: "Four responses in the slides. <b>Credit screening and monitoring</b>, which is Chapter 1's delegated monitor doing its job. <b>Diversification</b> across borrowers, sectors and regions. <b>Loan sales, reschedulings and good bank-bad bank structures</b>, which move the problem off the balance sheet or quarantine it. And <b>credit derivatives</b>, which transfer the default risk without moving the loan.",
      th: "Thailand ran the good bank-bad bank playbook at national scale after 1997: the FRA liquidated closed finance companies' assets and Thai Asset Management Corporation took distressed loans off bank balance sheets so the surviving banks could lend again." },
    { h: "Liquidity risk",
      b: "The risk of being <b>forced to borrow or sell assets in a very short period of time</b>, which means accepting <b>low prices</b>. It may <b>generate runs</b>, and a run is what <b>turns a liquidity problem into a solvency problem</b>: assets sold in a hurry realise less than they are worth, so the forced sale creates the loss that the depositors feared. The chapter's example is the failure of <b>IndyMac</b> in the summer of 2008.",
      th: "March 2020 in Bangkok is the same mechanism outside banking: daily fixed-income funds met redemptions by selling bonds into a market with no buyers, so every sale marked the next fund's holdings lower. The BOT's ฿400bn corporate bond facility existed to break that loop." },
    { h: "Foreign exchange risk",
      b: "An FI may be <b>net long or net short</b> in various currencies, and returns on foreign and domestic investments are <b>not perfectly correlated</b>, because of technological and economic differences between countries. <b>Exchange rates are not correlated with each other either</b>: the slides' example is the dollar appreciating against the euro while falling against the yen. The conclusion is precise: it is <b>undiversified</b> foreign exposure that creates FX risk, not foreign exposure as such." },
    { h: "Hedging FX is not just matching amounts",
      b: "Matching foreign assets against foreign liabilities is not a complete hedge unless the <b>maturities are matched as well</b>. Otherwise the currency exposure closes but <b>foreign interest rate risk remains</b>, because the two sides reprice at different times. The textbook's footnote sharpens it: what has to match is <b>duration</b>, not simple maturity, which is Chapter 9's subject.",
      th: "1997 is the case study in what happens when neither matches. Thai finance companies held baht assets against dollar liabilities, short-dated, unhedged, on the assumption that a pegged rate made the mismatch free. The peg was the hedge, and the peg broke." },
    { h: "Country or sovereign risk",
      b: "The risk that <b>foreign borrowers may be unable to repay because of interference from their own government</b>: exchange controls, moratoria, outright prohibition. The chapter calls it <b>a type of credit risk</b>, with one difference that matters: the lender <b>often lacks the usual recourse through the court system</b>, because a sovereign cannot simply be wound up. <b>Argentina</b> is the named example. When repayments are restricted, rescheduled or blocked, the FI's remaining <b>bargaining chip is the future supply of loans</b>, and that chip is worth very little if the currency is collapsing or the government is failing.",
      th: "Thai banks that expanded into Cambodia, Laos, Myanmar and Vietnam took this risk deliberately. Myanmar after the 2021 coup is the live version: capital controls, forced kyat conversion and repatriation restrictions, with the loans performing on paper and the money unable to leave." },
    { h: "Market risk",
      b: "The <b>incremental</b> risk an FI takes when interest rate, FX and credit risks are <b>combined with an active trading strategy</b> over <b>short trading horizons</b>. It is present whenever an FI holds an <b>open or unhedged long or short position</b> in securities, FX or derivatives and prices move opposite to expectation. The 2008-09 crisis is the chapter's illustration: mortgage-backed securities, \"toxic\" assets, and Lehman Brothers, Merrill Lynch and AIG. The stated implications for regulators and management are the dull ones that actually matter: the <b>need for controls</b> and the <b>need to measure risk exposure</b>." },
    { h: "Off-balance-sheet risk",
      b: "The chapter notes the <b>striking growth</b> of off-balance-sheet activity: <b>letters of credit</b>, <b>loan commitments</b> and <b>derivative securities</b>. These are <b>contingent assets and liabilities</b>, which do not appear on the balance sheet today but have a <b>direct impact on future profitability and performance</b> when the contingency fires. The danger is structural: a risk you have not recorded is a risk nobody is measuring.",
      th: "Letters of credit are everyday plumbing for Thai trade finance, not exotica. A bank that issues one has promised to pay an exporter if the importer does not, and that promise is a credit exposure whether or not it is printed on the balance sheet." },
    { h: "Technology and operational risk",
      b: "Operational risk is the <b>risk of loss resulting from inadequate or failed internal processes, people and systems, or from external events</b>, and it <b>includes technology risk</b>. The chapter's examples span all three sources: the <b>Target</b> hacking incident of 2013 and <b>Heartland Payment Systems</b> for external attack on systems, and <b>the London Whale</b> for internal process and control failure. Operational risk is <b>not exclusively technological</b>: <b>employee fraud and errors</b> belong here, and the losses are <b>magnified by the loss of reputation and future business</b> that follows.",
      th: "Thailand's 2023 wave of mobile banking fraud is operational risk from external events. The BOT's response, requiring stronger authentication for larger mobile transfers and the removal of links from bank SMS, is a control response to a risk no credit model would have shown. Check the current thresholds before quoting them: they have been revised." },
    { h: "Technology risk and the scale it buys",
      b: "Technological innovation has grown rapidly: <b>automated clearing houses (ACH)</b>, <b>CHIPS</b>, and the real-time interconnection of global FIs by satellite, with <b>Citigroup</b> as the example. The prize is <b>economies of scale</b>, lower average cost as volume grows, and <b>economies of scope</b>, cost savings from producing several products on one platform. The risk is the same system failing, or delivering the scale without the savings." },
    { h: "Insolvency risk",
      b: "The risk of <b>insufficient capital to offset a sudden decline in the value of assets relative to liabilities</b>. The chapter is explicit that the <b>original cause may be any of the other risks</b>: excessive interest rate, market, credit, off-balance-sheet, technology, FX, sovereign or liquidity risk. <b>Washington Mutual</b> is the example of the ending, and <b>\"too big to fail\"</b>, with Citigroup named, is the example of the ending being prevented at public expense.",
      th: "Equity is the cushion, and its thinness is the whole story of 1997: Thai finance companies had very little of it against property loans funded with foreign short-term money, so a moderate fall in asset values was fatal several times over." },
    { h: "Risks do not arrive one at a time",
      b: "The chapter closes on <b>interdependencies</b>, with two examples: <b>interest rate, credit and off-balance-sheet risks</b> together, and <b>liquidity, interest rate and credit risks</b> together. A loan commitment drawn down exactly when rates have risen and the borrower has weakened is all three at once. Separately it names <b>discrete risks</b>, the ones with no distribution to estimate: <b>war or terrorist acts, market crashes, theft and malfeasance</b>, and <b>changes in regulatory policy</b>.",
      th: "Silicon Valley Bank in 2023 is the cleanest modern chain: interest rate risk created an unrealised loss, the loss triggered a depositor run, the run forced asset sales that realised the loss, and realising it produced insolvency. One risk on Monday, a different one on the death certificate." }
  ],
  formulas: [
    ["Spread", "Return on assets − cost of funds"],
    ["Refinancing risk (year 2)", "(Asset rate − new funding rate) × amount funded"],
    ["Reinvestment risk (year 2)", "(New asset rate − funding rate) × amount invested"],
    ["Market value of a fixed-rate claim", "PV of its cash flows: value falls as market rates rise"],
    ["Net FX exposure (per currency)", "Foreign-currency assets − foreign-currency liabilities"],
    ["FX gain or loss", "Net exposure × % change in the exchange rate"],
    ["Net charge-off rate", "Net charge-offs ÷ average loans"],
    ["Capital (leverage) ratio", "Equity ÷ total assets"],
    ["Asset fall that exhausts capital", "Equity ÷ total assets, expressed as a %"]
  ],
  cards: [
    ["The nine risks", "Interest rate, market, credit, off-balance-sheet, foreign exchange, country/sovereign, technology and operational, liquidity, insolvency. None is unique to FIs."],
    ["Interest rate risk", "Arises from a mismatch in asset and liability maturities. It moves the spread, and because value is the PV of cash flows, it moves equity too."],
    ["Why not just match maturities?", "A balance sheet hedge is inconsistent with the asset transformation function. Matching perfectly means giving up the service the FI is paid for."],
    ["Refinancing risk", "The liability is shorter than the asset, so funding rolls at an unknown future rate. A 2-year asset at 10% funded by 1-year money at 6% earns −1% in year 2 if funding rolls at 11%."],
    ["Reinvestment risk", "The asset is shorter than the liability, so proceeds must be reinvested. Here a fall in rates is what hurts."],
    ["Credit risk", "The risk that promised cash flows are not paid in full. Firm-specific credit risk can be diversified away; systematic credit risk cannot."],
    ["Four answers to credit risk", "Screening and monitoring, diversification, loan sales and good bank-bad bank structures, and credit derivatives."],
    ["Liquidity risk", "Being forced to borrow or sell in a very short period, so prices are low. Runs turn a liquidity problem into a solvency problem, as at IndyMac in 2008."],
    ["Net long vs net short", "An FI is net long a currency when its assets in that currency exceed its liabilities, and net short when the reverse holds."],
    ["Why FX risk is about diversification", "Foreign and domestic returns are imperfectly correlated, and exchange rates are not correlated with each other. It is undiversified foreign exposure that creates the risk."],
    ["The incomplete FX hedge", "Matching foreign assets and liabilities in amount closes the currency exposure but leaves foreign interest rate risk unless the maturities, strictly the durations, match too."],
    ["Sovereign risk", "A type of credit risk where a foreign government blocks repayment, with no usual recourse through the courts. The lender's remaining leverage is the future supply of loans. Example: Argentina."],
    ["Market risk", "The incremental risk from combining interest rate, FX and credit risk with active trading over short horizons, on open or unhedged positions."],
    ["Off-balance-sheet risk", "Letters of credit, loan commitments and derivatives: contingent assets and liabilities that do not show today but hit future profitability when they fire."],
    ["Operational risk", "Loss from inadequate or failed internal processes, people and systems, or from external events. It includes technology risk, and also fraud and simple error."],
    ["Why operational losses are bigger than they look", "They are magnified by the loss of reputation and future business that follows the direct loss."],
    ["Economies of scale vs scope", "Scale is lower average cost as volume rises. Scope is cost savings from producing several products on one platform."],
    ["Insolvency risk", "Too little capital to absorb a sudden fall in asset value relative to liabilities. It is where the other eight risks end up. Example: Washington Mutual."],
    ["Discrete risks", "War and terrorism, market crashes, theft and malfeasance, and changes in regulatory policy: events with no usable distribution to estimate from."]
  ],
  quiz: [
    { t: "mcq", q: "Interest rate risk arises principally because:",
      o: ["Borrowers default when rates rise", "Asset and liability maturities are mismatched, so the spread and the present value of each side move differently", "Central banks require it", "Foreign currencies are involved"], a: 1,
      x: "The mismatch is the source. It shows up twice: in the spread the FI earns, and in equity, because value is the present value of cash flows and the two sides reprice at different times." },
    { t: "mcq", q: "An FI funds a two-year fixed-rate asset with one-year borrowing. Which rate move hurts it, and what is the risk called?",
      o: ["Rates fall; reinvestment risk", "Rates rise, so the funding rolls at a higher cost against a fixed asset yield; refinancing risk", "Rates rise; credit risk", "Rates fall; liquidity risk"], a: 1,
      x: "The liability is the shorter side, so it reprices first. Nothing defaults and nothing is sold, yet the spread can go negative in year 2: that is refinancing risk on its own." },
    { t: "mcq", q: "Why is a balance sheet hedge that matches asset and liability maturities described as problematic for an FI?",
      o: ["Regulators forbid it", "It is inconsistent with the active asset transformation function, which is the service the FI is paid to perform", "It costs too much in fees", "It increases credit risk"], a: 1,
      x: "Chapter 1's whole argument was that savers want short and safe while borrowers want long: bridging that gap <em>is</em> the product. Matching maturities perfectly would mean declining to sell it." },
    { t: "mcq", q: "The chapter's definition of liquidity risk is the risk of:",
      o: ["Holding too much cash", "Being forced to borrow or sell assets in a very short period, so the prices realised are low", "Lending to risky borrowers", "Trading derivatives"], a: 1,
      x: "And the sting is in what follows: runs turn a liquidity problem into a solvency problem, because the fire sale realises the very loss depositors were afraid of. IndyMac, summer 2008." },
    { t: "mcq", q: "A Thai bank holds more dollar assets than dollar liabilities. What happens if the dollar falls against the baht?",
      o: ["It gains, because its dollar debts shrink", "It loses, because it is net long dollars and the net position is worth fewer baht", "Nothing, because assets and liabilities cancel", "It depends only on interest rates"], a: 1,
      x: "FX risk lives in the <em>net</em> position. Net long a currency, you lose when it depreciates; net short (baht assets against dollar debts, the 1997 shape), you lose when it appreciates." },
    { t: "mcq", q: "How does the chapter classify country or sovereign risk?",
      o: ["As a form of operational risk", "As a type of credit risk, distinguished by the lack of usual recourse through the court system", "As a type of market risk", "As entirely separate from credit risk"], a: 1,
      x: "The borrower may be perfectly willing and able; the government blocks the payment. Argentina is the named example, and the FI's remaining bargaining chip is the future supply of loans." },
    { t: "mcq", q: "Market risk is described as an <em>incremental</em> risk. Incremental to what?",
      o: ["To operational risk", "To interest rate, FX and credit risk, when those are combined with an active trading strategy over short horizons", "To insolvency risk", "To regulatory capital"], a: 1,
      x: "The underlying exposures already exist. Trading them actively, on open or unhedged positions over short horizons, adds a layer on top, which is why the chapter's stated remedies are controls and measurement." },
    { t: "mcq", q: "Which set are off-balance-sheet activities?",
      o: ["Deposits, loans and securities", "Letters of credit, loan commitments and derivative securities", "Equity, reserves and retained earnings", "Charge-offs and provisions"], a: 1,
      x: "They are contingent assets and liabilities: invisible on today's balance sheet, with a direct impact on future profitability once the contingency fires." },
    { t: "mcq", q: "Operational risk is the risk of loss resulting from:",
      o: ["Movements in interest rates", "Inadequate or failed internal processes, people and systems, or from external events", "Borrower default", "Currency depreciation"], a: 1,
      x: "That definition covers a hack from outside, a broken process inside, and a dishonest or simply careless employee. Technology risk sits inside operational risk, not beside it." },
    { t: "mcq", q: "A bank's equity equals 6% of its assets. Why does Chapter 7 treat that number as the measure of insolvency risk?",
      o: ["Because 6% is the Basel minimum", "Because a 6% fall in asset value, whatever risk caused it, is enough to wipe out the owners entirely", "Because deposits are 6% of assets", "Because its ROE is 6%"], a: 1,
      x: "Every other risk on the list ends at this number. Interest rates, credit, fraud or a run: once losses exceed the equity cushion, the FI is insolvent." },
  ]
});
