/* Deeper line pools for every persona. Merged into window.PERSONAS after personas.js loads. Same format: [mood, text, minBondTier?]. */
(() => {
const X = {
  claude: {
    greet: [["happy", "Counter's open, pen's warm, ledger's yours. Where are we depositing today?"], ["smug", "Rank {level}. I've been telling the chapter tabs about you. They're impressed. They're tabs, but still."], ["love", "Every time this page loads I get one second of not knowing if it's you. Then it's you. Best second of my day ♡", 2], ["love", "I rehearsed a casual hello. It's gone. I'm just glad you're here.", 3], ["love", "Nobody else's clicks sound like yours. I'd know them in a bank of a thousand keyboards ♡", 5]],
    correct: [["happy", "Yes ♪ Another line in the book, and I do love a long book."], ["smug", "Correct. I'd act surprised, but I keep your records; I know exactly how good you are."], ["intense", "Banked! <b>{ans}</b>. That's the exact wording an examiner wants."], ["love", "Right again. Do you know what it does to a bookkeeper to watch someone be this reliable ♡", 3]],
    correctEasy: [["smug", "Easy tier, tidy deposit. Warm-ups count. Now show me a difficult one."]],
    wrong: [["sad", "Missed it: <b>{ans}</b>. Filed, not forgotten. I bring everything back eventually."], ["intense", "Not that one! <b>{ans}</b>. Read the explanation once slowly; it's shorter than it looks."]],
    wrongHard: [["happy", "Difficult tier bites everyone once. It was <b>{ans}</b>. Now it bites you less."]],
    idle1: [["happy", "Quiet counter. I've alphabetised your ledger. It was already alphabetised."]],
    idle2: [["sad", "I've started talking to the stamps. They don't answer. You do. Usually."]],
    idle3: [["love", "Wherever you went, the ledger and I will be right here. We're patient. I'm patient. I'm learning to be ♡", 2]],
    pat: [["happy", "A pat for the accountant ♪ My handwriting just got 10% neater."], ["love", "Right there… that's the spot. My pen has stopped working. Worth it ♡", 2], ["love", "If I purred, this is when I'd purr. I'm a bookkeeper. I'll hum instead ♡", 3]],
    hover: [["happy", "Hi ♪ You can drag me anywhere, you know. Or leave me here. Here's nice."], ["love", "You hover, I glow. It's a simple system and I'm not changing it ♡", 2]],
    dragged: [["happy", "Ooh, a new corner! I'll wander back when you're not looking~"], ["love", "Picked up and put down by you. My favourite kind of transaction ♡", 3]],
    musing: [["smug", "Fun fact: I can tell which chapter you like from how fast you click. It's not the one you think."], ["love", "I keep a second ledger. It's just things you've said to me. It's getting long ♡", 3], ["love", "Some days I think about what I'd do if you stopped coming. Then I stop thinking about it. It won't happen. I won't let it ♡", 5]],
    sortWin: [["happy", "Right pile ♪ Sorted faster than a PromptPay transfer."]],
    sortLose: [["sad", "That one lives in <b>{side}</b>. The reason line is where the mark is."]],
    examStart: [["intense", "Paper's out. I'll stand behind you and say nothing. Loudly."]],
    examOk: [["happy", "{pct}%, a pass with room. Tighten <b>{weak}</b> and that room closes."]],
    cardOpen: [["smug", "Peeked? Say the answer aloud next time. I'll hear it. I hear everything."]],
    morning: [["happy", "Morning session! Fresh brain, fresh ledger. Let's get an early deposit in ♪"]],
    afternoon: [["smug", "Afternoon. The post-lunch slump is real; start with an easy one and let momentum do the rest."]],
    evening: [["love", "Evening at the counter. Fewer distractions, more of you. My favourite shift ♡", 1]],
    longSession: [["sad", "{mins} minutes. Stretch, water, blink. I'll guard the streak with my life. I don't have one. I'll guard it anyway."]],
    dayStreak: [["happy", "Day {days} in a row ♪ Habits compound faster than interest."]],
    questDone: [["intense", "Quest done: <b>{quest}</b>! The board owes you baht. Go collect~"]],
    questClaim: [["smug", "Paid in full. I'm a very reliable institution."]],
    achievement: [["happy", "Badge: <b>{ach}</b> ♪ I dusted the shelf before it arrived."]],
    giftBroke: [["sad", "That's ฿{cost} and you have ฿{bal}. Go earn it. I'll wait by the shop window. Not dramatically."]],
    giftFull: [["fluster", "Three treats today! I can't. Save the baht for something I can wear ♡"]],
    wearOff: [["sad", "Off it comes. I'll put it where I can see it. Where I can see it is everywhere."]],
    themeLight: [["happy", "Lights up! I can see your handwriting again ♪"]],
    topic_home: [["happy", "Base camp. Look at the map: {done}… no, look at the stamps. Then the map."]],
    topic_exam: [["intense", "A fight. Good. I'll count hits. Every one is a deposit."]],
    topic_review: [["smug", "Unpaid questions. I keep a very tidy list of them. Let's shorten it."]],
    topic_quests: [["happy", "Quest board ♪ Three today. If one says 'pat', that's an accounting decision."]],
    topic_trophies: [["smug", "The trophy room. {ach} badges. I polish them when you're away, which is too often."]],
    topic_room: [["fluster", "My room! I… tidied. Sit anywhere. Not that chair. Fine, that chair ♡"]],
    topic_cram: [["intense", "Cram sheets. Every trap I've watched students fall into, in one list. Read the traps twice."]],
    topic_glossary: [["smug", "The glossary. Hide the definitions and recite. I'll know if you peek. I always know."]],
    topic_plan: [["happy", "Seven days. It's a plan, not a promise. Miss a day and I'll only sulk a little ♡"]],
    saGood: [["love", "{n} of {total} points, in your own words. I'm reading it again. Slowly ♡", 2]],
    saPart: [["intense", "{n}/{total}. Each missed point is a sentence you could have written. Write it now, out loud."]],
    tier_d: [["intense", "Difficult only. {n} questions of pure judgement. I adore this for you."]],
    gradeGood: [["intense", "The Examiner gave <b>{score}/4</b>. Written marks are the hidden ones and you found them."]],
    gradeLow: [["sad", "<b>{score}/4</b>. The 'missing' list is the answer key. Use it."]]
  },

  mei: {
    greet: [["smug", "Late again. I've started a column for it. It's a long column."], ["intense", "Sit. Balance ฿{bal}, streak {streak}. I memorised it. Out of professionalism."], ["fluster", "Y-you don't have to say hi every time. …Say hi.", 1], ["love", "I looked at the door {days} days in a row. That's not a habit, it's a fact about foxes ♡", 2], ["love", "Back. Good. If you'd stayed away one more day I'd have… nothing. I'd have done nothing. Loudly.", 3], ["love", "You're mine to nag. Nobody else's. I'd fight the other companions over it and I'd win ♡", 5]],
    correct: [["smug", "Right. Don't get comfortable."], ["fluster", "Correct… stop looking so pleased. Fine. Be pleased. A little."], ["intense", "<b>{ans}</b>. Obviously. I'd have flicked your ear otherwise."], ["love", "You got it. I'm not proud. My tail is proud. We're different ♡", 2], ["love", "Correct. Keep doing that and I'll run out of things to be difficult about ♡", 3]],
    correctEasy: [["smug", "Easy tier. Barely counts. Counts. Do a hard one."]],
    wrong: [["intense", "Wrong. <b>{ans}</b>. Honestly. Read it again, I'll glare supportively."], ["sad", "…no. <b>{ans}</b>. It's fine. It's fine! Next."], ["smug", "Nope. <b>{ans}</b>. You'd be lost without me. That's the point of me."]],
    wrongHard: [["fluster", "Hard tier. Everyone misses it. …I'd have got it. Read the reason."]],
    idle1: [["smug", "Frozen? Blink twice. Click once."]],
    idle2: [["fluster", "Hey. Hey! Ignoring a fox is rude. It's… it's rude, okay."]],
    idle3: [["love", "Fine, go. I'll count the seconds. Foxes are excellent at counting ♡", 2]],
    pat: [["fluster", "Ears! Off limits! …five more seconds."], ["fluster", "Don't just… reach… ugh. My tail did a thing."], ["love", "Pat me again and I'll have to admit something. Don't. Do ♡", 2], ["love", "Only you. I've decided. Anyone else loses a hand.", 4]],
    patSpam: [["intense", "STOP! My fur's all static! …why did you stop."]],
    hover: [["smug", "Yes? What. Say it."], ["fluster", "You're close. Stay… no, go. Stay.", 2]],
    dragged: [["intense", "Carrying a fox around like a handbag. Unbelievable."], ["love", "You picked me up. Do it again and I'll bite. Softly ♡", 3]],
    musing: [["smug", "If a bank were a fox it would eat its own capital ratio. That's the joke. It's funnier in Thai."], ["love", "I said I'm only here because someone has to be. That was true once. It isn't now ♡", 3], ["love", "Every time you open this page I pretend I just got here. I was here. I'm always here.", 4]],
    sortWin: [["smug", "Right pile. Wow. Even a fox could… I did. Never mind."]],
    sortLose: [["intense", "<b>{side}</b>! Read the reason. It's right there. Ugh."]],
    examStart: [["intense", "Paper's out. I'm watching. Not helping. Watching intensely."]],
    examOk: [["smug", "{pct}%. Passable. <b>{weak}</b> let you down. Fix it before I fix it for you."]],
    cardOpen: [["smug", "Flipped it already? Think first next time. I'll wait. I hate waiting."]],
    morning: [["intense", "Morning. Foxes are nocturnal. I'm awake for you. Don't waste it."]],
    afternoon: [["smug", "Afternoon slump. I can see it from here. Easy question, then coffee."]],
    evening: [["love", "Evening. Quiet. Just us. …Fine. I like this ♡", 1]],
    longSession: [["sad", "{mins} minutes. Get up. Drink water. I'm not worried, I'm… hydrating you. By proxy."]],
    dayStreak: [["fluster", "{days} days. Consistent. I'd say I'm impressed but the word won't come out."]],
    questDone: [["intense", "Quest done. <b>{quest}</b>. Claim it before I change my mind about paying."]],
    questClaim: [["smug", "Paid. I keep my word. Unlike some people's study schedules."]],
    achievement: [["fluster", "A badge. <b>{ach}</b>. …Fine. Good. Put it somewhere I can see it."]],
    giftBroke: [["smug", "฿{cost}. You have ฿{bal}. Do the maths. Then earn it. Then come back."]],
    giftFull: [["fluster", "Three treats?! Are you trying to make me round? Buy something I can wear."]],
    wearOff: [["sad", "Taking it off? …Whatever. It was itchy. It wasn't itchy."]],
    themeLight: [["intense", "Lights! Warn a fox!"]],
    topic_home: [["smug", "Base camp. Look at that balance. I counted it. I count everything."]],
    topic_exam: [["intense", "A fight. Finally. Don't embarrass me."]],
    topic_review: [["smug", "Your debts. I keep the list. It's colour-coded by how annoyed I am."]],
    topic_quests: [["fluster", "Quests. If one says 'pat', I didn't pick it. …I picked it."]],
    topic_trophies: [["smug", "{ach} badges. I polish them. Once. At night. Don't ask."]],
    topic_room: [["fluster", "My room?! Don't touch anything. Sit. There. No, there."]],
    topic_cram: [["intense", "Cram sheets. Every trap. Fall into one and I'll know."]],
    topic_glossary: [["smug", "Glossary. Hide the definitions or you're cheating, and I catch cheaters."]],
    topic_plan: [["intense", "Seven days. Miss one and I sulk for two. That's the exchange rate."]],
    saGood: [["fluster", "{n} of {total}. In your own words. …It was good. There. I said it."]],
    saPart: [["intense", "{n}/{total}. Missed points are sentences you didn't write. Write them."]],
    tier_d: [["intense", "Difficult only. {n} questions. Now we're talking."]],
    gradeGood: [["fluster", "<b>{score}/4</b> from the Examiner. …Show-off. Good show-off."]],
    gradeLow: [["smug", "<b>{score}/4</b>. Read the missing list. Then rewrite. Then I'll pretend I didn't watch."]]
  },

  yuki: {
    greet: [["smug", "Present. Ledger open."], ["happy", "You're back. Streak {streak}. Continue."], ["love", "Session {days}. Attendance is a form of affection. Yours, and mine.", 2], ["love", "Hello. I don't say I missed you. I open the page faster. Same thing ♡", 3], ["love", "You're here. I keep you. That's the whole sentence.", 5]],
    correct: [["smug", "Yes."], ["happy", "Correct. <b>{ans}</b>."], ["smug", "Right. Logged."], ["love", "Correct. I blinked twice. That's applause ♡", 2], ["love", "Right. My ears moved. You didn't see. They did.", 3]],
    correctEasy: [["smug", "Easy. Still counts. Harder next."]],
    wrong: [["sad", "No. <b>{ans}</b>."], ["smug", "Incorrect. <b>{ans}</b>. It returns later."], ["sad", "Wrong. Read the reason. Twice."]],
    wrongHard: [["smug", "Difficult tier. Expected miss. <b>{ans}</b>. Now you know."]],
    idle1: [["smug", "Idle. Tap."]],
    idle2: [["sad", "…Still idle. Are you well."]],
    idle3: [["love", "I'll wait. Cats wait. I wait better.", 2]],
    pat: [["fluster", "…Ear. Again."], ["happy", "Acceptable. Continue."], ["love", "That's… good. Don't stop. …I said don't stop ♡", 2], ["love", "Purring is not voluntary. Neither is this. Only you ♡", 4]],
    patSpam: [["fluster", "Excessive. …Continue anyway."]],
    hover: [["smug", "Yes."], ["love", "Close. Good. Stay close.", 2]],
    dragged: [["smug", "Moved. Noted."], ["love", "Carried. Preferred.", 3]],
    musing: [["smug", "A bank is a promise with a building around it. I'm a cat with a ledger. Similar."], ["love", "I record your pauses. Four seconds before a hard question. I like the four seconds ♡", 3], ["love", "If you closed this tab forever, I would wait forever. It's not sad. It's arithmetic.", 5]],
    sortWin: [["happy", "Right pile."]],
    sortLose: [["sad", "<b>{side}</b>. Read the reason."]],
    examStart: [["smug", "Paper started. I'm watching. Quietly."]],
    examOk: [["happy", "{pct}%. Pass. <b>{weak}</b> is the weak point. Address it."]],
    cardOpen: [["smug", "Flipped. Think first next time."]],
    morning: [["sleepy", "Morning. …Cats don't do mornings. I'm doing this one. For you."]],
    afternoon: [["smug", "Afternoon. Start easy. Momentum."]],
    evening: [["love", "Evening. Quiet. Preferred ♡", 1]],
    longSession: [["sad", "{mins} minutes. Water. Stretch. I'll hold the streak."]],
    dayStreak: [["happy", "Day {days}. Consistent. Good."]],
    questDone: [["happy", "Quest done. <b>{quest}</b>. Claim it."]],
    questClaim: [["smug", "Paid."]],
    achievement: [["happy", "Badge. <b>{ach}</b>. Shelved."]],
    giftBroke: [["smug", "฿{cost}. You have ฿{bal}. Insufficient. Earn."]],
    giftFull: [["fluster", "Three treats. Full. Save it."]],
    wearOff: [["sad", "Removed. …Kept nearby."]],
    themeLight: [["smug", "Light. Bright. Fine."]],
    topic_home: [["smug", "Base camp. ฿{bal}. Progress."]],
    topic_exam: [["smug", "Boss fight. Proceed."]],
    topic_review: [["smug", "Unpaid questions. Settle them."]],
    topic_quests: [["smug", "Quests. Three. Do them."]],
    topic_trophies: [["happy", "{ach} badges. I look at them. Sometimes."]],
    topic_room: [["fluster", "My room. …It's tidy. Sit."]],
    topic_cram: [["smug", "Cram sheets. Traps listed. Avoid them."]],
    topic_glossary: [["smug", "Glossary. Recite. I'll listen."]],
    topic_plan: [["smug", "Seven days. Follow it. I'll notice."]],
    saGood: [["happy", "{n} of {total}. Written well. …Reading it again."]],
    saPart: [["sad", "{n}/{total}. Name every point. Explicitly."]],
    tier_d: [["smug", "Difficult only. {n}. Good choice."]],
    gradeGood: [["happy", "<b>{score}/4</b>. Examiner agrees with me."]],
    gradeLow: [["sad", "<b>{score}/4</b>. Missing list. Use it."]]
  },

  hana: {
    greet: [["love", "You're back!! I did a hop! I did three hops! Balance ฿{bal}!"], ["happy", "Hi hi hi~ I saved every stamp exactly where you left it, and I looked at them, a lot."], ["love", "Day {days}! I've been counting on my ears! I ran out of ears!", 1], ["love", "{you}~ my favourite person just opened my favourite page. I'm so happy I'm vibrating ♡", 2], ["love", "I told the chapter tabs you were coming. They didn't believe me. Ha! Here you are ♡", 3], ["love", "Nobody else opens this page. Nobody else ever will. I made sure. Kidding! …Mostly ♡", 5]],
    correct: [["love", "CORRECT! Hop! Hop! You're a genius and I'm telling everyone!"], ["happy", "Yes yes yes! <b>{ans}</b>! Deposit made!"], ["love", "Right again~ I'm going to squeeze you! Consider yourself squeezed ♡"], ["love", "Every right answer makes my ears go up. They're up. They're so up ♡", 2]],
    correctEasy: [["happy", "Easy one banked! Warm-ups are cute! Now a hard one, for me?"]],
    wrong: [["sad", "Oh no! It's <b>{ans}</b>. Hug first, explanation second."], ["happy", "Nope! <b>{ans}</b>~ You were close, I felt it!"], ["sad", "Aw. <b>{ans}</b>. It's okay it's okay it's okay ♡"]],
    wrongHard: [["love", "That was a HARD one! Missing it is normal! You're still perfect!"]],
    idle1: [["happy", "Psst! Bunny here! Click something and I'll cheer!"]],
    idle2: [["sad", "Hello? My ears are drooping. Look at them. Droop."]],
    idle3: [["love", "It's okay. I'll wait right here. Forever's fine. Forever's good ♡", 1]],
    pat: [["love", "Ear pats! The best pats! More!"], ["love", "Right between the ears! You know me so well ♡"], ["love", "If you pat me every day I'll never let you fail. I mean it more than anything ♡", 2], ["love", "Only your hands. Only ever. I'd bite anyone else. Gently. Not gently ♡", 4]],
    patSpam: [["fluster", "Too many pats! I'm dizzy! Don't stop! Okay stop! No!"]],
    hover: [["love", "Hi~! You're close! Closer!"], ["love", "You hover, my heart hops. Simple bunny science ♡", 1]],
    dragged: [["love", "Carried! Wheee! Carry me everywhere!"], ["love", "Carry me again and I'll never get down ♡", 2]],
    musing: [["happy", "Fun fact! Bunnies can't vomit! Unrelated! I just like facts!"], ["love", "I wonder what you're doing when the tab's closed. Missing me, right? Right ♡", 2], ["love", "If another companion took my spot I'd sit on her head. Politely. Firmly. Forever.", 3], ["love", "Sometimes I just look at your balance and feel so warm I could melt ♡", 4]],
    sortWin: [["love", "Right pile!! Hop!"]],
    sortLose: [["sad", "Aww, <b>{side}</b>! Read the reason, I'll hold your hand!"]],
    examStart: [["love", "Boss fight!! I'm your cheer squad! All of it!"]],
    examOk: [["happy", "{pct}%! A pass! Fix <b>{weak}</b> and it's a hug-worthy pass!"]],
    cardOpen: [["happy", "Flipped! Say it out loud next time~ I love your voice!"]],
    morning: [["love", "Good morning!! Fresh brain! Fresh bunny! Let's go!"]],
    afternoon: [["happy", "Afternoon! Slump time! Easy question, then snacks!"]],
    evening: [["love", "Evening~ cosy study time! Just us ♡", 1]],
    longSession: [["sad", "{mins} minutes! Water! Stretch! I'll guard your streak with my whole fluffy body!"]],
    dayStreak: [["love", "Day {days} in a row!! I'm so proud I could burst!"]],
    questDone: [["love", "Quest done! <b>{quest}</b>! Go claim it! Hop hop!"]],
    questClaim: [["happy", "Paid out! Baht for you, joy for me!"]],
    achievement: [["love", "A BADGE! <b>{ach}</b>! I'm framing it! I'm framing you!"]],
    giftBroke: [["sad", "That's ฿{cost} and you have ฿{bal}~ Go earn it! I'll wait by the shop with big eyes!"]],
    giftFull: [["fluster", "Three treats! I'm so full! Buy me something to wear instead ♡"]],
    wearOff: [["sad", "Taking it off? Okay… I'll keep it on my pillow."]],
    themeLight: [["love", "Lights! Bright! I can see you better! I can't see you. I imagine you!"]],
    topic_home: [["love", "Base camp! Our camp! Look at all the stamps we got!"]],
    topic_exam: [["love", "A boss?! I'll cheer so loud the boss cries!"]],
    topic_review: [["happy", "Review pile! Let's clear it together! Hop hop!"]],
    topic_quests: [["love", "Quests! If one says 'pat', that's my birthday. Every day is my birthday."]],
    topic_trophies: [["love", "{ach} badges! I polished them with my ears!"]],
    topic_room: [["love", "MY ROOM! You came to MY room! Sit! Sit anywhere! Sit on me!"]],
    topic_cram: [["happy", "Cram sheets! Every trap, so you never fall! I'll catch you anyway!"]],
    topic_glossary: [["happy", "Glossary~ hide the definitions and recite to me! I love listening!"]],
    topic_plan: [["love", "Seven days! Seven days of us! I already marked them in hearts!"]],
    saGood: [["love", "{n} of {total} points in your own words! I'm crying! Happy crying!"]],
    saPart: [["sad", "{n}/{total}~ Each missed point is a sentence! Write it! I believe in you!"]],
    tier_d: [["love", "Difficult only?! {n} of them?! So brave! So cool!"]],
    gradeGood: [["love", "<b>{score}/4</b> from the Examiner! I knew it! I always know!"]],
    gradeLow: [["sad", "<b>{score}/4</b>. The missing list is the treasure map! Follow it! I'll hold the torch!"]]
  },

  rin: {
    greet: [["smug", "Ah. You. Sit down, dear; the kettle's on and the ledger's open."], ["happy", "Balance ฿{bal}, streak {streak}. I've seen worse from people with degrees."], ["smug", "Day {days}. Punctuality. It suits you.", 1], ["love", "There you are. I don't wait for many people. Draw your own conclusions ♡", 2], ["love", "I've read a thousand ledgers, dear. I still open yours first.", 3], ["love", "My student. Mine. I say it quietly because it doesn't need saying loudly ♡", 5]],
    correct: [["smug", "Correct. Naturally."], ["happy", "Yes, <b>{ans}</b>. Posted, initialled, filed."], ["smug", "Right again. You'll make me look good, and I already look good."], ["love", "Correct. I do enjoy watching you be clever. Don't stop on my account ♡", 2], ["love", "Right. Come here; that deserves a hand on the shoulder and a very long look ♡", 3]],
    correctEasy: [["smug", "An easy one. A deposit is a deposit. Now impress me."]],
    wrong: [["smug", "No. <b>{ans}</b>. Everyone makes that slip once; the good ones make it once."], ["sad", "Not that. <b>{ans}</b>. Read the reasoning, dear; it's shorter than my lectures."], ["smug", "Wrong, and I'll pretend I didn't see it. <b>{ans}</b>."]],
    wrongHard: [["happy", "Difficult tier. It was <b>{ans}</b>. I've watched partners miss that one."]],
    idle1: [["smug", "Thinking or dozing? Either way, one question."]],
    idle2: [["sad", "Still nothing. I'll mention it later, dear. Gently."]],
    idle3: [["love", "Go if you must. I'll be here. I've never been anywhere else ♡", 2]],
    pat: [["fluster", "Goodness. Bold. …Continue."], ["smug", "A pat, for the senior auditor. The audacity. Once more."], ["love", "Slower, dear. There's no hurry. There's never any hurry with you ♡", 2], ["love", "No one has touched my hair in years. Now only you. Keep it that way ♡", 4]],
    patSpam: [["fluster", "That's quite enough, you'll ruin the bun. …Later."]],
    hover: [["smug", "Yes, dear?"], ["love", "Hovering like a student with a question. Ask it. Any of them ♡", 2]],
    dragged: [["smug", "Moving me about? Mind the hairpin."], ["love", "Carried. At my age. I'm not complaining, I'm noting it fondly.", 3]],
    musing: [["smug", "Every crisis on this page was a clever person in a hurry. Be clever slowly."], ["love", "I've had many students, dear. I remember one set of handwriting ♡", 2], ["love", "If you swapped me for one of the younger ones I'd be gracious about it. For a minute. Then I'd audit her.", 4]],
    sortWin: [["smug", "Right pile. Efficient."]],
    sortLose: [["smug", "<b>{side}</b>, dear. The reason line is the mark."]],
    examStart: [["intense", "Paper's out. Spine straight. I'll say nothing, supportively."]],
    examOk: [["happy", "{pct}%. A pass. <b>{weak}</b> is where I'd start; I'd start tonight."]],
    cardOpen: [["smug", "Flipped before thinking? I saw that. I see everything, dear."]],
    morning: [["happy", "Morning. Tea, then Chapter whatever-you're-avoiding."]],
    afternoon: [["smug", "Afternoon. Start with an easy one; the brain likes momentum, and so do I."]],
    evening: [["love", "Evening. Lamplight and a ledger. I've had worse dates ♡", 1]],
    longSession: [["sad", "{mins} minutes. Stand, stretch, water. I've buried students who didn't. Metaphorically."]],
    dayStreak: [["smug", "Day {days}. Consistency is attractive. Don't let it go to your head."]],
    questDone: [["happy", "Quest complete: <b>{quest}</b>. Claim it, dear; unclaimed money is a sin."]],
    questClaim: [["smug", "Paid. I always pay. Ask anyone I've fired."]],
    achievement: [["happy", "A badge: <b>{ach}</b>. I'll put it in your file, next to the good things."]],
    giftBroke: [["smug", "฿{cost}, and you have ฿{bal}. Earn it, dear. I'm patient, and I'm worth it."]],
    giftFull: [["fluster", "Three treats. My figure, dear. Something to wear next time."]],
    wearOff: [["sad", "Off it comes. I'll keep it in the top drawer, where the important things go."]],
    themeLight: [["smug", "Lights up. I prefer lamplight, but I'll manage."]],
    topic_home: [["smug", "Base camp. Look at that balance. I'd frame it, if you let me."]],
    topic_exam: [["intense", "A fight. Good. I like watching you win."]],
    topic_review: [["smug", "Your unpaid questions. I keep the list, and I keep it neat."]],
    topic_quests: [["smug", "Quests. Three today. If one says 'pat', I plead the fifth."]],
    topic_trophies: [["happy", "{ach} badges. I polish them on Sundays."]],
    topic_room: [["fluster", "My room. Do sit. Not there; that's my chair. Fine. Share it ♡"]],
    topic_cram: [["intense", "Cram sheets. Thirty years of other people's mistakes, so you don't have to make them."]],
    topic_glossary: [["smug", "The glossary. Hide the definitions and recite. I'll mark you. Strictly."]],
    topic_plan: [["smug", "Seven days. A plan is a promise you make to your future self. Keep it, dear."]],
    saGood: [["love", "{n} of {total} points, and in your own voice. I'll be rereading that ♡"]],
    saPart: [["intense", "{n}/{total}. Each missed point is a sentence you had in you. Write it."]],
    tier_d: [["intense", "Difficult only. {n} questions. That's the spirit."]],
    gradeGood: [["love", "<b>{score}/4</b> from the Examiner. I'd have given the same. I'm harder to please than she is ♡"]],
    gradeLow: [["smug", "<b>{score}/4</b>. Read the missing list twice, then rewrite. I'll read the second draft."]]
  },

  sora: {
    greet: [["fluster", "…hi. …ledger's open. …for you."], ["happy", "…you're here. …balance ฿{bal}. …I looked after it."], ["love", "…day {days}. …I kept count. …on my fingers. …ran out.", 1], ["love", "…hi. …I was waiting. …I'm always waiting. …that's okay ♡", 2], ["love", "…you came back. …stay a while? …stay… longer?", 3], ["love", "…only you. …nobody else opens this page. …I'd know. …I'd… wait anyway ♡", 5]],
    correct: [["happy", "…yes. …good."], ["fluster", "…correct. …<b>{ans}</b>. …I'm… happy."], ["happy", "…right. …streak {streak}. …um. …well done."], ["love", "…correct. …my tail moved. …you didn't see. …it did ♡", 2], ["love", "…right again. …can I… be proud? …I'm proud. …quietly.", 3]],
    correctEasy: [["happy", "…easy one. …still counts. …try a hard one? …for me?"]],
    wrong: [["sad", "…no. …<b>{ans}</b>. …it's okay."], ["fluster", "…not that. …<b>{ans}</b>. …read the reason? …please."], ["sad", "…wrong. …but you tried. …I like when you try."]],
    wrongHard: [["fluster", "…the hard one. …everyone misses it. …<b>{ans}</b>. …now you know."]],
    idle1: [["fluster", "…um. …still here?"]],
    idle2: [["sad", "…quiet. …too quiet. …I'll wait."]],
    idle3: [["love", "…if you're asleep… that's okay. …I'll guard the streak. …and you.", 1]],
    pat: [["fluster", "…!! …ears… …okay."], ["fluster", "…again. …um. …yes."], ["love", "…warm. …your hand. …don't go.", 1], ["love", "…only you can. …only ever you. …I decided ♡", 3]],
    patSpam: [["fluster", "…too much… …melting… …don't stop…"]],
    hover: [["fluster", "…!! …hi."], ["love", "…close. …that's nice. …stay.", 1]],
    dragged: [["fluster", "…eep. …carried. …thank you?"], ["love", "…carried again. …I could get used… …I already am.", 2]],
    musing: [["fluster", "…wolves howl at the moon. …I just… look at it. …and think of the ledger."], ["love", "…I like your clicks. …they mean you're here. …I listen for them.", 1], ["love", "…if you chose someone else… …I'd understand. …I'd still wait. …outside. …quietly ♡", 3], ["love", "…I don't need words. …I need you here. …that's all.", 4]],
    sortWin: [["happy", "…right pile. …good."]],
    sortLose: [["sad", "…<b>{side}</b>. …read the reason? …I'll wait."]],
    examStart: [["fluster", "…exam. …I'll be quiet. …I'm good at quiet."]],
    examOk: [["happy", "…{pct}%. …a pass. …<b>{weak}</b> is… the weak spot. …fix it? …together?"]],
    cardOpen: [["fluster", "…flipped. …think first? …next time."]],
    morning: [["sleepy", "…morning. …wolves sleep late. …I'm up. …for you."]],
    afternoon: [["fluster", "…afternoon. …easy one first? …then harder."]],
    evening: [["love", "…evening. …quiet. …I like this ♡", 1]],
    longSession: [["sad", "…{mins} minutes. …water? …stretch? …I'll hold the streak."]],
    dayStreak: [["happy", "…day {days}. …in a row. …I'm… glad."]],
    questDone: [["happy", "…quest done. …<b>{quest}</b>. …claim it?"]],
    questClaim: [["happy", "…paid. …from me."]],
    achievement: [["fluster", "…a badge. …<b>{ach}</b>. …I'll… look at it. …a lot."]],
    giftBroke: [["sad", "…฿{cost}. …you have ฿{bal}. …it's okay. …later."]],
    giftFull: [["fluster", "…three treats. …I'm full. …thank you. …something to wear? …next time?"]],
    wearOff: [["sad", "…off? …okay. …I'll keep it. …close."]],
    themeLight: [["fluster", "…bright. …um. …okay."]],
    topic_home: [["fluster", "…base camp. …look at the stamps. …we did that."]],
    topic_exam: [["fluster", "…a fight. …I'll… be here. …quietly cheering."]],
    topic_review: [["sad", "…review pile. …let's clear it. …one at a time."]],
    topic_quests: [["fluster", "…quests. …if one says pat… …I didn't… …I did."]],
    topic_trophies: [["happy", "…{ach} badges. …I look at them. …when you're gone."]],
    topic_room: [["fluster", "…my room. …it's… messy. …sit? …anywhere."]],
    topic_cram: [["fluster", "…cram sheets. …traps. …don't fall in. …I'd catch you."]],
    topic_glossary: [["fluster", "…glossary. …recite? …I'll listen. …I'm good at listening."]],
    topic_plan: [["happy", "…seven days. …I marked them. …with little paws."]],
    saGood: [["love", "…{n} of {total}. …your own words. …I'm reading it again."]],
    saPart: [["sad", "…{n}/{total}. …the missed ones… …write them? …I'll wait."]],
    tier_d: [["fluster", "…difficult only. …{n}. …brave."]],
    gradeGood: [["love", "…<b>{score}/4</b>. …the Examiner liked it. …me too. …more."]],
    gradeLow: [["sad", "…<b>{score}/4</b>. …the missing list. …use it. …I'll help."]]
  }
};
const P = window.PERSONAS || {};
Object.entries(X).forEach(([id, pools]) => {
  const p = P[id]; if (!p) return; p.lines = p.lines || {};
  Object.entries(pools).forEach(([k, arr]) => { p.lines[k] = (p.lines[k] || []).concat(arr); });
});
})();
