/* Append-only question bank extensions. Existing questions get tiers and sources; new ones are pushed to the end. */
FI.extend = FI.extend || function (id, tiers, srcs, more) {
  const c = FI.chapters.find(x => x.id === id) || FI.cases.find(x => x.id === id);
  const arr = c.quiz || c.qs;
  arr.forEach((q, i) => { q.tier = q.tier || tiers[i] || "m"; q.src = q.src || (srcs && srcs[i]) || "Slides"; });
  (more || []).forEach(q => arr.push(q));
};

FI.extend("c1", "eeemmemeem", ["Slides", "Thailand", "Thailand", "Thailand", "Slides", "Slides", "Thailand", "Thailand", "Thailand", "Slides"], [
  { t: "mcq", tier: "e", src: "Slides", q: "In the slides' picture of an economy <em>without</em> FIs, what flows between households and corporations?",
    o: ["Deposits and insurance policies", "Cash from households, in exchange for equity and debt claims", "Central bank reserves", "Loans from corporations to households"], a: 1,
    x: "Households hand over cash directly and receive primary securities (equity and debt). Deposits and policies only appear once an asset-transforming FI sits in the middle." },
  { t: "mcq", tier: "e", src: "Slides", q: "A ฿1,000 investment in a Thai equity fund gives a small saver a slice of a ฿5 billion diversified portfolio. Which service is this?",
    o: ["Maturity intermediation", "Credit allocation", "Denomination intermediation", "Payment services"], a: 2,
    x: "Denomination intermediation lets small savers own pieces of large, indivisible assets. Maturity intermediation is about <em>time</em> (short liabilities, long assets), not size." },
  { t: "mcq", tier: "e", src: "Slides", q: "A bank funds 20-year mortgages with savings deposits. This maturity intermediation mainly exposes the bank to:",
    o: ["Interest-rate risk", "Foreign-exchange risk", "Underwriting risk", "Operational risk"], a: 0,
    x: "If rates rise, the bank's deposit costs reprice quickly while its mortgage income is locked in. That is interest-rate risk from the maturity mismatch." },
  { t: "mcq", tier: "e", src: "Textbook 1", q: "Which FI activity is the clearest example of <em>intergenerational (time) intermediation</em>?",
    o: ["A broker executing a SET trade", "A pension or life insurance product turning working-age savings into retirement income", "A bank issuing a letter of guarantee", "The BOT setting the policy rate"], a: 1,
    x: "Time intermediation moves wealth across a lifetime, from working years to retirement. The other options are brokerage, an off-balance-sheet guarantee, and monetary policy." },
  { t: "mcq", tier: "e", src: "Slides", q: "What is the main purpose of guaranty funds such as the US Deposit Insurance Fund, SIPC, or Thailand's DPA?",
    o: ["To guarantee investment returns", "To fund government budgets", "To protect small savers when an FI fails and so reduce the incentive to run", "To set interest rate ceilings"], a: 2,
    x: "They protect claimholders up to a limit, which removes much of the reason for a panic run. None of them guarantee market returns." },
  { t: "mcq", tier: "e", src: "Slides", q: "The US Community Reinvestment Act (CRA) and Home Mortgage Disclosure Act (HMDA) are examples of:",
    o: ["Consumer protection regulation aimed at discrimination in lending", "Monetary policy tools", "Entry regulation", "Investor protection for securities markets"], a: 0,
    x: "Both target unfair lending practices such as redlining. Investor protection is the 1933/1934 Acts and the 1940 Act; entry regulation concerns charters." },
  { t: "mcq", tier: "e", src: "Slides", q: "If regulators make it very hard to obtain a new banking licence, what happens to the value of existing bank charters?",
    o: ["It falls, because competition rises", "It rises, because incumbents face less competition", "It is unaffected", "It becomes zero"], a: 1,
    x: "Entry impediments protect incumbents' profits, so the charter becomes more valuable. That is why entry regulation affects both profitability and net regulatory burden." },
  { t: "mcq", tier: "m", src: "Textbook 1", q: "The central bank cuts the reserve requirement on transaction deposits. What is the immediate effect on a bank?",
    o: ["Its deposits fall", "Part of its required reserves become excess reserves that it is free to lend", "It must raise equity", "Its loan book must shrink"], a: 1,
    x: "Reserve requirements are a monetary policy tool because they change how much of each deposit sits idle at the central bank. Lower requirement, more lendable reserves." },
  { t: "mcq", tier: "m", src: "Textbook 1", q: "Why can a cut in the reserve requirement expand total deposits by far more than the reserves it frees?",
    o: ["Because banks create the extra money by printing it", "Because each loan is redeposited and re-lent, so freed reserves support a multiple of deposits (reserves ÷ reserve ratio)", "Because the central bank buys bonds at the same time", "It cannot; deposits rise by exactly the freed amount"], a: 1,
    x: "This is the deposit multiplier. Counting only the first round of lending misses the repeated re-deposits that make fractional reserve banking expand money." },
  { t: "mcq", tier: "m", src: "Slides", q: "Which scenario best illustrates the <em>negative externality</em> argument for regulating FIs?",
    o: ["A bank charges higher fees than its competitors", "One Thai bank's failure triggers withdrawals at healthy banks and SMEs lose their credit lines", "A fund underperforms its benchmark", "A broker's app crashes for an hour"], a: 1,
    x: "An externality is a cost borne by people outside the transaction: contagion to sound banks and credit cut off for innocent borrowers. The other options hurt only the firm's own customers." },
  { t: "mcq", tier: "m", src: "Textbook 1", q: "The central bank buys ฿1 billion of government securities from commercial banks. What is the immediate effect?",
    o: ["Bank reserves fall by ฿1 billion and rates rise", "Bank reserves rise by ฿1 billion, credit availability expands and rates tend to fall", "Nothing changes until the reserve requirement changes", "The money supply falls by ฿1 billion"], a: 1,
    x: "The central bank pays by crediting the banks' reserve accounts, so reserves rise. That is an <b>expansionary</b> open market operation. A <em>sale</em> would do the reverse." },
  { t: "mcq", tier: "m", src: "Textbook 1", q: "Why do big tech platforms (e-wallets, super-apps and marketplaces operating in Thailand) pose a <em>digital disruption</em> risk to banks?",
    o: ["They are legally required to take deposits", "They hold rich customer data and payment relationships, so they can offer credit and payments without a full bank's net regulatory burden", "They always charge lower interest than the BOT policy rate", "They cannot be regulated by any Thai authority"], a: 1,
    x: "Their edge is data, distribution and lighter regulation, not deposits. Regulators respond by extending rules to activities (payments, lending) rather than only to licensed banks." },
  { t: "mcq", tier: "d", src: "Slides", q: "A commentator says: “Deposit insurance simply makes banks safer.” What is the best critique?",
    o: ["Deposit insurance has no effect on runs", "It reduces runs but creates moral hazard: insured depositors stop monitoring, so banks can take more risk unless premiums and capital rules push back", "It makes banks safer only in the United States", "It is always funded by taxpayers, so it cannot work"], a: 1,
    x: "Both halves matter. Insurance removes the run incentive, which is its purpose, but it also removes depositor discipline. That is why FDICIA added risk-based premiums and why capital rules exist." },
  { t: "mcq", tier: "d", src: "Slides", q: "The slides note a falling US share of assets at depository institutions and a rising share at investment companies. Which explanation do they offer?",
    o: ["Depository institutions pay higher deposit rates", "A heavier net regulatory burden on depositories pushes activity toward less-regulated FIs", "Investment companies are insured by the FDIC", "Households stopped needing liquidity"], a: 1,
    x: "When the costs of regulation outweigh its benefits for one group of FIs, business migrates to substitutes with a lighter burden. The same logic explains shadow banking." },
  { t: "mcq", tier: "d", src: "Textbook 1", q: "JPMorgan's 2012 “London Whale” loss (about $6.2bn) came from its Chief Investment Office, a unit meant to hedge. What is the core ERM lesson?",
    o: ["Hedging units should never trade derivatives", "Risk must be measured and limited firm-wide, including units labelled “hedging”, backed by a culture that challenges big positions", "Losses under $10bn do not matter for a large bank", "ERM only applies to credit risk"], a: 1,
    x: "The positions grew outside effective firm-wide limits, and warnings were not escalated. ERM treats risks as one interrelated portfolio and depends on governance and culture, not just models." },
  { t: "mcq", tier: "d", src: "Slides", q: "Why does the delegated-monitor rationale for banks weaken under originate-to-distribute?",
    o: ["Banks lose access to borrower information", "Once the loan is sold, the bank no longer bears the default risk, so its incentive to screen and monitor falls, while dispersed buyers free-ride again", "Securitized loans cannot default", "Regulators ban monitoring of sold loans"], a: 1,
    x: "Delegated monitoring works because the monitor holds the risk. Selling the loan hands the risk to many small holders, recreating the free-rider problem that FIs were meant to solve." },
  { t: "mcq", tier: "d", src: "Textbook 1", q: "The reserve requirement is raised and a bank cannot obtain more reserves. What must happen to its transaction deposits?",
    o: ["Nothing; the bank simply holds less capital", "They must contract, and by more than the reserve shortfall, because the multiplier works in reverse", "They rise to cover the requirement", "They convert into equity"], a: 1,
    x: "The same reserves now support fewer deposits. The bank must call in loans and let deposits run off, which is why raising requirements is a blunt, powerful contraction tool." },
  { t: "mcq", tier: "d", src: "Thailand", q: "Thailand directs subsidised farm credit through BAAC. Which statement best captures the trade-off from the credit-allocation perspective?",
    o: ["It has no costs because BAAC is state-owned", "It supports a socially important sector, but below-market lending can create losses borne by taxpayers and weaker credit discipline", "It reduces the net regulatory burden on commercial banks to zero", "It is a form of monetary policy, not credit allocation"], a: 1,
    x: "Credit allocation deliberately overrides pure market pricing. The benefit is access for priority sectors; the cost is the subsidy, possible losses, and weaker incentives to screen borrowers." }
]);
