const RIVERSIDE = "Siam Riverside Bank (illustrative, ฿ million): interest income 18,000; non-interest income 3,000; interest expense 9,500; provision for loan losses 1,800; non-interest expense 4,200; taxes 1,100; total assets 250,000; total equity 25,000.";

FI.extend("c2", "eemeemmmeemd", ["Slides", "Slides", "Slides", "Thailand", "Slides", "Slides", "Thailand", "Thailand", "Slides", "Thailand", "Slides", "Slides"], [
  { t: "mcq", tier: "e", src: "Slides", q: "Which Act separated commercial banking from investment banking and created the FDIC?",
    o: ["McFadden Act, 1927", "Glass-Steagall Act, 1933", "Bank Holding Company Act, 1956", "DIDMCA, 1980"], a: 1,
    x: "Glass-Steagall (1933). McFadden (1927) limited branching; the BHC Act (1956) governed holding companies; DIDMCA (1980) was deregulation." },
  { t: "mcq", tier: "e", src: "Slides", q: "What did the Riegle-Neal Act of 1994 permit?",
    o: ["Banks to underwrite insurance", "Interstate bank acquisitions and branching", "Interest on demand deposits", "Credit unions to convert to banks"], a: 1,
    x: "Riegle-Neal allowed BHCs to acquire banks in other states and convert them into branches of one interstate bank." },
  { t: "mcq", tier: "e", src: "Slides", q: "Which US banks are automatically members of the Federal Reserve System?",
    o: ["State-chartered banks", "Credit unions", "National banks", "Savings associations"], a: 2,
    x: "National banks (chartered by the OCC) are automatically Fed members. State-chartered banks may choose to join." },
  { t: "mcq", tier: "e", src: "Slides", q: "Which feature defines a credit union?",
    o: ["A shareholder-owned bank listed on an exchange", "A nonprofit owned by member-depositors with a common bond, exempt from taxes and the CRA", "A bank that only makes business loans", "An FI that takes no deposits"], a: 1,
    x: "Member ownership, the common bond, and tax and CRA exemptions are the defining features. Small banks call the tax exemption an unfair advantage." },
  { t: "mcq", tier: "e", src: "Slides", q: "US commercial banks fell from 14,416 in 1985 to 4,231 in 2021. What is the main reason given in the slides?",
    o: ["Mass bank failures only", "Mergers and acquisitions after branching restrictions were relaxed", "Banks converting to credit unions", "A legal cap on the number of banks"], a: 1,
    x: "Most of the decline came through M&A, which had been blocked before the 1980s and 1990s. Failures played a smaller part." },
  { t: "mcq", tier: "e", src: "Slides", q: "A NOW (Negotiable Order of Withdrawal) account is best described as:",
    o: ["A certificate of deposit that cannot be withdrawn early", "An interest-bearing checking (transaction) account", "A money market mutual fund", "A loan commitment"], a: 1,
    x: "NOW accounts let savers write cheques and earn interest. DIDMCA authorised them nationwide in 1980." },
  { t: "num", tier: "e", src: "Slides", q: "A bank has total assets of ฿2,400bn and total equity of ฿200bn. What is its equity multiplier?",
    a: 12, tol: 0.01, unit: "×",
    x: "EM = total assets ÷ total equity = 2,400 ÷ 200 = <b>12×</b>. Equity funds 1 ÷ 12 = 8.3% of assets. Answering 0.083 inverts the ratio." },
  { t: "num", tier: "m", src: "Textbook 2", q: RIVERSIDE + " What is net income, in ฿ million?",
    a: 4400, tol: 0.5, unit: "฿m",
    x: "18,000 + 3,000 − 9,500 − 1,800 − 4,200 − 1,100 = <b>฿4,400m</b>. Answering ฿5,500m forgets taxes; ฿6,200m forgets the provision as well." },
  { t: "num", tier: "m", src: "Textbook 2", q: RIVERSIDE + " What is its ROA, in %?",
    a: 1.76, tol: 0.01, unit: "%",
    x: "NI = ฿4,400m, and ROA = 4,400 ÷ 250,000 = <b>1.76%</b>. Dividing by equity instead gives the ROE of 17.6%." },
  { t: "num", tier: "m", src: "Textbook 2", q: RIVERSIDE + " What is its asset utilisation, in %?",
    a: 8.4, tol: 0.01, unit: "%",
    x: "Total operating income = 18,000 + 3,000 = ฿21,000m, and AU = 21,000 ÷ 250,000 = <b>8.4%</b>. Using only interest income gives 7.2%, which misses the fee business." },
  { t: "num", tier: "d", src: "Textbook 2", q: RIVERSIDE + " Credit quality worsens and the provision for loan losses doubles. Assuming taxes stay at ฿1,100m, what is the new ROE, in %?",
    a: 10.4, tol: 0.01, unit: "%",
    x: "Provision rises by ฿1,800m, so NI = 4,400 − 1,800 = ฿2,600m. ROE = 2,600 ÷ 25,000 = <b>10.4%</b>, down from 17.6%. Leverage (EM = 10) turns a 0.72-point drop in ROA into a 7.2-point drop in ROE." },
  { t: "mcq", tier: "m", src: "Slides", q: "Which set of outcomes belongs to FIRREA (1989)?",
    o: ["Introduced prompt corrective action and risk-based premiums", "Replaced FSLIC with FDIC-SAIF, created the Office of Thrift Supervision and the Resolution Trust Corporation", "Allowed interstate branching", "Created the Consumer Financial Protection Bureau"], a: 1,
    x: "FIRREA cleaned up the S&L crisis: FSLIC abolished, OTS and RTC created. PCA is FDICIA (1991), interstate branching is Riegle-Neal (1994), and the CFPB is Dodd-Frank (2010)." },
  { t: "mcq", tier: "m", src: "Slides", q: "A bank has extended a large unused loan commitment to a Thai conglomerate. Why is this off-balance-sheet item risky?",
    o: ["It earns no fees", "The client can draw it exactly when its own credit or market liquidity worsens, turning it into an on-balance-sheet loan at a bad moment", "It must be reported as equity", "It is a derivative with unlimited losses"], a: 1,
    x: "Commitments are contingent: drawdowns tend to arrive in stress, bringing both credit and liquidity risk. The fee compensates the bank for that option." },
  { t: "mcq", tier: "m", src: "Textbook 2", q: "How does the Volcker rule (Dodd-Frank) relate to the Financial Services Modernization Act of 1999?",
    o: ["It extends FSMA by allowing banks to own hedge funds freely", "It partially reverses FSMA's trend by banning bank holding companies' proprietary trading and limiting their hedge fund and private equity investments", "It repeals deposit insurance", "They are unrelated"], a: 1,
    x: "FSMA knocked down the walls between banking, insurance and securities. After the crisis, the Volcker rule rebuilt part of the wall around risky trading." },
  { t: "mcq", tier: "d", src: "Slides", q: "Over two years a bank's ROE rose from 12% to 15% while its ROA fell. What must have happened, and how should an analyst read it?",
    o: ["Profit margin rose; a clear improvement", "The equity multiplier rose sharply; the higher ROE is leverage-driven and the bank is riskier", "Asset utilisation rose; a clear improvement", "Nothing can be inferred"], a: 1,
    x: "ROE = ROA × EM. If ROA fell and ROE rose, EM must have risen by more than enough to offset it. More debt per baht of equity means a thinner loss-absorbing cushion." },
  { t: "mcq", tier: "d", src: "Slides", q: "In the late 1970s, market rates rose far above Regulation Q deposit ceilings. What happened to US thrifts?",
    o: ["Deposits flowed in because thrifts were insured", "Savers moved to money market funds (disintermediation), while thrifts were stuck with long fixed-rate mortgages, squeezing them from both sides", "Thrifts earned record profits", "Regulation Q was tightened further"], a: 1,
    x: "Ceilings stopped thrifts matching market rates, so funding left. Their assets were long-term fixed-rate mortgages earning old low rates. Later, moral hazard and forbearance turned losses into the S&L crisis." },
  { t: "mcq", tier: "d", src: "Thailand", q: "A Thai savings cooperative pays 4% on deposits while large banks pay about 1.5%. Why might it be riskier for members than the rate suggests?",
    o: ["Cooperatives always fail", "It sits outside BOT supervision and DPA protection, the higher rate must be funded by riskier lending or investments, and a common bond concentrates exposure", "Its deposits are guaranteed up to ฿2 million", "Higher rates always mean lower risk"], a: 1,
    x: "Yield comes from somewhere. No deposit insurance, lighter supervision and concentrated membership (one employer or profession) add up to more risk, a lesson from past cooperative scandals." },
  { t: "mcq", tier: "d", src: "Slides", q: "FDICIA (1991) limited “too big to fail” bailouts, yet in 2008–09 US authorities injected TARP capital into the largest banks. Which explanation is most consistent with the course?",
    o: ["FDICIA was repealed in 2007", "Regulators judged that the negative externalities of disorderly failure exceeded the cost of rescue, even though rescues worsen moral hazard", "TARP only applied to small community banks", "Banks repaid depositors directly, so no rescue occurred"], a: 1,
    x: "Rules limiting bailouts usually carry systemic-risk exceptions. The externality argument from Chapter 1 won in the crisis, and Dodd-Frank then tried to make future failures orderly." }
]);
