FI.extend("c3", "eeemdmemem", ["Slides", "Slides", "Slides", "Thailand", "Thailand", "Textbook 3", "Thailand", "Slides", "Thailand", "Slides"], [
  { t: "mcq", tier: "e", src: "Slides", q: "The largest 20 US finance companies hold about 65% of the industry's assets. The industry is therefore best described as:",
    o: ["Highly fragmented", "Highly concentrated", "Perfectly competitive", "Dominated by credit unions"], a: 1,
    x: "Twenty firms holding two-thirds of assets is high concentration. Mutual funds, by contrast, are described as having low concentration." },
  { t: "mcq", tier: "e", src: "Slides", q: "A sales finance institution specialises in:",
    o: ["Loans to the customers of a particular retailer or manufacturer", "Equipment leasing and factoring", "Taking time deposits", "Underwriting corporate bonds"], a: 0,
    x: "Sales finance supports a seller's customers, as Ford Motor Credit or Sears Roebuck Acceptance did. Leasing and factoring are business credit." },
  { t: "mcq", tier: "e", src: "Slides", q: "Which activities define a business credit institution?",
    o: ["Payday loans and credit cards", "Equipment leasing and factoring", "Mortgage-backed security underwriting", "Money market funds"], a: 1,
    x: "Business credit institutions (CIT Group, for example) provide business loans, equipment leases and factoring." },
  { t: "mcq", tier: "e", src: "Slides", q: "According to the slides, which category is the largest share of finance company loans?",
    o: ["Payday loans", "Business loans (about 30%)", "Home equity loans", "Student loans"], a: 1,
    x: "Business loans are the largest single portion. Consumer loans are dominated by motor vehicle loans and leases." },
  { t: "mcq", tier: "e", src: "Slides", q: "Which law applies to US banks but <em>not</em> to finance companies?",
    o: ["State usury ceilings", "The Community Reinvestment Act of 1977", "Dodd-Frank", "Securities Act of 1933"], a: 1,
    x: "Finance companies are not depository institutions, so the CRA does not apply. They remain subject to state usury ceilings and, after 2010, Dodd-Frank oversight." },
  { t: "num", tier: "e", src: "Thailand", q: "A motorcycle priced at ฿60,000 is bought on hire purchase at a flat rate of 12% a year for 24 months. What is the total interest charged, in ฿?",
    a: 14400, tol: 1, unit: "฿",
    x: "Flat interest = principal × rate × years = 60,000 × 0.12 × 2 = <b>฿14,400</b>. Answering ฿7,200 uses one year instead of two." },
  { t: "num", tier: "m", src: "Thailand", q: "Same motorcycle: ฿60,000 at a 12% flat rate over 24 months. What is the monthly installment, in ฿?",
    a: 3100, tol: 0.5, unit: "฿",
    x: "Total repaid = 60,000 + 14,400 = ฿74,400, and ÷ 24 = <b>฿3,100</b>. The effective rate is about 21.6% a year, still under the 23% motorcycle cap." },
  { t: "mcq", tier: "m", src: "Slides", q: "Why did US home equity lending grow rapidly after the Tax Reform Act of 1986?",
    o: ["It banned credit cards", "Interest on home equity loans stayed tax-deductible while deductions for other consumer interest were phased out", "It required banks to stop mortgage lending", "It capped home prices"], a: 1,
    x: "Borrowers switched from car and card debt to home-secured debt to keep the deduction. That is how home equity became a major finance company asset, and a source of losses in 2007–08." },
  { t: "mcq", tier: "m", src: "Slides", q: "Finance companies have historically charged higher consumer loan rates than commercial banks. The main reason is:",
    o: ["They pay interest on deposits", "They lend to riskier borrowers, including subprime customers banks avoid", "They are required to by the Fed", "They have no operating costs"], a: 1,
    x: "Higher rates compensate for higher default risk, and funding costs are also higher without deposits." },
  { t: "mcq", tier: "m", src: "Slides", q: "How does liquidity risk management at a finance company differ from a commercial bank's?",
    o: ["It is identical", "It depends on rolling over commercial paper and market debt, often backed by bank credit lines, rather than a deposit base and central bank access", "Finance companies have no liquidity risk", "They hold mostly cash"], a: 1,
    x: "No deposits and no discount window means refinancing risk. When CP markets froze in 2008, finance companies were hit immediately." },
  { t: "num", tier: "m", src: "Thailand", q: "A Thai credit card charges 16% a year, compounded monthly on a revolving balance. What is the effective annual rate, in %?",
    a: 17.23, tol: 0.02, unit: "%",
    x: "(1 + 0.16/12)¹² − 1 = 1.013333¹² − 1 = <b>17.23%</b>. The 16% is a nominal annual rate; carrying a balance all year costs more." },
  { t: "mcq", tier: "d", src: "Slides", q: "A regulator caps payday-style loan rates at 36% a year. Using the course's logic, which unintended consequence is most likely?",
    o: ["Every borrower gets cheaper credit", "Lenders stop serving the riskiest borrowers, who may turn to informal lenders (like Thai “helmet loan” sharks) or to lenders that evade the cap through partnerships elsewhere", "Banks start offering payday loans at 36%", "Demand for short-term credit disappears"], a: 1,
    x: "A price ceiling below the cost of lending to high-risk borrowers rations credit. The slides show evasion via national bank partnerships; in Thailand the informal market absorbs excluded borrowers." },
  { t: "mcq", tier: "d", src: "Slides", q: "Why was the Fed's 2008 approval of GMAC as a bank holding company controversial?",
    o: ["GMAC had no auto loans", "It extended the federal safety net to a lender tied to an industrial firm, blurring the separation of banking and commerce and increasing moral hazard", "It forced GM into liquidation", "It made GMAC exempt from all regulation"], a: 1,
    x: "Bailout access for a car company's finance arm raised the question of who belongs inside the safety net. Hence the condition that GM cut its stake below 10%." },
  { t: "num", tier: "d", src: "Slides", q: "A payday loan charges 15% per two-week period. If the borrower rolls it over for a full year (26 periods) and the fees compound, what is the effective annual rate, in %?",
    a: 3685.7, tol: 5, unit: "%",
    x: "(1.15)²⁶ − 1 = 37.857 − 1 = <b>3,685.7%</b>. The slides' 390% is the simple APR (15% × 26). Compounding makes rollovers catastrophically expensive." },
  { t: "mcq", tier: "d", src: "Slides", q: "Captive finance companies can often offer 0% promotional auto loans that stand-alone lenders cannot. What makes this possible?",
    o: ["Captives are exempt from usury laws", "The parent manufacturer effectively subsidises the loan out of its vehicle margin, and parent guarantees or letters of credit lower the captive's funding cost", "Captives take deposits", "Zero-percent loans have no credit risk"], a: 1,
    x: "The goal is selling cars, not only earning interest. After 9/11, captives used 0% financing to push sales, and parent support lowers their borrowing costs." },
  { t: "num", tier: "d", src: "Slides", q: "A finance company has ฿80bn of assets and ฿11.44bn of equity (14.3% capital-to-assets). If it operated at the banks' 11.5% ratio with the same equity, how much more could it lend, in ฿bn?",
    a: 19.48, tol: 0.05, unit: "฿bn",
    x: "Assets supported = 11.44 ÷ 0.115 = ฿99.48bn. Extra = 99.48 − 80 = <b>฿19.48bn</b>. Market lenders demand the thicker cushion precisely because there is no safety net." }
]);
