FI.extend("c3", "eeemdmemem", ["Slides", "Slides", "Slides", "Thailand", "Thailand", "Textbook 3", "Thailand", "Slides", "Thailand", "Slides"], [
  { t: "mcq", tier: "e", src: "Slides", q: "The largest 20 US finance companies hold about 65% of the industry's assets. The industry is therefore best described as:",
    o: ["Highly fragmented", "Highly concentrated", "Perfectly competitive", "Dominated by credit unions"], a: 1,
    x: "Twenty firms holding two-thirds of assets is high concentration. Mutual funds, by contrast, are described as having low concentration." },
  { t: "mcq", tier: "e", src: "Slides", q: "A sales finance institution specialises in:",
    o: ["Loans to the customers of a particular retailer or manufacturer", "Equipment leasing and factoring", "Taking time deposits", "Underwriting corporate bonds"], a: 0,
    x: "Sales finance supports a seller's customers, as Ford Motor Credit or Sears Roebuck Acceptance did. Leasing and factoring are business credit." },
  { t: "mcq", tier: "e", src: "Slides", q: "Which activities define a business credit institution?",
    o: ["Payday loans and credit cards", "Equipment leasing and factoring", "Mortgage-backed security underwriting", "Money market funds"], a: 1,
    x: "Business credit institutions (CIT Group, for example) provide business loans, equipment leases and factoring." },
  { t: "mcq", tier: "e", src: "Slides", q: "According to the slides, which category is the largest share of finance company loans?",
    o: ["Payday loans", "Business loans (about 30%)", "Home equity loans", "Student loans"], a: 1,
    x: "Business loans are the largest single portion. Consumer loans are dominated by motor vehicle loans and leases." },
  { t: "mcq", tier: "e", src: "Slides", q: "Which law applies to US banks but <em>not</em> to finance companies?",
    o: ["State usury ceilings", "The Community Reinvestment Act of 1977", "Dodd-Frank", "Securities Act of 1933"], a: 1,
    x: "Finance companies are not depository institutions, so the CRA does not apply. They remain subject to state usury ceilings and, after 2010, Dodd-Frank oversight." },
  { t: "mcq", tier: "e", src: "Thailand", q: "On a hire-purchase contract quoted at a flat rate, how is total interest computed?",
    o: ["On the declining balance each month", "Principal × flat rate × number of years, regardless of the repayments already made", "On the first year only", "As a single one-off fee"], a: 1,
    x: "Flat interest ignores that the balance falls every month. A two-year contract charges two full years of interest on the whole original price." },
  { t: "mcq", tier: "m", src: "Thailand", q: "Why does the OCPB set hire-purchase caps in <em>effective</em> rates rather than flat rates?",
    o: ["Flat rates are illegal in Thailand", "Because a flat rate understates the true cost; capping the effective rate stops lenders hiding behind the lower-looking quote", "Effective rates are easier to compute", "Because motorcycle loans carry no interest"], a: 1,
    x: "A 12% flat motorcycle loan is about 21.6% effective, just under the 23% cap. Quote it flat and it sounds half as expensive as it is." },
  { t: "mcq", tier: "m", src: "Slides", q: "Why did US home equity lending grow rapidly after the Tax Reform Act of 1986?",
    o: ["It banned credit cards", "Interest on home equity loans stayed tax-deductible while deductions for other consumer interest were phased out", "It required banks to stop mortgage lending", "It capped home prices"], a: 1,
    x: "Borrowers switched from car and card debt to home-secured debt to keep the deduction. That is how home equity became a major finance company asset, and a source of losses in 2007–08." },
  { t: "mcq", tier: "m", src: "Slides", q: "Finance companies have historically charged higher consumer loan rates than commercial banks. The main reason is:",
    o: ["They pay interest on deposits", "They lend to riskier borrowers, including subprime customers banks avoid", "They are required to by the Fed", "They have no operating costs"], a: 1,
    x: "Higher rates compensate for higher default risk, and funding costs are also higher without deposits." },
  { t: "mcq", tier: "m", src: "Slides", q: "How does liquidity risk management at a finance company differ from a commercial bank's?",
    o: ["It is identical", "It depends on rolling over commercial paper and market debt, often backed by bank credit lines, rather than a deposit base and central bank access", "Finance companies have no liquidity risk", "They hold mostly cash"], a: 1,
    x: "No deposits and no discount window means refinancing risk. When CP markets froze in 2008, finance companies were hit immediately." },
  { t: "mcq", tier: "m", src: "Thailand", q: "A credit card charges 16% a year, compounded monthly. Why is the effective annual cost above 16%?",
    o: ["Because of the annual card fee", "Because interest charged each month is added to the balance and itself accrues interest", "Because 16% is a daily rate", "It is not; compounding lowers the cost"], a: 1,
    x: "16% is a nominal annual rate. Carry a balance all year and the twelve monthly charges compound to about 17.2%." },
  { t: "mcq", tier: "d", src: "Slides", q: "A regulator caps payday-style loan rates at 36% a year. Using the course's logic, which unintended consequence is most likely?",
    o: ["Every borrower gets cheaper credit", "Lenders stop serving the riskiest borrowers, who may turn to informal lenders (like Thai “helmet loan” sharks) or to lenders that evade the cap through partnerships elsewhere", "Banks start offering payday loans at 36%", "Demand for short-term credit disappears"], a: 1,
    x: "A price ceiling below the cost of lending to high-risk borrowers rations credit. The slides show evasion via national bank partnerships; in Thailand the informal market absorbs excluded borrowers." },
  { t: "mcq", tier: "d", src: "Slides", q: "Why was the Fed's 2008 approval of GMAC as a bank holding company controversial?",
    o: ["GMAC had no auto loans", "It extended the federal safety net to a lender tied to an industrial firm, blurring the separation of banking and commerce and increasing moral hazard", "It forced GM into liquidation", "It made GMAC exempt from all regulation"], a: 1,
    x: "Bailout access for a car company's finance arm raised the question of who belongs inside the safety net. Hence the condition that GM cut its stake below 10%." },
  { t: "mcq", tier: "d", src: "Slides", q: "Why does rolling over a payday loan for a full year cost thousands of percent, not the 390% simple APR?",
    o: ["Because the lender raises the fee each time", "Because each period's fee is charged on the fee-inflated balance, so the cost compounds 26 times", "Because of late penalties", "Because the APR is capped by law"], a: 1,
    x: "390% is fee × periods. Compounded, 15% per fortnight for 26 fortnights is a multiple of the principal. Rollovers are where payday lending becomes catastrophic." },
  { t: "mcq", tier: "d", src: "Slides", q: "Captive finance companies can often offer 0% promotional auto loans that stand-alone lenders cannot. What makes this possible?",
    o: ["Captives are exempt from usury laws", "The parent manufacturer effectively subsidises the loan out of its vehicle margin, and parent guarantees or letters of credit lower the captive's funding cost", "Captives take deposits", "Zero-percent loans have no credit risk"], a: 1,
    x: "The goal is selling cars, not only earning interest. After 9/11, captives used 0% financing to push sales, and parent support lowers their borrowing costs." },
  { t: "mcq", tier: "d", src: "Slides", q: "Finance companies hold more capital relative to assets (about 14%) than banks (about 11.5%). Why?",
    o: ["Regulators require it", "They have no deposit insurance or lender of last resort, so market funders demand a thicker cushion before they keep lending to them", "They are more profitable", "They hold only mortgages"], a: 1,
    x: "Without a safety net, a finance company must signal soundness to the commercial paper market every day. The extra capital is the price of that signal, and it limits how much they can lend." },
]);
