FI.extend("c4", "ememmeemee", ["Textbook 4", "Textbook 4", "Slides", "Slides", "Slides", "Slides", "Slides", "Slides", "Slides", "Thailand"], [
  { t: "mcq", tier: "e", src: "Slides", q: "What are the three core businesses of securities firms and investment banks named in the slides?",
    o: ["Deposit taking, lending, payments", "Underwriting, market making, advising", "Insurance, leasing, factoring", "Monetary policy, supervision, clearing"], a: 1,
    x: "Underwrite securities, make markets in them, and advise on M&A and restructurings. Everything else in the chapter builds on these." },
  { t: "mcq", tier: "e", src: "Slides", q: "A private placement is:",
    o: ["An IPO listed on the SET", "A sale of securities directly to a small number of large investors, without a public offering", "A share buyback", "A trade executed in a dark pool"], a: 1,
    x: "Private placements skip the public offering process. Public offerings are sold to the investing public, as with IPOs and seasoned issues." },
  { t: "mcq", tier: "e", src: "Slides", q: "Market making means:",
    o: ["Advising on mergers", "Quoting bid and ask prices and holding an inventory of securities to trade with clients", "Setting the policy rate", "Only executing clients' orders as an agent"], a: 1,
    x: "Market makers commit capital to inventory and earn the bid-ask spread, bearing price risk. Pure agency brokerage holds no position." },
  { t: "mcq", tier: "e", src: "Textbook 4", q: "Venture capital is best described as:",
    o: ["Short-term bank loans to large firms", "A professionally managed pool of money that finances new, high-risk firms in exchange for equity", "Government grants to start-ups", "Commercial paper issued by finance companies"], a: 1,
    x: "Banks rarely lend to firms with no assets or history, so venture capital fills the gap with equity plus advice, not outright loans." },
  { t: "mcq", tier: "e", src: "Slides", q: "In the US, which body handles day-to-day regulation of broker-dealers (trading abuses, rule violations, capital)?",
    o: ["The FDIC", "FINRA", "The OCC", "The CFPB"], a: 1,
    x: "The SEC sets the standards; FINRA, a self-regulatory organisation, polices members day to day." },
  { t: "num", tier: "m", src: "Textbook 4", q: "An underwriter buys shares from the issuer at ฿47.50 and offers them to the public at ฿50.00. What is the gross spread as a percentage of the offer price?",
    a: 5, tol: 0.01, unit: "%",
    x: "Spread = 50.00 − 47.50 = ฿2.50, and ÷ 50.00 = <b>5%</b>. Dividing by the bid price instead gives 5.26%." },
  { t: "num", tier: "m", src: "Textbook 4", q: "A best-efforts offering of 40 million shares at ฿20 carries a commission of ฿0.80 per share sold. Only 30 million shares sell. How much does the issuer receive, in ฿ million?",
    a: 576, tol: 0.5, unit: "฿m",
    x: "Proceeds = 30m × (20 − 0.80) = <b>฿576m</b>. The 10m unsold shares go back to the issuer. Answering ฿768m assumes all 40m sold, as if it were a firm commitment." },
  { t: "mcq", tier: "m", src: "Slides", q: "US domestic M&A fell from about $1.7 trillion in 2007 to $687 billion in 2010. What best explains the drop in advisory business?",
    o: ["M&A was banned by Dodd-Frank", "The financial crisis dried up deal financing and collapsed valuations and confidence", "Investment banks stopped charging fees", "All firms had already merged"], a: 1,
    x: "Deals need financing and confident buyers. The crisis removed both, although activity stayed above the early-2000s trough." },
  { t: "mcq", tier: "m", src: "Slides", q: "How did decimalisation and online trading affect market makers?",
    o: ["They widened bid-ask spreads", "They narrowed bid-ask spreads and commissions, squeezing trading revenue and adding technology risk", "They eliminated market risk", "They had no effect"], a: 1,
    x: "Prices quoted in cents instead of fractions, plus cheap electronic competition, compressed the spread that market makers earn." },
  { t: "mcq", tier: "m", src: "Slides", q: "What did the National Securities Markets Improvement Act (NSMIA, 1996) do?",
    o: ["Created SIPC", "Confirmed the SEC as the primary regulator of securities firms, pre-empting much state oversight", "Separated banking and securities", "Created FINRA and abolished the SEC"], a: 1,
    x: "Before NSMIA, firms answered to both the SEC and the states. State attorneys general regained influence in the early 2000s through enforcement cases." },
  { t: "mcq", tier: "d", src: "Slides", q: "Securities firms hold far less capital than banks, yet in 2008 they were hit hardest. Which combination best explains why?",
    o: ["They had too many retail deposits", "Thin capital, marked-to-market assets and overnight repo funding with no deposit insurance or routine central bank access, so doubts about collateral became a funding run", "They were banned from trading mortgages", "SIPC refused to pay"], a: 1,
    x: "Losses hit equity immediately through mark-to-market, and repo lenders could refuse to roll over overnight. Banks had insured deposits and the discount window; Bear and Lehman did not." },
  { t: "mcq", tier: "d", src: "Slides", q: "Why would Goldman Sachs and Morgan Stanley choose to become bank holding companies in 2008, accepting heavier regulation?",
    o: ["To avoid SEC oversight entirely", "To gain access to the Fed's lending facilities and signal government backing, stemming the funding run, in exchange for Fed supervision and capital rules", "To start taking payday loans", "Because Glass-Steagall was reinstated"], a: 1,
    x: "Confidence was the scarce asset. BHC status traded independence for the safety net, a textbook case of net regulatory burden being worth paying." },
  { t: "mcq", tier: "d", src: "Slides", q: "An analyst at a securities company downgrades a firm her own group is underwriting, and senior bankers press her to soften it. What is this, and which US response targeted it?",
    o: ["Market timing; the 1940 Act", "A research–investment banking conflict of interest; the 2003 global settlement ($1.4bn) and SEC rules on analyst disclosure", "Risk arbitrage; Dodd-Frank", "Late trading; Sarbanes-Oxley"], a: 1,
    x: "Optimistic research helped win underwriting mandates. New York State's case against Merrill Lynch led to the settlement and to rules separating and disclosing analyst conflicts." },
  { t: "num", tier: "d", src: "Textbook 4", q: "Firm commitment: an underwriter buys 50 million shares at ฿9.40 and offers them at ฿10.00. 70% sell at the offer price. At what price, in ฿, must the remaining shares sell for the underwriter to break even?",
    a: 8, tol: 0.01, unit: "฿",
    x: "Profit on sold shares = 35m × 0.60 = ฿21m. Remaining 15m shares must lose exactly ฿21m: (9.40 − P) × 15m = 21m, so 9.40 − P = 1.40 and P = <b>฿8.00</b>. Answering ฿9.40 ignores the spread already earned." },
  { t: "num", tier: "d", src: "Slides", q: "After a takeover bid of ฿50 a share is announced, a risk arbitrageur buys 1 million target shares at ฿47. Regulators block the deal and the target falls to ฿38. What is the loss, in ฿ million?",
    a: 9, tol: 0.01, unit: "฿m",
    x: "(47 − 38) × 1m = <b>฿9m</b>. The ฿3 gap below the bid was the market's price for deal-break risk. That is why this is <em>risk</em> arbitrage, not pure arbitrage." },
  { t: "num", tier: "d", src: "Slides", q: "A broker-dealer finances ฿1bn of bonds through repo with a 2% haircut. In a panic, lenders raise the haircut to 10%. How much extra equity, in ฿ million, must it find to keep the position?",
    a: 80, tol: 0.1, unit: "฿m",
    x: "Equity needed at 2% = ฿20m; at 10% = ฿100m. Extra = <b>฿80m</b>, a fourfold jump. Firms that couldn't raise it had to dump bonds, which pushed prices and haircuts further. That was the 2008 repo spiral." }
]);
