FI.extend("c4", "ememmeemee", ["Textbook 4", "Textbook 4", "Slides", "Slides", "Slides", "Slides", "Slides", "Slides", "Slides", "Thailand"], [
  { t: "mcq", tier: "e", src: "Slides", q: "What are the three core businesses of securities firms and investment banks named in the slides?",
    o: ["Deposit taking, lending, payments", "Underwriting, market making, advising", "Insurance, leasing, factoring", "Monetary policy, supervision, clearing"], a: 1,
    x: "Underwrite securities, make markets in them, and advise on M&A and restructurings. Everything else in the chapter builds on these." },
  { t: "mcq", tier: "e", src: "Slides", q: "A private placement is:",
    o: ["An IPO listed on the SET", "A sale of securities directly to a small number of large investors, without a public offering", "A share buyback", "A trade executed in a dark pool"], a: 1,
    x: "Private placements skip the public offering process. Public offerings are sold to the investing public, as with IPOs and seasoned issues." },
  { t: "mcq", tier: "e", src: "Slides", q: "Market making means:",
    o: ["Advising on mergers", "Quoting bid and ask prices and holding an inventory of securities to trade with clients", "Setting the policy rate", "Only executing clients' orders as an agent"], a: 1,
    x: "Market makers commit capital to inventory and earn the bid-ask spread, bearing price risk. Pure agency brokerage holds no position." },
  { t: "mcq", tier: "e", src: "Textbook 4", q: "Venture capital is best described as:",
    o: ["Short-term bank loans to large firms", "A professionally managed pool of money that finances new, high-risk firms in exchange for equity", "Government grants to start-ups", "Commercial paper issued by finance companies"], a: 1,
    x: "Banks rarely lend to firms with no assets or history, so venture capital fills the gap with equity plus advice, not outright loans." },
  { t: "mcq", tier: "e", src: "Slides", q: "In the US, which body handles day-to-day regulation of broker-dealers (trading abuses, rule violations, capital)?",
    o: ["The FDIC", "FINRA", "The OCC", "The CFPB"], a: 1,
    x: "The SEC sets the standards; FINRA, a self-regulatory organisation, polices members day to day." },
  { t: "mcq", tier: "m", src: "Textbook 4", q: "The gross spread is the gap between the public offer price and what the underwriter pays the issuer. What does it compensate the underwriter for?",
    o: ["Nothing; it is a stamp duty", "Distribution, due diligence and, under a firm commitment, the risk of being stuck with unsold shares", "Interest on a loan to the issuer", "The exchange listing fee"], a: 1,
    x: "Spreads are wider for smaller, riskier or unfamiliar issuers because the underwriter's placement risk is higher. An off-market spread is also a due-diligence red flag, as 1MDB showed." },
  { t: "mcq", tier: "m", src: "Textbook 4", q: "Under a best-efforts offering, what happens to shares that do not sell?",
    o: ["The underwriter must buy them", "They go back to the issuer, which raises less money; the underwriter earns commission only on the shares it sold", "The exchange buys them", "They are cancelled and the underwriter pays a penalty"], a: 1,
    x: "Best efforts shifts the placement risk to the issuer. It is cheaper than a firm commitment for exactly that reason." },
  { t: "mcq", tier: "m", src: "Slides", q: "US domestic M&A fell from about $1.7 trillion in 2007 to $687 billion in 2010. What best explains the drop in advisory business?",
    o: ["M&A was banned by Dodd-Frank", "The financial crisis dried up deal financing and collapsed valuations and confidence", "Investment banks stopped charging fees", "All firms had already merged"], a: 1,
    x: "Deals need financing and confident buyers. The crisis removed both, although activity stayed above the early-2000s trough." },
  { t: "mcq", tier: "m", src: "Slides", q: "How did decimalisation and online trading affect market makers?",
    o: ["They widened bid-ask spreads", "They narrowed bid-ask spreads and commissions, squeezing trading revenue and adding technology risk", "They eliminated market risk", "They had no effect"], a: 1,
    x: "Prices quoted in cents instead of fractions, plus cheap electronic competition, compressed the spread that market makers earn." },
  { t: "mcq", tier: "m", src: "Slides", q: "What did the National Securities Markets Improvement Act (NSMIA, 1996) do?",
    o: ["Created SIPC", "Confirmed the SEC as the primary regulator of securities firms, pre-empting much state oversight", "Separated banking and securities", "Created FINRA and abolished the SEC"], a: 1,
    x: "Before NSMIA, firms answered to both the SEC and the states. State attorneys general regained influence in the early 2000s through enforcement cases." },
  { t: "mcq", tier: "d", src: "Slides", q: "Securities firms hold far less capital than banks, yet in 2008 they were hit hardest. Which combination best explains why?",
    o: ["They had too many retail deposits", "Thin capital, marked-to-market assets and overnight repo funding with no deposit insurance or routine central bank access, so doubts about collateral became a funding run", "They were banned from trading mortgages", "SIPC refused to pay"], a: 1,
    x: "Losses hit equity immediately through mark-to-market, and repo lenders could refuse to roll over overnight. Banks had insured deposits and the discount window; Bear and Lehman did not." },
  { t: "mcq", tier: "d", src: "Slides", q: "Why would Goldman Sachs and Morgan Stanley choose to become bank holding companies in 2008, accepting heavier regulation?",
    o: ["To avoid SEC oversight entirely", "To gain access to the Fed's lending facilities and signal government backing, stemming the funding run, in exchange for Fed supervision and capital rules", "To start taking payday loans", "Because Glass-Steagall was reinstated"], a: 1,
    x: "Confidence was the scarce asset. BHC status traded independence for the safety net, a textbook case of net regulatory burden being worth paying." },
  { t: "mcq", tier: "d", src: "Slides", q: "An analyst at a securities company downgrades a firm her own group is underwriting, and senior bankers press her to soften it. What is this, and which US response targeted it?",
    o: ["Market timing; the 1940 Act", "A research–investment banking conflict of interest; the 2003 global settlement ($1.4bn) and SEC rules on analyst disclosure", "Risk arbitrage; Dodd-Frank", "Late trading; Sarbanes-Oxley"], a: 1,
    x: "Optimistic research helped win underwriting mandates. New York State's case against Merrill Lynch led to the settlement and to rules separating and disclosing analyst conflicts." },
  { t: "mcq", tier: "d", src: "Textbook 4", q: "In a firm commitment, part of the issue sells at the offer price and the rest must be sold lower. What decides whether the underwriter still breaks even?",
    o: ["The issuer's credit rating", "Whether the spread earned on the shares sold at the offer covers the loss on the shares sold below the purchase price", "The number of investors in the book", "The exchange's closing price that day"], a: 1,
    x: "The spread already banked is a cushion. Ignoring it, and assuming the underwriter loses on every share below its purchase price, overstates the loss." },
  { t: "mcq", tier: "d", src: "Slides", q: "A risk arbitrageur buys a takeover target below the announced bid price. Why is this called <em>risk</em> arbitrage rather than pure arbitrage?",
    o: ["Because it uses derivatives", "Because the gap only closes if the deal completes; if regulators block it the shares fall and the trade loses", "Because it is illegal", "Because it needs no capital"], a: 1,
    x: "The discount to the bid is the market's price for deal-break risk. Pure arbitrage has no such waiting period and no such risk." },
  { t: "mcq", tier: "d", src: "Slides", q: "During a panic, repo lenders raise haircuts. Why does this force a broker-dealer to sell bonds?",
    o: ["Because the bonds have defaulted", "Because a larger haircut means more of each position must be funded with the dealer's own scarce equity; without it, positions must be cut", "Because the central bank orders sales", "Because interest rates fall"], a: 1,
    x: "A haircut moving from 2% to 10% multiplies the equity needed by five. Forced sales push prices down, which raises haircuts again: the 2008 repo spiral that finished Bear Stearns and Lehman." },
]);
