FI.extend("c5", "mememdemee", ["Textbook 5", "Textbook 5", "Thailand", "Textbook 5", "Slides", "Thailand", "Slides", "Slides", "Thailand", "Slides"], [
  { t: "mcq", tier: "e", src: "Slides", q: "Where and when did the first mutual fund appear, according to the slides?",
    o: ["New York, 1940", "Boston, 1924", "London, 1868", "Chicago, 1972"], a: 1,
    x: "Boston, 1924, with slow growth at first. 1940 is the Investment Company Act; 1972 is when money market mutual funds arrived." },
  { t: "mcq", tier: "e", src: "Slides", q: "Money market mutual funds took off from 1972 mainly because:",
    o: ["They were FDIC insured", "Regulation Q capped bank deposit rates, and MMMFs could pay market rates", "Stocks were banned", "Banks stopped offering savings accounts"], a: 1,
    x: "MMMFs let savers earn market rates when deposit rates were capped: disintermediation in action." },
  { t: "mcq", tier: "e", src: "Textbook 5", q: "In an open-end mutual fund, the number of shares outstanding:",
    o: ["Is fixed at launch", "Rises and falls daily with purchases and redemptions at NAV", "Can only fall", "Is set by the stock exchange"], a: 1,
    x: "Investors buy from and sell back to the fund at NAV, so supply adjusts to demand. Closed-end funds have a fixed number of shares." },
  { t: "mcq", tier: "e", src: "Slides", q: "A 12b-1 fee is:",
    o: ["A one-time front-end sales load", "An annual fee charged to fund assets for marketing and distribution", "A tax on capital gains", "A hedge fund performance fee"], a: 1,
    x: "12b-1 fees are ongoing annual charges, often used instead of, or alongside, loads to pay brokers." },
  { t: "mcq", tier: "e", src: "Slides", q: "The slides group hedge funds by risk. A market-neutral or value-oriented fund is classed as:",
    o: ["More risky", "Moderate risk", "Risk avoidance", "Risk-free"], a: 1,
    x: "Market directional = more risky; market neutral or value = moderate; risk avoidance = moderate, consistent returns with low risk." },
  { t: "mcq", tier: "e", src: "Slides", q: "Under the 2004 rules, a mutual fund's chief compliance officer reports directly to:",
    o: ["The fund's executives", "The fund's board of directors", "The fund's largest investor", "The stock exchange"], a: 1,
    x: "Reporting to the board, not management, keeps the CCO independent enough to report wrongdoing and police personal trading." },
  { t: "mcq", tier: "e", src: "Textbook 5", q: "When computing a fund's NAV, what happens if you ignore its liabilities?",
    o: ["NAV is understated", "NAV is overstated, because investors would be credited with money the fund owes to others", "Nothing; liabilities are excluded by definition", "The number of units outstanding changes"], a: 1,
    x: "NAV = (assets − liabilities) ÷ units. Accrued fees, payables and borrowings all belong to creditors before unitholders." },
  { t: "mcq", tier: "m", src: "Textbook 5", q: "How does a fund's NAV respond to the market prices of the shares it holds?",
    o: ["Only when the shares are sold", "Directly: NAV is recomputed from current market prices every day", "Only at the financial year end", "Not at all; NAV is fixed at issue"], a: 1,
    x: "Marking to market is what makes open-end funds fair to investors who join and leave on different days." },
  { t: "mcq", tier: "m", src: "Textbook 5", q: "New investors subscribe to an open-end fund and the manager buys more of the same shares at market prices. What happens to the NAV per unit?",
    o: ["It rises, because the fund is bigger", "It stays the same: assets and units grow in proportion", "It falls, because existing units are diluted", "It doubles"], a: 1,
    x: "Investment <em>size</em> never moves NAV; only market prices do. New money buys new units at the current NAV." },
  { t: "mcq", tier: "m", src: "Textbook 5", q: "Why do fund share classes with a front-end load often suit long-term investors better than classes with a higher annual 12b-1 fee?",
    o: ["Loads are refundable after five years", "A one-off load spreads over many years of holding, while an annual fee is paid every year for as long as the investment lasts", "12b-1 fees are illegal outside the US", "Loads earn interest for the investor"], a: 1,
    x: "The industry convention spreads the load evenly over the holding period. Over five years a 5% load is about 1% a year; over twenty it is a quarter of that." },
  { t: "mcq", tier: "m", src: "Textbook 5", q: "Class A: 5% front-end load plus 0.30% a year. Class C: no load, 1.00% a year. For a 20-year investor, which is cheaper under the same convention?",
    o: ["Class C, because it has no load", "Class A: 5%/20 + 0.30% = 0.55% a year, versus 1.00% for C", "They cost the same", "Class C: 1.00% versus A's 5.30%"], a: 1,
    x: "Long horizons dilute the one-time load. Over 5 years C wins (1.00% vs 1.30%); over 20 years A wins. Horizon changes the answer." },
  { t: "mcq", tier: "m", src: "Textbook 5", q: "A money market fund holds its price at ฿1.00 per unit. How do investors receive their return?",
    o: ["Through a rising unit price", "As additional units or cash dividends, since the price itself is held constant", "They don't; money market funds pay nothing", "As a capital gain at exit"], a: 1,
    x: "The stable price is the product's promise. It is also its vulnerability: when Reserve Primary's assets fell below the promise, it “broke the buck”." },
  { t: "mcq", tier: "d", src: "Textbook 5", q: "Why can a closed-end fund trade at a persistent discount to NAV, while an open-end fund cannot?",
    o: ["Closed-end funds hold worse assets", "Closed-end shares can't be redeemed at NAV, so nothing forces the market price back to NAV; the price reflects demand for the fund's own shares", "Open-end funds are guaranteed by the SEC", "Closed-end funds don't mark to market"], a: 1,
    x: "Open-end redemption at NAV is an arbitrage anchor. Without it, closed-end prices float with sentiment, fees, liquidity and doubts about valuations, as with SET property funds." },
  { t: "mcq", tier: "d", src: "Slides", q: "Early-2000s <em>market timing</em> in international funds exploited stale NAVs. Who was harmed?",
    o: ["Nobody, because it was legal", "Long-term shareholders, whose returns were diluted when timers bought cheap and sold at the next day's catch-up price", "Only the fund manager", "Foreign stock exchanges"], a: 1,
    x: "When a fund's Asian holdings close hours before the US 4pm NAV, timers trade on news the price hasn't absorbed. The profit comes out of the other shareholders' pockets." },
  { t: "mcq", tier: "d", src: "Textbook 5", q: "SEC reforms required a floating NAV for <em>institutional prime</em> money market funds but not government funds. What is the logic?",
    o: ["Government funds are larger", "Prime funds hold credit-risky paper, and institutional investors run fastest, so a fixed $1 NAV there invites first-mover runs", "Retail investors can't calculate NAV", "Government funds pay no interest"], a: 1,
    x: "Credit risk plus sophisticated, fast-moving investors is the run recipe of 2008. Government funds hold Treasuries and repos. Even so, prime funds saw outflows again in March 2020." },
  { t: "mcq", tier: "d", src: "Slides", q: "What does a high-water mark do in a hedge fund's fee contract?",
    o: ["It caps the management fee", "It ensures the performance fee is charged only on gains above the fund's previous peak, so managers are not paid twice for recovering losses", "It guarantees investors a minimum return", "It sets the fund's leverage limit"], a: 1,
    x: "Fall from ฿1,000m to ฿900m and back to ฿1,050m, and only the ฿50m above the old peak earns a fee. Without the mark, the whole recovery would be charged again." },
  { t: "mcq", tier: "d", src: "Slides", q: "Before costs, the average actively managed baht invested in Thai equities earns the market return. What follows after costs?",
    o: ["Active funds beat index funds on average", "The average active fund underperforms a low-cost index fund by roughly its extra fees", "Costs don't affect relative returns", "Index funds must underperform"], a: 1,
    x: "Active investors in aggregate <em>are</em> the market, so they earn its return minus their costs. Some managers win, but the average loses by the fee gap. The Fee Drag lab shows how that compounds." },
  { t: "mcq", tier: "d", src: "Textbook 5", q: "A closed-end fund's NAV is unchanged for a year but its discount to NAV narrows. What happens to an investor who bought at the wide discount?",
    o: ["Nothing, because NAV is unchanged", "They earn a positive return purely from the price moving closer to NAV, with no change in the portfolio", "They lose money", "They must pay the difference to the fund"], a: 1,
    x: "Closed-end fund returns have two sources: the portfolio, and the discount. The second is why activists buy deeply discounted funds and push for open-ending." },
]);
