FI.extend("c5", "mememdemee", ["Textbook 5", "Textbook 5", "Thailand", "Textbook 5", "Slides", "Thailand", "Slides", "Slides", "Thailand", "Slides"], [
  { t: "mcq", tier: "e", src: "Slides", q: "Where and when did the first mutual fund appear, according to the slides?",
    o: ["New York, 1940", "Boston, 1924", "London, 1868", "Chicago, 1972"], a: 1,
    x: "Boston, 1924, with slow growth at first. 1940 is the Investment Company Act; 1972 is when money market mutual funds arrived." },
  { t: "mcq", tier: "e", src: "Slides", q: "Money market mutual funds took off from 1972 mainly because:",
    o: ["They were FDIC insured", "Regulation Q capped bank deposit rates, and MMMFs could pay market rates", "Stocks were banned", "Banks stopped offering savings accounts"], a: 1,
    x: "MMMFs let savers earn market rates when deposit rates were capped: disintermediation in action." },
  { t: "mcq", tier: "e", src: "Textbook 5", q: "In an open-end mutual fund, the number of shares outstanding:",
    o: ["Is fixed at launch", "Rises and falls daily with purchases and redemptions at NAV", "Can only fall", "Is set by the stock exchange"], a: 1,
    x: "Investors buy from and sell back to the fund at NAV, so supply adjusts to demand. Closed-end funds have a fixed number of shares." },
  { t: "mcq", tier: "e", src: "Slides", q: "A 12b-1 fee is:",
    o: ["A one-time front-end sales load", "An annual fee charged to fund assets for marketing and distribution", "A tax on capital gains", "A hedge fund performance fee"], a: 1,
    x: "12b-1 fees are ongoing annual charges, often used instead of, or alongside, loads to pay brokers." },
  { t: "mcq", tier: "e", src: "Slides", q: "The slides group hedge funds by risk. A market-neutral or value-oriented fund is classed as:",
    o: ["More risky", "Moderate risk", "Risk avoidance", "Risk-free"], a: 1,
    x: "Market directional = more risky; market neutral or value = moderate; risk avoidance = moderate, consistent returns with low risk." },
  { t: "mcq", tier: "e", src: "Slides", q: "Under the 2004 rules, a mutual fund's chief compliance officer reports directly to:",
    o: ["The fund's executives", "The fund's board of directors", "The fund's largest investor", "The stock exchange"], a: 1,
    x: "Reporting to the board, not management, keeps the CCO independent enough to report wrongdoing and police personal trading." },
  { t: "num", tier: "e", src: "Textbook 5", q: "A fund has assets with a market value of ฿500m, liabilities of ฿20m, and 40m units outstanding. What is its NAV, in ฿?",
    a: 12, tol: 0.001, unit: "฿",
    x: "NAV = (500 − 20) ÷ 40 = <b>฿12.00</b>. Forgetting liabilities gives ฿12.50." },
  { t: "num", tier: "m", src: "Textbook 5", q: "A Thai fund holds 5,000 SCB shares at ฿110, 8,000 AOT shares at ฿62 and 10,000 KBANK shares at ฿150, with no cash or liabilities. It has 100,000 units outstanding. What is the NAV, in ฿?",
    a: 25.46, tol: 0.001, unit: "฿",
    x: "550,000 + 496,000 + 1,500,000 = ฿2,546,000, and ÷ 100,000 = <b>฿25.46</b>." },
  { t: "num", tier: "m", src: "Textbook 5", q: "Same fund (NAV ฿25.46, 100,000 units). New investors put in ฿254,600, which the manager invests in the same shares at market prices. How many new units are issued?",
    a: 10000, tol: 0.5, unit: "units",
    x: "Units = 254,600 ÷ 25.46 = <b>10,000</b>. NAV stays ฿25.46, because assets and units grow in proportion. Investment <em>size</em> doesn't change NAV; only market prices do." },
  { t: "num", tier: "m", src: "Textbook 5", q: "Class A shares carry a 5% front-end load plus 0.30% a year in management and 12b-1 fees. Using the industry convention (load spread evenly, no time value), what is the annual cost, in %, for an investor who holds for 5 years?",
    a: 1.3, tol: 0.001, unit: "%",
    x: "5% ÷ 5 + 0.30% = 1.00% + 0.30% = <b>1.30%</b> a year. Forgetting to spread the load gives 5.30%." },
  { t: "mcq", tier: "m", src: "Textbook 5", q: "Class A: 5% front-end load plus 0.30% a year. Class C: no load, 1.00% a year. For a 20-year investor, which is cheaper under the same convention?",
    o: ["Class C, because it has no load", "Class A: 5%/20 + 0.30% = 0.55% a year, versus 1.00% for C", "They cost the same", "Class C: 1.00% versus A's 5.30%"], a: 1,
    x: "Long horizons dilute the one-time load. Over 5 years C wins (1.00% vs 1.30%); over 20 years A wins. Horizon changes the answer." },
  { t: "num", tier: "m", src: "Textbook 5", q: "A money market fund keeps its price at ฿1.00 per unit. You hold 10,000 units and the fund earns 2.4% net over the year, credited as extra units. How many units do you hold at year end?",
    a: 10240, tol: 0.5, unit: "units",
    x: "The price stays at ฿1, so returns arrive as more units: 10,000 × 1.024 = <b>10,240 units</b>." },
  { t: "mcq", tier: "d", src: "Textbook 5", q: "Why can a closed-end fund trade at a persistent discount to NAV, while an open-end fund cannot?",
    o: ["Closed-end funds hold worse assets", "Closed-end shares can't be redeemed at NAV, so nothing forces the market price back to NAV; the price reflects demand for the fund's own shares", "Open-end funds are guaranteed by the SEC", "Closed-end funds don't mark to market"], a: 1,
    x: "Open-end redemption at NAV is an arbitrage anchor. Without it, closed-end prices float with sentiment, fees, liquidity and doubts about valuations, as with SET property funds." },
  { t: "mcq", tier: "d", src: "Slides", q: "Early-2000s <em>market timing</em> in international funds exploited stale NAVs. Who was harmed?",
    o: ["Nobody, because it was legal", "Long-term shareholders, whose returns were diluted when timers bought cheap and sold at the next day's catch-up price", "Only the fund manager", "Foreign stock exchanges"], a: 1,
    x: "When a fund's Asian holdings close hours before the US 4pm NAV, timers trade on news the price hasn't absorbed. The profit comes out of the other shareholders' pockets." },
  { t: "mcq", tier: "d", src: "Textbook 5", q: "SEC reforms required a floating NAV for <em>institutional prime</em> money market funds but not government funds. What is the logic?",
    o: ["Government funds are larger", "Prime funds hold credit-risky paper, and institutional investors run fastest, so a fixed $1 NAV there invites first-mover runs", "Retail investors can't calculate NAV", "Government funds pay no interest"], a: 1,
    x: "Credit risk plus sophisticated, fast-moving investors is the run recipe of 2008. Government funds hold Treasuries and repos. Even so, prime funds saw outflows again in March 2020." },
  { t: "num", tier: "d", src: "Slides", q: "A hedge fund charges 20% of gains above its high-water mark of ฿1,000m. It fell to ฿900m last year and ends this year at ฿1,050m before the performance fee. What is the performance fee, in ฿ million?",
    a: 10, tol: 0.01, unit: "฿m",
    x: "Only gains above the previous peak count: 20% × (1,050 − 1,000) = <b>฿10m</b>. Charging on the whole ฿150m recovery would give ฿30m, but the high-water mark stops managers being paid twice for the same gains." },
  { t: "mcq", tier: "d", src: "Slides", q: "Before costs, the average actively managed baht invested in Thai equities earns the market return. What follows after costs?",
    o: ["Active funds beat index funds on average", "The average active fund underperforms a low-cost index fund by roughly its extra fees", "Costs don't affect relative returns", "Index funds must underperform"], a: 1,
    x: "Active investors in aggregate <em>are</em> the market, so they earn its return minus their costs. Some managers win, but the average loses by the fee gap. The Fee Drag lab shows how that compounds." },
  { t: "num", tier: "d", src: "Textbook 5", q: "A closed-end fund's NAV is ฿24 and it trades at ฿21. You buy. A year later NAV is still ฿24 but the discount narrows to 5%. Ignoring distributions, what is your return, in %?",
    a: 8.57, tol: 0.02, unit: "%",
    x: "New price = 24 × 0.95 = ฿22.80. Return = (22.80 − 21) ÷ 21 = <b>8.57%</b>, earned purely from the discount narrowing, with no change in the portfolio." }
]);
