FI.extend("c6", "eemdemmmdm", ["Slides", "Slides", "Textbook 6", "Textbook 6", "Slides", "Slides", "Slides", "Slides", "Slides", "Slides"], [
  { t: "mcq", tier: "e", src: "Slides", q: "Which set are the major liabilities of a property and casualty insurer?",
    o: ["Net policy reserves and policy loans", "Loss reserves, loss adjustment expenses and unearned premiums", "Deposits and commercial paper", "Repos and short positions"], a: 1,
    x: "Net policy reserves are the <em>life</em> insurer's dominant liability. P&amp;C owes for claims incurred (loss reserves), the cost of settling them (LAE), and cover paid for but not yet provided (unearned premium)." },
  { t: "mcq", tier: "e", src: "Slides", q: "Which of these is a form of <em>ordinary</em> life insurance?",
    o: ["Group life", "Industrial life", "Endowment life", "Credit life"], a: 2,
    x: "Ordinary life is the individual market: term, whole, endowment, and the variable, universal and variable universal generation. Group, industrial and credit life are the three separate categories beside it." },
  { t: "mcq", tier: "e", src: "Slides", q: "The slides describe an annuity as:",
    o: ["The reverse of life insurance activities", "A form of credit life", "A property and casualty product", "A reinsurance contract"], a: 0,
    x: "Life insurance builds a fund that pays out on death. An annuity takes a fund and pays it out over a life. The insurer is exposed to people living longer, not dying sooner." },
  { t: "mcq", tier: "e", src: "Slides", q: "Morbidity insurance covers:",
    o: ["Death only", "Accident and health: sickness and injury", "Fire damage to a factory", "Legal liability to third parties"], a: 1,
    x: "Morbidity is sickness and injury, as opposed to mortality. The slides list accident and health cover as a life insurer activity alongside annuities and pensions." },
  { t: "mcq", tier: "e", src: "Textbook 6", q: "A combined ratio greater than 100 means:",
    o: ["The insurer made an overall profit", "Premiums are insufficient to cover losses and expenses", "Investment yields were negative", "The insurer is over-reserved"], a: 1,
    x: "The combined ratio is loss ratio plus expense ratio, so above 100 the underwriting business loses money. Whether the <em>year</em> loses money depends on the operating ratio, which subtracts the investment yield." },
  { t: "mcq", tier: "e", src: "Thailand", q: "Which body supervises both life and non-life insurers in Thailand?",
    o: ["The Bank of Thailand", "SEC Thailand", "The Office of Insurance Commission (OIC, คปภ.)", "The Deposit Protection Agency"], a: 2,
    x: "The OIC regulates both, under the Life Insurance Act and the Non-Life Insurance Act B.E. 2535. In the US this job belongs to fifty state commissions coordinated by the NAIC." },
  { t: "mcq", tier: "m", src: "Slides", q: "The slides count about 2,476 P&C companies, with the top 10 writing 47.6% of premiums. What does that describe?",
    o: ["A fragmented market with no large firms", "A highly concentrated market, with M&A raising concentration further", "A market of only ten firms", "A state-owned industry"], a: 1,
    x: "Thousands of licensed firms, but half the premium in ten of them. Counting firms and measuring concentration are different questions, and the slides make the point deliberately." },
  { t: "mcq", tier: "m", src: "Textbook 6", q: "Why are loss adjustment expenses included in an insurer's loss ratio?",
    o: ["They are not; only claims paid count", "Because investigating and settling claims is part of the cost of the claims themselves", "Because they are paid by reinsurers", "Because regulators tax them"], a: 1,
    x: "Leaving them out flatters the ratio. A claim that costs ฿100 to pay and ฿8 to adjust cost the insurer ฿108." },
  { t: "mcq", tier: "m", src: "Textbook 6", q: "What does an insurer's expense ratio measure?",
    o: ["Claims paid ÷ premiums earned", "Underwriting expenses such as commissions and administration ÷ premiums written", "Investment yield on reserves", "Dividends paid to shareholders"], a: 1,
    x: "Loss ratio plus expense ratio is the combined ratio. The slides note expense ratios have generally fallen as insurers sell more through their own channels." },
  { t: "mcq", tier: "m", src: "Textbook 6", q: "Why do P&C insurers hold more liquid assets and larger capital and reserves than life insurers?",
    o: ["Regulators forbid them to buy bonds", "Their losses are less predictable and can arrive suddenly and together", "Their policies last longer", "They have no investment income"], a: 1,
    x: "Life claims are long-dated and statistically smooth, so long assets match long liabilities. A hurricane turns thousands of policies into one bill payable now, so P&amp;C has to stay shorter and thicker." },
  { t: "mcq", tier: "m", src: "Textbook 6", q: "An annual motor policy is sold in October. At the December year end, why is most of the premium a liability rather than income?",
    o: ["Because the customer has not paid yet", "Because the insurer still owes nine months of cover; the premium is earned only as the cover is provided", "Because motor claims are paid in advance", "Because premiums are refundable on demand"], a: 1,
    x: "Unearned premiums sit beside loss reserves as the main P&amp;C liabilities. The cash is in hand, but the service has not been delivered." },
  { t: "mcq", tier: "m", src: "Thailand", q: "In the 2011 Thai floods roughly $16bn of a $45bn economic loss was insured. What does that ratio illustrate?",
    o: ["Insurers paid for nearly everything", "The protection gap: most catastrophe losses fall on the uninsured, and even the insured share was largely ceded to foreign reinsurers", "Reinsurance failed", "The floods were smaller than reported"], a: 1,
    x: "About a third insured is typical for a large catastrophe. The National Catastrophe Insurance Fund was created afterwards to narrow the gap, and later wound down." },
  { t: "mcq", tier: "m", src: "Slides", q: "Roughly what share of the reinsurance bought by US insurers is written by non-US firms such as Munich Re?",
    o: ["About 10%", "About 35%", "About 75%", "About 95%"], a: 2,
    x: "About 75%. Reinsurance is how a national insurance market exports its tail risk, and it is why a Thai flood or a Japanese tsunami shows up on European balance sheets." },
  { t: "mcq", tier: "d", src: "Textbook 6", q: "An insurer's combined ratio after dividends is 106% and its investment yield is 8%. Which statement is right?",
    o: ["It lost money overall", "Underwriting lost 6 per 100 of premium, but investment income more than covered it, so the operating ratio is below 100 and the year was profitable", "It must raise premiums by 6%", "Investment income is irrelevant to the result"], a: 1,
    x: "Operating ratio = 106 − 8 = 98. The 2-point margin came entirely from the investment book, which is why interest rate and credit risk sit at the heart of Chapter 6." },
  { t: "mcq", tier: "d", src: "Slides", q: "Why does the chapter warn that claims in high-severity, low-frequency lines \"may not be independent\"?",
    o: ["Because those policies are sold to the same customer", "Because one event, such as an earthquake or hurricane, triggers a great many policies simultaneously, so pooling stops reducing risk", "Because the claims are usually fraudulent", "Because reinsurers refuse to cover them"], a: 1,
    x: "Pooling only works on independent risks: average many uncorrelated claims and the total becomes predictable. One catastrophe converts thousands of policies into a single draw, so the law of large numbers stops applying exactly when it is needed." },
  { t: "mcq", tier: "d", src: "Thailand", q: "A Thai life insurer sold long-dated endowments guaranteeing returns set when government bond yields were high, then yields fell for a decade. What is the danger the chapter identifies?",
    o: ["Adverse selection in the motor book", "Maturing assets must be reinvested at lower yields against fixed guarantees, while low rates also make new policies unattractive and give existing policyholders reason to surrender", "Unearned premium reserves become too large", "The expense ratio rises automatically"], a: 1,
    x: "This is the crisis mechanism in the slides: capital losses and low short-term rates hurt the ability to price new policies and create an incentive to surrender existing ones. A surrender wave turns a long, quiet liability into an immediate cash demand." },
  { t: "mcq", tier: "d", src: "Slides", q: "The chapter worries that government catastrophe schemes may crowd out catastrophe bonds. Why does that matter?",
    o: ["Catastrophe bonds pay higher commissions", "Cat bonds move catastrophe risk to capital market investors who choose to hold it; a subsidised public scheme moves the same risk to taxpayers and weakens the price signal", "Cat bonds are risk free", "Government schemes are always cheaper to run"], a: 1,
    x: "TRIA after 9/11 and Thailand's National Catastrophe Insurance Fund after 2011 both show the trade-off: a backstop restores capacity quickly, but if it is priced below the risk it also removes the incentive for private capital to price and carry that risk." },
  { t: "mcq", tier: "d", src: "Slides", q: "Why would a mutual life insurer convert to a stockholder-controlled company, as the slides' trend describes?",
    o: ["To escape state regulation entirely", "To reach equity capital markets for funding and acquisition currency, at the cost of owners whose interests differ from policyholders'", "Because mutuals may not sell annuities", "To qualify for FDIC insurance"], a: 1,
    x: "A mutual can only raise capital from retained surplus and debt. Demutualization buys access to equity and a share currency for consolidation, and introduces a classic agency problem: shareholders want returns, policyholders want security." }
]);
