FI.extend("c7", "emdemmmeem", ["Slides", "Textbook 7", "Slides", "Slides", "Textbook 7", "Slides", "Slides", "Slides", "Slides", "Textbook 7"], [
  { t: "mcq", tier: "e", src: "Slides", q: "What does the chapter say about whether these nine risks are peculiar to financial institutions?",
    o: ["They are unique to banks", "They are unique to regulated FIs", "They are not unique to FIs: all global firms face them", "They apply only to institutions with foreign operations"], a: 2,
    x: "An airline hedges fuel and currency, a manufacturer worries about a customer's credit, everyone has operational risk. What is distinctive about FIs is concentration: for them these risks <em>are</em> the business, not a side effect of it." },
  { t: "mcq", tier: "e", src: "Slides", q: "The failure of IndyMac in the summer of 2008 is used in the chapter to illustrate:",
    o: ["Sovereign risk", "Liquidity risk, and how a run turns a liquidity problem into a solvency problem", "Operational risk", "Off-balance-sheet risk"], a: 1,
    x: "Depositors queued, assets had to be sold quickly and therefore cheaply, and the forced sale created the very loss that had been feared. The sequence matters more than the name." },
  { t: "mcq", tier: "e", src: "Slides", q: "Washington Mutual appears in the chapter as the example of:",
    o: ["Insolvency risk", "Technology risk", "Reinvestment risk", "Country risk"], a: 0,
    x: "Insolvency risk is where the other eight risks end up: too little capital to absorb a sudden fall in asset values. \"Too big to fail\", with Citigroup named, is the same ending prevented at public expense." },
  { t: "mcq", tier: "e", src: "Slides", q: "Which of these is an off-balance-sheet item?",
    o: ["A term deposit", "A government bond held to maturity", "An undrawn loan commitment", "Retained earnings"], a: 2,
    x: "Until the borrower draws it, the commitment is a contingent liability: a promise to lend on agreed terms. It costs nothing today and can cost a great deal on the day everyone draws at once." },
  { t: "mcq", tier: "e", src: "Slides", q: "The Target hacking incident of 2013, Heartland Payment Systems and the London Whale are all cited as examples of:",
    o: ["Credit risk", "Technology and operational risk", "Sovereign risk", "Reinvestment risk"], a: 1,
    x: "Two external attacks on systems and one internal control failure. The definition is deliberately broad: processes, people, systems, or external events." },
  { t: "mcq", tier: "e", src: "Thailand", q: "In 1997 Thai finance companies held baht assets funded by short-term US dollar borrowing. Which risk does that structure create?",
    o: ["Operational risk", "Foreign exchange risk, from an unhedged net short dollar position", "Technology risk", "Reinvestment risk"], a: 1,
    x: "Dollar liabilities exceeding dollar assets is a net short position in the dollar, so a rising dollar raises the debt in baht terms. The pegged rate was treated as the hedge, and it was the peg that broke." },
  { t: "num", tier: "m", src: "Textbook 7", q: "An FI funds a ฿100m two-year asset yielding 10% with one-year borrowing at 6%, rolled at 9% for year 2. What is its total profit over the two years, in ฿ million?",
    a: 5, tol: 0.05, unit: "฿m",
    x: "Year 1: 100 × (10% − 6%) = ฿4m. Year 2: 100 × (10% − 9%) = ฿1m. Total <b>฿5m</b>, against ฿8m if funding had stayed at 6%. Refinancing risk does not have to be fatal to be expensive." },
  { t: "num", tier: "m", src: "Textbook 7", q: "Now reverse it: a ฿100m one-year asset yielding 10% is funded by two-year borrowing at 6%. At the end of year 1 the proceeds are reinvested at 8%. What is the spread in year 2, in %?",
    a: 2, tol: 0.05, unit: "%",
    x: "8% − 6% = <b>2%</b>, down from 4% in year 1. This is reinvestment risk: the asset is the shorter side, so it is <em>falling</em> rates that hurt, the mirror image of refinancing risk." },
  { t: "mcq", tier: "m", src: "Slides", q: "What is the practical difference between firm-specific and systematic credit risk?",
    o: ["There is none; the terms are interchangeable", "Firm-specific risk can be diversified away across many borrowers, while systematic credit risk moves with the economy and survives diversification", "Systematic risk affects only foreign borrowers", "Firm-specific risk applies only to consumer loans"], a: 1,
    x: "A hundred unrelated borrowers protect you from one of them failing. They protect you from nothing when a recession, a rate cycle or a property crash arrives for all of them at once." },
  { t: "mcq", tier: "m", src: "Slides", q: "Which set are the chapter's four responses to growing credit risk?",
    o: ["Higher rates, shorter maturities, more collateral, more branches", "Screening and monitoring, diversification, loan sales and good bank-bad bank structures, and credit derivatives", "Deposit insurance, capital, reserves, and stress tests", "Letters of credit, commitments, swaps, and futures"], a: 1,
    x: "The first prevents bad loans, the second stops any one of them mattering, the third removes them once made, and the fourth transfers the default risk while the loan stays put." },
  { t: "mcq", tier: "m", src: "Slides", q: "An FI matches US$500m of dollar assets against US$500m of dollar liabilities, but the assets are five-year and the liabilities are three-month. What exposure remains?",
    o: ["None; it is fully hedged", "Foreign interest rate risk, because the two sides reprice at different times", "Sovereign risk only", "Operational risk only"], a: 1,
    x: "The currency exposure is closed but the maturity exposure is not, so US rates still move the spread and the present values. The textbook's footnote is stricter again: what must match is duration, not simple maturity." },
  { t: "mcq", tier: "m", src: "Slides", q: "The chapter notes that the dollar may appreciate against the euro while falling against the yen. What does that imply for an FI with foreign operations?",
    o: ["Foreign exposure is riskless if spread across two countries", "Exchange rates are not perfectly correlated, so exposure must be diversified across currencies; it is <em>undiversified</em> foreign exposure that creates FX risk", "All foreign exposure should be closed", "Only the dollar matters"], a: 1,
    x: "The chapter is careful here. Going abroad is not the risk; concentrating abroad is. Imperfect correlation between currencies and between foreign and domestic returns is precisely what makes diversification work." },
  { t: "num", tier: "m", src: "Textbook 7", q: "A bank writes off ฿12.6bn of bad loans, net of recoveries, against average loans of ฿1,800bn. What is its net charge-off rate, in %?",
    a: 0.7, tol: 0.01, unit: "%",
    x: "12.6 ÷ 1,800 = <b>0.70%</b>. The chapter tracks this ratio because it is credit risk actually realised, as opposed to provisioned for: US charge-offs kept climbing into late 2008." },
  { t: "mcq", tier: "m", src: "Thailand", q: "In 2023 Thai banks faced a wave of fraud in which customers were tricked into authorising transfers themselves. Under the chapter's taxonomy this is:",
    o: ["Credit risk, because money was lost", "Operational risk, which covers losses from external events as well as internal process and system failures", "Market risk", "Sovereign risk"], a: 1,
    x: "No borrower defaulted and no price moved. The BOT's response was a controls response: stronger authentication for larger mobile transfers and no links in bank SMS. Check current thresholds before quoting them, since they have been revised." },
  { t: "mcq", tier: "m", src: "Slides", q: "The chapter pairs economies of scale with economies of scope. What is the difference?",
    o: ["They are the same thing", "Scale is lower average cost as volume of one product rises; scope is cost savings from producing several products on shared systems", "Scale applies to banks, scope to insurers", "Scope is a type of credit risk"], a: 1,
    x: "Technology promises both, which is why FIs keep buying it. The same shared platform that delivers the savings also concentrates the operational risk in one place." },
  { t: "mcq", tier: "d", src: "Slides", q: "A borrower draws down an old loan commitment at a fixed rate, just as market rates have risen and its own credit has deteriorated. Which risks has the FI just met at once?",
    o: ["Only credit risk", "Off-balance-sheet, interest rate and credit risk together", "Only operational risk", "Only liquidity risk"], a: 1,
    x: "This is the chapter's own interdependency example. The contingent item becomes an asset, it is priced at yesterday's rate, and it is now owed by a worse borrower. Commitments are drawn hardest in exactly the conditions that make them least attractive to fund." },
  { t: "num", tier: "d", src: "Textbook 7", q: "An FI holds a zero-coupon bond with a face value of ฿100m maturing in 5 years, bought when yields were 3%. Yields rise to 5%. What is the bond's market value now, in ฿ million?",
    a: 78.35, tol: 0.1, unit: "฿m",
    x: "100 ÷ 1.05⁵ = <b>฿78.35m</b>, against 100 ÷ 1.03⁵ = ฿86.26m before. A fall of 9.2% with no default, no sale and no change in the promised cash flows: value is the PV of cash flows, so rates alone rewrote it. Hold it to maturity and you still get ฿100m; be forced to sell it and you do not." },
  { t: "mcq", tier: "d", src: "Slides", q: "Silicon Valley Bank's collapse in 2023 began with unrealised losses on long-dated bonds and ended in failure within days. Which point from this chapter does it demonstrate best?",
    o: ["That sovereign risk is unavoidable", "That risks are interdependent: interest rate risk created the loss, liquidity risk forced it to be realised, and insolvency risk was the result", "That operational risk is the largest category", "That diversification eliminates systematic risk"], a: 1,
    x: "One risk on Monday and a different one on the death certificate. The chapter's closing point is precisely that these categories are a vocabulary for describing a single chain of events, not nine separate dangers." },
  { t: "mcq", tier: "d", src: "Slides", q: "When a foreign government blocks repayment, the chapter says the FI's remaining bargaining chip is the future supply of loans. When is that chip nearly worthless?",
    o: ["When the loans are large", "When the currency is collapsing or the government is failing, because a country in that position gains little from the promise of future credit", "When the loans are in local currency", "When other banks are also lending"], a: 1,
    x: "Leverage over a sovereign depends on it wanting something from you tomorrow. A government fighting for survival discounts tomorrow steeply, and there is no court that can wind up a country in the meantime." }
]);
