/* Common-knowledge questions: background every finance student is assumed to have, tied back to the chapter it supports.
   Loaded last, so the base questions already carry their own tiers and sources. Appended only, never reordered. */
(() => {
const add = (id, more) => FI.extend(id, "", [], more.map(q => Object.assign({ src: "General" }, q)));

add("c1", [
  { t: "mcq", tier: "e", q: "In everyday use, an asset is called <em>liquid</em> when:",
    o: ["It pays a high return", "It can be turned into cash quickly at close to its market value", "It is guaranteed by the government", "It has a long maturity"], a: 1,
    x: "Cash is perfectly liquid; a condominium is not. Chapter 1's <b>liquidity cost</b> is exactly this: a saver holding a direct claim on a company cannot sell it in a hurry without accepting a discount." },
  { t: "mcq", tier: "e", q: "What is the difference between a nominal and a real interest rate?",
    o: ["Nominal is after tax; real is before tax", "Real strips out inflation: roughly the nominal rate minus the inflation rate, and it can be negative", "Real is the rate banks quote to customers", "They are the same in Thailand"], a: 1,
    x: "A 3% deposit in 5% inflation is losing purchasing power every year. The habit that matters is always asking “compared with inflation?”." },
  { t: "mcq", tier: "m", q: "A driver with fully comprehensive cover starts parking in riskier places. Economists call this:",
    o: ["Adverse selection", "Moral hazard", "Diversification", "Arbitrage"], a: 1,
    x: "Moral hazard is a change in behaviour <em>after</em> the cover is in place. Adverse selection happens <em>before</em>: the riskiest drivers are the keenest to buy. Chapter 1 raises moral hazard as the price of deposit insurance; Chapter 6 raises adverse selection as the life insurer's pricing problem." },
  { t: "mcq", tier: "m", q: "Why does the market price of an existing fixed-rate bond fall when market interest rates rise?",
    o: ["The issuer stops paying coupons", "Its fixed coupon is now worse than what new bonds pay, so buyers will only take it at a discount", "Inflation destroys the principal", "Rating agencies downgrade it automatically"], a: 1,
    x: "The coupon is fixed, so only the price can adjust. This is the <b>price risk</b> Chapter 1 says FIs absorb on the saver's behalf, and it is the unrealised loss that destroyed SVB in 2023." },
  { t: "mcq", tier: "e", q: "Which of these is <em>not</em> normally a central bank's job?",
    o: ["Setting the policy interest rate", "Acting as lender of last resort to banks", "Maximising profit for its shareholders", "Issuing banknotes"], a: 2,
    x: "Central banks are public institutions with mandates for price and financial stability, not profit. The Bank of Thailand, like the Fed, does the other three." },
  { t: "mcq", tier: "m", q: "Why does compound interest beat simple interest over long periods?",
    o: ["Because banks pay more on longer deposits", "Because interest already earned starts earning interest itself, so growth accelerates over time", "Because simple interest is capped by law", "Because inflation is lower for long deposits"], a: 1,
    x: "Over three years the gap is a few baht; over decades it is most of the balance. Compounding is the whole argument for saving early and for minding fees." },
  { t: "mcq", tier: "e", q: "PromptPay lets Thai households send money instantly using a phone number or ID. Which of Chapter 1's special services is that?",
    o: ["Denomination intermediation", "Payment services", "Credit allocation", "Maturity intermediation"], a: 1,
    x: "Payment services. The textbook's US equivalents are Fedwire and CHIPS for large values, and FedNow (2023) for retail instant payments, which arrived six years after PromptPay." }
]);

add("c2", [
  { t: "mcq", tier: "e", q: "Why can a bank not repay all its depositors at once, even when it is perfectly solvent?",
    o: ["It is forbidden by law", "It has lent most of the deposits out in longer-term loans and keeps only a fraction as cash", "Deposits are not really money", "The central bank blocks withdrawals"], a: 1,
    x: "Fractional reserve banking. <b>Solvency</b> asks whether assets exceed liabilities; <b>liquidity</b> asks whether the cash is there today. A run attacks the second, and can kill a bank that would have passed the first." },
  { t: "mcq", tier: "m", q: "What is a bank's net interest margin, and what does it pay the bank for?",
    o: ["Fees ÷ assets; payment for services", "(Interest earned − interest paid) ÷ earning assets; the reward for carrying the maturity mismatch and the credit risk", "Net income ÷ equity; leverage", "Deposits ÷ loans; liquidity"], a: 1,
    x: "NIM is the core of bank income. It is also what Chapter 7's interest rate risk attacks: when funding reprices faster than assets, the margin compresses." },
  { t: "mcq", tier: "e", q: "Why is a mortgage usually far cheaper than a credit card balance?",
    o: ["Mortgages are shorter term", "The mortgage is secured on the property, so the lender's loss if the borrower defaults is much smaller", "Credit cards are unregulated", "Mortgages are insured by the SET"], a: 1,
    x: "Collateral, not kindness. The BOT caps Thai credit cards at 16% a year while mortgage rates sit far below that, and almost all of the gap is recovery in default." },
  { t: "mcq", tier: "m", q: "\"Too big to fail\" describes a bank that:",
    o: ["Has never made a loss", "Is so large or interconnected that governments feel forced to rescue it, which lets it borrow more cheaply than its own risk deserves", "Is legally immune from bankruptcy", "Holds more capital than required"], a: 1,
    x: "The rescue is the problem, not the solution: an implicit guarantee is a subsidy, and a subsidised risk gets taken more often. FDICIA 1991 tried to restrict bailouts and Dodd-Frank 2010 added resolution planning." },
  { t: "mcq", tier: "e", q: "SWIFT is best described as:",
    o: ["A global bank", "A messaging network banks use to instruct cross-border payments", "A currency", "A credit rating agency"], a: 1,
    x: "SWIFT moves instructions, not money; the money moves through correspondent accounts. That is why being cut off from SWIFT is so damaging to a sanctioned bank: the money still exists, but nobody can be told to move it." },
  { t: "mcq", tier: "m", q: "Why does the share of a bank's assets funded by equity matter so much to regulators?",
    o: ["Because it sets the bank's tax rate", "Because it is the size of asset loss the bank can absorb before it is insolvent", "Because it determines deposit interest rates", "It doesn't; deposits matter more"], a: 1,
    x: "Equity of 8% of assets means an 8% fall in asset values wipes out the owners. That single number is the reason capital regulation exists." },
  { t: "mcq", tier: "e", q: "Thai savings cooperatives take deposits from members and lend to them, but sit outside BOT supervision and the DPA. Their closest US counterpart is:",
    o: ["Money center banks", "Credit unions", "Investment banks", "Money market funds"], a: 1,
    x: "Both are member-owned, common-bond, non-profit deposit takers. The difference matters: US credit unions have the NCUA and its insurance fund behind them, while Thai cooperatives sit under the Cooperative Promotion Department with no deposit guarantee at all." }
]);

add("c3", [
  { t: "mcq", tier: "e", q: "What does an APR include that a headline interest rate may not?",
    o: ["Only the interest", "Compulsory fees and charges, so it shows the full annual cost of borrowing", "Future inflation", "The lender's profit margin only"], a: 1,
    x: "Two loans quoting the same rate can have very different APRs once arrangement fees and compulsory insurance are folded in. It is the same misdirection the flat rate performs, just moved to a different line of the contract." },
  { t: "mcq", tier: "e", q: "A credit bureau such as Thailand's NCB exists mainly to:",
    o: ["Set interest rates", "Share borrowers' repayment histories between lenders, reducing information asymmetry", "Insure lenders against default", "License finance companies"], a: 1,
    x: "It is Chapter 1's information problem solved by pooling data. Past behaviour is the cheapest predictor a lender has, and sharing it stops good borrowers quietly subsidising bad ones." },
  { t: "mcq", tier: "m", q: "A lender expects some borrowers to default. Why must it charge all borrowers more than its own required return?",
    o: ["To punish borrowers for risk", "Because the interest paid by those who repay must also cover the principal lost on those who do not", "Because regulators set a minimum spread", "It need not; defaults are insured"], a: 1,
    x: "Most of the premium over the required return is not profit: it is the cost of the loans that never come back. Expected loss is priced in before a single default happens." },
  { t: "mcq", tier: "m", q: "\"Buy now, pay later\" schemes that split a purchase into interest-free instalments are, in Chapter 3's vocabulary, a modern form of:",
    o: ["Factoring", "Sales finance: credit extended to the customers of a particular retailer", "Deposit taking", "Market making"], a: 1,
    x: "The same structure as GMAC financing car buyers, moved to the checkout page. The borrower pays no interest because the merchant pays a fee, and the merchant pays it because the credit lifts the sale." },
  { t: "mcq", tier: "e", q: "Under a Thai hire-purchase contract for a car, who owns the vehicle until the final instalment is paid?",
    o: ["The buyer", "The finance company", "The insurer", "The dealer's bank"], a: 1,
    x: "Title passes only on the last payment, which is what makes repossession straightforward and keeps the rate below unsecured credit. A lease differs at the other end: the asset normally goes back rather than transferring." },
  { t: "mcq", tier: "m", q: "Why do informal lenders charge rates far above the legal caps, when borrowers could in principle go to a bank?",
    o: ["Their funding costs are higher than banks'", "They serve borrowers banks reject, with no collateral, no documentation and high default rates, and they carry the enforcement risk themselves", "The law requires it", "They are more efficient than banks"], a: 1,
    x: "Chapter 3's point about serving riskier customers, pushed to its extreme. The policy answer is not only enforcement but legal access, which is what Thailand's nano and pico finance licences were created to provide." },
  { t: "mcq", tier: "m", q: "Why does a lender care about a borrower's debt service ratio, the share of monthly income already committed to repayments?",
    o: ["It measures the borrower's total wealth", "It measures whether the borrower can afford another instalment out of current income, which is what actually prevents a default", "It is required for tax purposes", "It sets the legal interest rate cap"], a: 1,
    x: "Income pays instalments; assets only matter after things have already gone wrong. Thai household debt near 90% of GDP is why the BOT's responsible-lending rules are built around this measure." }
]);

add("c4", [
  { t: "mcq", tier: "e", q: "An initial public offering is:",
    o: ["A company borrowing from a bank", "The first sale of a company's shares to public investors", "A merger of two listed firms", "A government bond auction"], a: 1,
    x: "After the IPO the shares change hands between investors on the secondary market, and the company receives nothing further from those trades." },
  { t: "mcq", tier: "e", q: "A market maker quotes a stock at bid ฿24.50 / ask ฿24.75. What is that ฿0.25 difference?",
    o: ["A tax", "The spread: the market maker's compensation for standing ready to buy and sell from its own inventory", "The dividend", "The brokerage commission"], a: 1,
    x: "It buys at the bid and sells at the ask. The spread pays for the risk of holding a position that nobody else wanted at that moment, which is the whole service being sold." },
  { t: "mcq", tier: "m", q: "A short seller borrows shares and sells them. They profit when:",
    o: ["The price rises", "The price falls, so they can buy back cheaper and return the borrowed shares", "The company pays a dividend", "Trading is suspended"], a: 1,
    x: "Losses on a short are theoretically unlimited, because there is no ceiling on a price. That asymmetry drives every short squeeze, and it is behind Archegos: the prime brokers were funding positions whose downside had no floor." },
  { t: "mcq", tier: "e", q: "The SET Index and the S&P 500 both measure:",
    o: ["The number of listed companies", "The combined value of a basket of listed shares, used as a benchmark for the market", "Corporate bond yields", "Central bank policy rates"], a: 1,
    x: "An index is a yardstick, not an investment. Index funds and ETFs exist to track one, which is Chapter 5's territory." },
  { t: "mcq", tier: "m", q: "What does a company's market capitalisation measure, and what does it leave out?",
    o: ["Total assets; nothing", "The market value of its equity (shares × price); it says nothing about the debt sitting beside that equity", "Annual profit; taxes", "Book value; goodwill"], a: 1,
    x: "Two firms with identical market caps can carry wildly different risk if one is financed with far more debt. Market cap prices the equity slice only." },
  { t: "mcq", tier: "m", q: "When you buy SCB shares from another investor on the SET, how much of your money reaches SCB?",
    o: ["All of it", "None: secondary market trades move money between investors, not into the company", "Half", "Only the dividend portion"], a: 1,
    x: "Companies raise money in the <b>primary</b> market, at IPO or in a seasoned offering. The secondary market's job is to make those claims liquid, which is precisely why investors are willing to buy them in the primary market at all." },
  { t: "mcq", tier: "d", q: "Why is a securities firm that both underwrites a company's shares and publishes research on them exposed to a conflict of interest?",
    o: ["Research is illegal for underwriters", "Favourable research helps win and place underwriting business, so the analyst is under pressure to stay positive about a client", "Underwriters may not own shares", "Research must legally be free"], a: 1,
    x: "This is exactly what the 2003 global settlement, $1.4bn across ten firms, was about. Research and banking are now separated by information barriers, and analysts' pay may not be tied to banking revenue." }
]);

add("c5", [
  { t: "mcq", tier: "e", q: "\"Don't put all your eggs in one basket\" is the everyday version of which idea?",
    o: ["Leverage", "Diversification: combining imperfectly correlated assets lowers the risk of the portfolio as a whole", "Arbitrage", "Market timing"], a: 1,
    x: "The catch is the one Chapter 6 keeps hammering: it only works while the eggs are not all dropped by the same event. Correlated risks defeat diversification exactly when you need it." },
  { t: "mcq", tier: "e", q: "The main practical difference between an ETF and a traditional open-end mutual fund is:",
    o: ["ETFs hold only bonds", "ETF units trade on an exchange throughout the day, while open-end fund units are bought and redeemed at the day's NAV", "ETFs charge no fees", "ETFs are government guaranteed"], a: 1,
    x: "Both can track the same index. The difference is plumbing: exchange trading plus a creation-and-redemption mechanism run by authorised participants, which is what keeps the ETF's price close to its NAV." },
  { t: "mcq", tier: "m", q: "The rule of 72 says 72 ÷ the annual rate ≈ years to double. Why is it a useful lens on fund fees?",
    o: ["It shows that fees are irrelevant", "A fee that trims the return from 8% to 6% stretches doubling from about 9 years to about 12: small percentages, large amounts of time", "It shows funds double every 72 months", "It sets the legal maximum fee"], a: 1,
    x: "Run it the other way to feel fee drag. At 4.5% net you wait 16 years to double; at 8% gross you would have waited 9." },
  { t: "mcq", tier: "m", q: "A fund gains 50% one year and loses 50% the next. Why is the investor down 25% rather than flat?",
    o: ["Because of fees", "Because returns compound: the 50% loss is taken on a larger base than the 50% gain, so losses need bigger gains to undo them", "Because of tax", "The investor is flat; the arithmetic average is zero"], a: 1,
    x: "1.5 × 0.5 = 0.75. Compounded returns, not averages, are what actually pay for anything, and they punish volatility." },
  { t: "mcq", tier: "m", q: "Investing a fixed amount every month, whatever the price, means you:",
    o: ["Always beat the market", "Buy more units when prices are low and fewer when they are high, which removes the need to time your entry", "Pay no fees", "Eliminate market risk"], a: 1,
    x: "It manages behaviour, not risk. The market risk is untouched; what it removes is the chance of committing everything on the worst possible day, and the temptation to keep guessing which day that is." },
  { t: "mcq", tier: "d", q: "A fund family advertises that its funds have beaten the market on average over ten years, but it has quietly closed or merged away its worst performers. What is the flaw?",
    o: ["Nothing, the figure is audited", "Survivorship bias: the average covers only the funds that survived, so the failures have been removed from the record", "The funds are too diversified", "Fees are excluded by law"], a: 1,
    x: "The same trap infests hedge fund indices, where reporting is voluntary and a dying fund simply stops reporting. It is one reason the average active fund's real record looks worse than the advertised one." },
  { t: "mcq", tier: "e", q: "Why does a government bond fund usually offer a lower expected return than an equity fund?",
    o: ["Bond funds charge higher fees", "Investors demand extra return for bearing extra risk, and government bonds carry far less of it", "Bonds pay no income", "Equity funds are insured"], a: 1,
    x: "The risk-return trade-off is the most reused idea in the course. Any product promising equity-like returns with deposit-like safety is mispriced, misunderstood or misrepresented, and Chapter 5's cases show all three." }
]);

add("c6", [
  { t: "mcq", tier: "e", q: "A policy with a ฿5,000 deductible (excess) means:",
    o: ["The insurer pays the first ฿5,000", "The policyholder pays the first ฿5,000 of any claim", "The premium is ฿5,000", "Cover stops at ฿5,000"], a: 1,
    x: "Deductibles do two jobs at once: they strip out small claims that cost more to process than to pay, and they leave the policyholder with a real stake in avoiding the loss, which blunts moral hazard." },
  { t: "mcq", tier: "e", q: "What does an actuary do?",
    o: ["Sells policies door to door", "Uses statistics to estimate future claims and set premiums and reserves", "Investigates fraudulent claims", "Regulates insurance companies"], a: 1,
    x: "The actuary's estimate <em>becomes</em> the net policy reserve on the balance sheet. The entire liability side of a life insurer rests on their assumptions about mortality, lapse rates and investment returns." },
  { t: "mcq", tier: "m", q: "A health insurer finds that people buying its most generous plan are already sicker than average <em>before</em> they buy. That is:",
    o: ["Moral hazard", "Adverse selection", "Social inflation", "Reinsurance"], a: 1,
    x: "Adverse selection happens at the point of purchase; moral hazard is the behaviour change afterwards, such as visiting the doctor more because it is now free. Chapter 6 names the first as the life insurer's central problem; deductibles and co-payments are aimed at the second." },
  { t: "mcq", tier: "m", q: "What is an insurer's pure (risk) premium?",
    o: ["The total price the customer pays", "Expected claims per policy: the probability of a claim × its average severity", "The commission paid to agents", "The investment yield on reserves"], a: 1,
    x: "Everything charged above the pure premium covers expenses, commission, profit and a cushion for a worse-than-expected year: the things the expense and combined ratios measure." },
  { t: "mcq", tier: "m", q: "An insurer needs expenses and profit to take 28% of each premium. Why is the gross premium not simply the pure premium plus 28%?",
    o: ["Because taxes are added separately", "Because the 28% is a share of the final premium, so the pure premium must be divided by 72%, not marked up by 28%", "Because premiums are regulated", "Because reinsurance covers the expenses"], a: 1,
    x: "Marking up by 28% leaves the insurer short every single year. It is the same mistake as confusing a discount on the sale price with a mark-up on cost." },
  { t: "mcq", tier: "m", q: "A Thai motor insurer offers a discount that grows with every claim-free year. In insurance terms this is:",
    o: ["Reinsurance", "Experience rating: pricing each policyholder on their own record, which fights adverse selection and moral hazard at once", "A deductible", "An unearned premium"], a: 1,
    x: "Careful drivers self-select into the insurer, and every driver gains a reason to stay careful. It is the cheapest underwriting tool there is, because the policyholders do the sorting themselves." },
  { t: "mcq", tier: "d", q: "Insurers collect premiums before they pay claims and invest the money in between. Why does that matter so much for a P&C insurer?",
    o: ["It is illegal in most countries", "Investment income on those reserves can turn an underwriting loss into a profitable year, which is exactly why the operating ratio subtracts the investment yield from the combined ratio", "It removes the need to hold capital", "It eliminates catastrophe risk"], a: 1,
    x: "An insurer running a 104% combined ratio with a 7% investment yield still made money. It cuts the other way too: falling interest rates squeeze insurers twice, through lower investment income and through higher present values for long-tail liabilities." },
  { t: "mcq", tier: "e", q: "Thailand's Universal Coverage Scheme (บัตรทอง), introduced in 2002 and long known for its ฿30 fee per visit, covers most of the population. What does that imply for private health insurers here?",
    o: ["They cannot legally operate", "They compete on top-up benefits such as private rooms, faster access and wider choice, rather than on basic coverage", "They must be state owned", "They may only sell to foreigners"], a: 1,
    x: "Where a public scheme covers the basics, private cover moves up-market into supplementary benefits. The same pattern appears in every country with universal coverage, and it decides which risks private insurers actually end up pooling." }
]);

add("c7", [
  { t: "mcq", tier: "e", q: "To <em>hedge</em> an exposure means to:",
    o: ["Insure it with a licensed insurer", "Take an offsetting position, so a loss on one side is matched by a gain on the other", "Sell the asset immediately", "Borrow against it"], a: 1,
    x: "Hedging removes the upside along with the downside, which is why it is a cost rather than a free lunch. A hedge that still makes money when things go well is usually not a hedge." },
  { t: "mcq", tier: "e", q: "A Thai importer must pay dollars in three months. Which move hurts, and what kind of position is it?",
    o: ["Baht strengthens; a net long dollar position", "Baht weakens, because more baht are needed for the same dollars; effectively a short dollar position", "Nothing hurts; there is no FX exposure", "Dollar falls; a net short baht position"], a: 1,
    x: "Being short a currency you must buy later is an FX exposure whether or not you call it one. A weaker baht helps exporters and hurts importers for the same reason." },
  { t: "mcq", tier: "m", q: "What normally happens to a firm's borrowing costs after a credit rating downgrade?",
    o: ["Nothing; ratings are only opinions", "They rise, and contracts may additionally require more collateral or allow lenders to withdraw", "They fall, because the firm is riskier", "They are fixed by the central bank"], a: 1,
    x: "The second half is what kills firms. A downgrade that merely raises the cost of new debt is survivable; a downgrade that triggers collateral calls on existing contracts demands cash today, which is what happened to AIG in 2008." },
  { t: "mcq", tier: "m", q: "Value at risk (VaR) reports something like \"a 1% chance of losing more than ฿50m in a day\". What is its main blind spot?",
    o: ["It overstates risk", "It says nothing about how bad the loss is once you are inside that 1% tail", "It cannot be computed for equities", "It ignores the size of the portfolio"], a: 1,
    x: "VaR gives the threshold, not the damage beyond it, and it is estimated from history that may contain no comparable event. It is still worth having: Chapter 7 asks for measurement, and a flawed measure that escalates beats no measure at all." },
  { t: "mcq", tier: "e", q: "A derivative is best described as:",
    o: ["A share in a company", "A contract whose value is derived from an underlying asset, rate or index", "A type of bank deposit", "A government bond"], a: 1,
    x: "Futures, options and swaps all fit. The chapter lists them as off-balance-sheet items because a contract can carry enormous exposure while showing almost nothing on the balance sheet today." },
  { t: "mcq", tier: "d", q: "Why do carefully diversified portfolios so often fall together in a crisis?",
    o: ["Diversification is a myth", "Correlations that looked low in calm markets rise towards one under stress, as forced sellers liquidate everything they can sell at once", "Diversified portfolios hold only one asset", "Regulators force simultaneous sales"], a: 1,
    x: "Correlation is measured on the past and the past was mostly calm. LTCM in 1998 and the 2011 Thai floods are the same lesson in different markets: pooling protects you until one event reaches every holding at once." },
  { t: "mcq", tier: "m", q: "A finance employee receives a convincing email from the \"chief executive\" instructing an urgent transfer, and pays it. Under Chapter 7's taxonomy this loss is:",
    o: ["Credit risk", "Operational risk, from the external-events and people limbs of the definition", "Market risk", "Insolvency risk"], a: 1,
    x: "No price moved and nobody defaulted. The control that failed was a payment authorisation process, which is why Chapter 7 defines operational risk to cover people and external events, not only broken systems." }
]);
})();
