FI.sorters = {
  c1: { title: "Which kind of regulation?", prompt: "Tap the type of regulation each rule belongs to.",
    sides: ["Safety & soundness", "Monetary policy", "Credit allocation", "Consumer & investor protection", "Entry"],
    items: [
      { t: "The DPA protects up to ฿1 million per depositor per bank", side: 0, why: "A guaranty fund is a safety-and-soundness layer that reduces run risk." },
      { t: "The BOT's MPC raises the policy rate by 0.25%", side: 1, why: "Setting the policy rate transmits monetary policy through banks." },
      { t: "GH Bank is mandated to fund low-income housing", side: 2, why: "Directing credit to a socially important sector is credit allocation." },
      { t: "The US Community Reinvestment Act targets redlining", side: 3, why: "The CRA prevents discrimination in lending: consumer protection." },
      { t: "The BOT limits how many virtual bank licences it grants", side: 4, why: "Controlling who may enter, and so the charter value, is entry regulation." },
      { t: "A bank may not lend more than about 25% of its capital to one borrower group", side: 0, why: "A diversification limit is a safety-and-soundness tool." },
      { t: "Banks must hold a minimum share of deposits as reserves", side: 1, why: "Reserve requirements are a monetary policy tool." },
      { t: "BAAC offers subsidised loans to farmers", side: 2, why: "Channelling cheaper credit to agriculture is credit allocation." },
      { t: "The Securities Act of 1933 requires disclosure on new issues", side: 3, why: "Disclosure protects investors: investor protection." },
      { t: "Basel III minimum capital ratios", side: 0, why: "Capital requirements protect against FI failure." },
      { t: "The 1999 FSMA lets banks, insurers and securities firms enter each other's businesses", side: 4, why: "It defines the scope of permitted activities, a form of entry regulation." },
      { t: "Open market purchases of government bonds", side: 1, why: "OMOs change bank reserves: monetary policy." }
    ] },
  c2: { title: "Name that US law", prompt: "Which Act did this?",
    sides: ["Glass-Steagall 1933", "FDICIA 1991", "Riegle-Neal 1994", "FSMA 1999", "Dodd-Frank 2010"],
    items: [
      { t: "Separated commercial and investment banking", side: 0, why: "Glass-Steagall built the wall that FSMA later took down." },
      { t: "Created the FDIC", side: 0, why: "Deposit insurance arrived with Glass-Steagall in 1933." },
      { t: "Introduced prompt corrective action", side: 1, why: "FDICIA made regulators act as capital falls." },
      { t: "Risk-based deposit insurance premiums", side: 1, why: "FDICIA priced insurance by risk to curb moral hazard." },
      { t: "Allowed BHCs to acquire banks in other states", side: 2, why: "Riegle-Neal ended most interstate banking barriers." },
      { t: "Let BHCs convert out-of-state subsidiaries into branches", side: 2, why: "The branching half of Riegle-Neal." },
      { t: "Allowed banks, insurers and securities firms into each other's businesses", side: 3, why: "FSMA (Gramm-Leach-Bliley) created financial services holding companies." },
      { t: "Provided for state regulation of insurance", side: 3, why: "Part of FSMA's streamlining." },
      { t: "Created the Consumer Financial Protection Bureau", side: 4, why: "The CFPB is a Dodd-Frank creation." },
      { t: "Created the Financial Stability Oversight Council", side: 4, why: "The FSOC monitors systemic risk under Dodd-Frank." },
      { t: "Prohibited interest on demand deposits", side: 0, why: "Glass-Steagall's rate rules (Regulation Q's origin)." },
      { t: "Limited “too big to fail” bailouts", side: 1, why: "FDICIA restricted regulators' ability to rescue large banks." },
      { t: "Required some derivatives to trade through clearinghouses", side: 4, why: "A post-crisis Dodd-Frank reform." }
    ] },
  c3: { title: "Which kind of lender?", prompt: "Sales finance, personal credit or business credit?",
    sides: ["Sales finance", "Personal credit", "Business credit"],
    items: [
      { t: "Ford Motor Credit financing Ford buyers", side: 0, why: "Lending to a manufacturer's customers is sales finance (and a captive)." },
      { t: "HSBC Finance making consumer loans", side: 1, why: "Loans to individuals are personal credit." },
      { t: "CIT Group leasing equipment to factories", side: 2, why: "Leasing to businesses is business credit." },
      { t: "Toyota Leasing (Thailand) financing Camry buyers", side: 0, why: "A captive financing its parent's products is sales finance." },
      { t: "Buying an exporter's receivables at a discount", side: 2, why: "Factoring is a business credit service." },
      { t: "A Thai card and personal-loan company lending to salaried workers", side: 1, why: "Unsecured consumer loans are personal credit." },
      { t: "AIG American General consumer lending", side: 1, why: "A personal credit institution in the slides." },
      { t: "Sears Roebuck Acceptance Corp.", side: 0, why: "It financed Sears' customers: sales finance." },
      { t: "U.S. Bancorp Equipment Finance", side: 2, why: "Equipment finance for firms is business credit." },
      { t: "A payday lender", side: 1, why: "Small, short-term loans to individuals are personal credit." }
    ] },
  c4: { title: "Which activity?", prompt: "Where does each task sit in a securities firm?",
    sides: ["Investment banking", "Market making", "Trading", "Advice & services"],
    items: [
      { t: "Buying a whole IPO at ฿9.40 to resell at ฿10", side: 0, why: "Firm-commitment underwriting is investment banking." },
      { t: "Continuously quoting bid 99.20 / ask 99.35 on a government bond", side: 1, why: "Standing ready to buy and sell from inventory is market making." },
      { t: "Buying a target's shares after a takeover is announced", side: 2, why: "Risk arbitrage is a trading strategy." },
      { t: "Advising a Thai conglomerate on an acquisition", side: 3, why: "M&A advisory." },
      { t: "Placing a bond issue with three insurance companies", side: 0, why: "A private placement is investment banking." },
      { t: "Computer-driven trading of whole baskets of stocks", side: 2, why: "Program trading." },
      { t: "Buying at 99.20 from one dealer and selling at 99.35 to another at once", side: 2, why: "Pure arbitrage is trading." },
      { t: "Sweeping client cash into a money market account", side: 3, why: "Cash management is a service line." },
      { t: "Clearing and settling client trades", side: 3, why: "Back-office services." },
      { t: "Holding a big bond position as a bet on falling rates", side: 2, why: "Position trading." }
    ] },
  c5: { title: "Mutual fund or hedge fund?", prompt: "Which does each feature describe best?",
    sides: ["Mutual fund", "Hedge fund"],
    items: [
      { t: "Redeems units daily at NAV", side: 0, why: "Open-end mutual funds redeem at NAV." },
      { t: "“2 and 20” fees", side: 1, why: "A management fee plus a performance fee is the hedge fund model." },
      { t: "Open only to accredited investors", side: 1, why: "Pre-2010 exemptions depended on accredited or fewer than 100 investors." },
      { t: "Charges a 12b-1 distribution fee", side: 0, why: "12b-1 fees are a mutual fund feature." },
      { t: "Must appoint a chief compliance officer reporting to the board (2004)", side: 0, why: "An SEC mutual fund rule." },
      { t: "Often domiciled in the Cayman Islands", side: 1, why: "Offshore centres are typical for hedge funds." },
      { t: "Market-neutral strategy with heavy leverage", side: 1, why: "Leverage and hedged strategies define hedge funds." },
      { t: "A Thai ESG tax-deductible fund", side: 0, why: "A retail mutual fund regulated by SEC Thailand." },
      { t: "Long-Term Capital Management", side: 1, why: "LTCM was a hedge fund rescued in 1998." },
      { t: "Offers load and no-load share classes", side: 0, why: "Loads and share classes are mutual fund pricing." },
      { t: "Historically exempt from SEC registration", side: 1, why: "Until Dodd-Frank, most hedge fund advisers were exempt." }
    ] },
  c6: { title: "Life or general?", prompt: "Which kind of insurer does each feature belong to?",
    sides: ["Life insurer", "Property & casualty"],
    items: [
      { t: "Net policy reserves are the dominant liability", side: 0, why: "Life insurers set aside reserves against expected future claims on long-dated policies." },
      { t: "Unearned premiums sit on the balance sheet as a liability", side: 1, why: "Premium collected for cover not yet provided. A P&C liability alongside loss reserves and LAE." },
      { t: "Endowment, universal and variable universal policies", side: 0, why: "All are ordinary life products, where protection is bundled with a savings element." },
      { t: "Homeowners multiple-peril cover", side: 1, why: "One of the five P&C product lines in the slides." },
      { t: "Annuities that pay a fund out over a lifetime", side: 0, why: "The slides call annuities the reverse of life insurance. They are a life insurer activity." },
      { t: "Needs liquid assets because claims can arrive all at once", side: 1, why: "Life claims are smooth; catastrophe claims are lumpy, so P&C stays shorter and holds more capital." },
      { t: "Morbidity (accident and health) cover", side: 0, why: "Listed under other life insurer activities, beside annuities and private pension funds." },
      { t: "Compulsory Thai third-party motor cover (Por Ror Bor)", side: 1, why: "Automobile liability insurance, made compulsory by statute. A non-life line." },
      { t: "Asbestos claims filed thirty years after the policy was written", side: 1, why: "Long-tail liability risk, the chapter's warning about P&C reserving." },
      { t: "Credit cover bundled with a hire-purchase contract to repay the loan on death", side: 0, why: "Credit life: one of the four categories beside ordinary, group and industrial life." },
      { t: "The combined ratio is the headline number of the year", side: 1, why: "Loss ratio plus expense ratio is the P&C underwriting scorecard." },
      { t: "Policy loans, where the insurer lends the customer their own accumulated value", side: 0, why: "A distinctive life insurer asset, made possible by the savings component of the policy." },
      { t: "The 2011 floods that inundated seven Thai industrial estates at once", side: 1, why: "A high-severity, low-frequency, non-independent catastrophe loss: the P&C problem in one event." },
      { t: "Applicants sorted into risk pools to blunt adverse selection", side: 0, why: "The slides raise adverse selection under life insurance issues, answered by grouping policyholders into pools." }
    ] },
  c7: { title: "Which risk is it?", prompt: "Name the risk the chapter would put this under.",
    sides: ["Credit", "Interest rate", "Market", "Liquidity", "Foreign exchange", "Operational"],
    items: [
      { t: "A two-year loan funded with three-month deposits, and the policy rate rises", side: 1, why: "A mismatch in asset and liability maturities: refinancing risk, the core of interest rate risk." },
      { t: "Depositors queue at the branch and bonds must be sold the same afternoon", side: 3, why: "Being forced to sell in a very short period, so prices are low. IndyMac in 2008." },
      { t: "A trader's unhedged long position in mortgage-backed securities falls 30%", side: 2, why: "An open position in a traded security moving against expectation: market risk." },
      { t: "An employee routes client money to a personal account for two years", side: 5, why: "Operational risk covers people as well as systems, and fraud sits squarely inside it." },
      { t: "A Thai bank's dollar liabilities exceed its dollar assets when the baht falls", side: 4, why: "A net short dollar position: the liabilities grow in baht terms. Thailand, 1997." },
      { t: "A property developer stops servicing its loan after sales collapse", side: 0, why: "Promised cash flows are not paid in full. Firm-specific credit risk." },
      { t: "A foreign government imposes capital controls, so a performing loan cannot be repatriated", side: 0, why: "Country or sovereign risk, which the chapter classifies as a type of credit risk, distinguished by having no recourse through the courts." },
      { t: "A card processor is breached and millions of card numbers are taken", side: 5, why: "Loss from an external event striking systems: operational risk, of which technology risk is a part. Target and Heartland." },
      { t: "Long-dated government bonds lose 9% of their value after a rate rise, with no default", side: 1, why: "Market value risk, the second face of interest rate risk: value is the PV of cash flows, so rates alone rewrite it." },
      { t: "Recession hits, and defaults rise across every sector of the loan book at once", side: 0, why: "Systematic credit risk, the part diversification cannot reach." },
      { t: "A bank's mobile app is down for a day and transfers fail", side: 5, why: "Failed systems. The direct loss is small; the reputational loss is what the chapter warns about." },
      { t: "An FI matches its dollar assets and liabilities in amount, but the assets are five-year and the funding is three-month", side: 1, why: "The currency exposure is closed, so what remains is foreign <em>interest rate</em> risk from the maturity mismatch." },
      { t: "A money market fund cannot sell its holdings at any sensible price because every fund is selling", side: 3, why: "A market with no buyers turns a redemption request into a fire sale. Bangkok, March 2020." },
      { t: "The dollar rises against the euro while falling against the yen, and the FI is concentrated in one of them", side: 4, why: "Exchange rates are not correlated with each other, so it is undiversified foreign exposure that creates FX risk." },
      { t: "A trading desk builds a derivatives position so large that exiting it moves the price against itself", side: 2, why: "The London Whale. The position is a market risk; the control failure that allowed its size is operational." },
      { t: "A borrower draws an old fixed-rate commitment on the day rates peak", side: 1, why: "The commitment becomes an asset priced at yesterday's rate. The chapter uses this as its interdependency example: off-balance-sheet, interest rate and credit risk together." }
    ] }
};
