FI.sorters = {
  c1: { title: "Which kind of regulation?", prompt: "Tap the type of regulation each rule belongs to.",
    sides: ["Safety & soundness", "Monetary policy", "Credit allocation", "Consumer & investor protection", "Entry"],
    items: [
      { t: "The DPA protects up to ฿1 million per depositor per bank", side: 0, why: "A guaranty fund is a safety-and-soundness layer that reduces run risk." },
      { t: "The BOT's MPC raises the policy rate by 0.25%", side: 1, why: "Setting the policy rate transmits monetary policy through banks." },
      { t: "GH Bank is mandated to fund low-income housing", side: 2, why: "Directing credit to a socially important sector is credit allocation." },
      { t: "The US Community Reinvestment Act targets redlining", side: 3, why: "The CRA prevents discrimination in lending: consumer protection." },
      { t: "The BOT limits how many virtual bank licences it grants", side: 4, why: "Controlling who may enter, and so the charter value, is entry regulation." },
      { t: "A bank may not lend more than about 25% of its capital to one borrower group", side: 0, why: "A diversification limit is a safety-and-soundness tool." },
      { t: "Banks must hold a minimum share of deposits as reserves", side: 1, why: "Reserve requirements are a monetary policy tool." },
      { t: "BAAC offers subsidised loans to farmers", side: 2, why: "Channelling cheaper credit to agriculture is credit allocation." },
      { t: "The Securities Act of 1933 requires disclosure on new issues", side: 3, why: "Disclosure protects investors: investor protection." },
      { t: "Basel III minimum capital ratios", side: 0, why: "Capital requirements protect against FI failure." },
      { t: "The 1999 FSMA lets banks, insurers and securities firms enter each other's businesses", side: 4, why: "It defines the scope of permitted activities, a form of entry regulation." },
      { t: "Open market purchases of government bonds", side: 1, why: "OMOs change bank reserves: monetary policy." }
    ] },
  c2: { title: "Name that US law", prompt: "Which Act did this?",
    sides: ["Glass-Steagall 1933", "FDICIA 1991", "Riegle-Neal 1994", "FSMA 1999", "Dodd-Frank 2010"],
    items: [
      { t: "Separated commercial and investment banking", side: 0, why: "Glass-Steagall built the wall that FSMA later took down." },
      { t: "Created the FDIC", side: 0, why: "Deposit insurance arrived with Glass-Steagall in 1933." },
      { t: "Introduced prompt corrective action", side: 1, why: "FDICIA made regulators act as capital falls." },
      { t: "Risk-based deposit insurance premiums", side: 1, why: "FDICIA priced insurance by risk to curb moral hazard." },
      { t: "Allowed BHCs to acquire banks in other states", side: 2, why: "Riegle-Neal ended most interstate banking barriers." },
      { t: "Let BHCs convert out-of-state subsidiaries into branches", side: 2, why: "The branching half of Riegle-Neal." },
      { t: "Allowed banks, insurers and securities firms into each other's businesses", side: 3, why: "FSMA (Gramm-Leach-Bliley) created financial services holding companies." },
      { t: "Provided for state regulation of insurance", side: 3, why: "Part of FSMA's streamlining." },
      { t: "Created the Consumer Financial Protection Bureau", side: 4, why: "The CFPB is a Dodd-Frank creation." },
      { t: "Created the Financial Stability Oversight Council", side: 4, why: "The FSOC monitors systemic risk under Dodd-Frank." },
      { t: "Prohibited interest on demand deposits", side: 0, why: "Glass-Steagall's rate rules (Regulation Q's origin)." },
      { t: "Limited “too big to fail” bailouts", side: 1, why: "FDICIA restricted regulators' ability to rescue large banks." },
      { t: "Required some derivatives to trade through clearinghouses", side: 4, why: "A post-crisis Dodd-Frank reform." }
    ] },
  c3: { title: "Which kind of lender?", prompt: "Sales finance, personal credit or business credit?",
    sides: ["Sales finance", "Personal credit", "Business credit"],
    items: [
      { t: "Ford Motor Credit financing Ford buyers", side: 0, why: "Lending to a manufacturer's customers is sales finance (and a captive)." },
      { t: "HSBC Finance making consumer loans", side: 1, why: "Loans to individuals are personal credit." },
      { t: "CIT Group leasing equipment to factories", side: 2, why: "Leasing to businesses is business credit." },
      { t: "Toyota Leasing (Thailand) financing Camry buyers", side: 0, why: "A captive financing its parent's products is sales finance." },
      { t: "Buying an exporter's receivables at a discount", side: 2, why: "Factoring is a business credit service." },
      { t: "A Thai card and personal-loan company lending to salaried workers", side: 1, why: "Unsecured consumer loans are personal credit." },
      { t: "AIG American General consumer lending", side: 1, why: "A personal credit institution in the slides." },
      { t: "Sears Roebuck Acceptance Corp.", side: 0, why: "It financed Sears' customers: sales finance." },
      { t: "U.S. Bancorp Equipment Finance", side: 2, why: "Equipment finance for firms is business credit." },
      { t: "A payday lender", side: 1, why: "Small, short-term loans to individuals are personal credit." }
    ] },
  c4: { title: "Which activity?", prompt: "Where does each task sit in a securities firm?",
    sides: ["Investment banking", "Market making", "Trading", "Advice & services"],
    items: [
      { t: "Buying a whole IPO at ฿9.40 to resell at ฿10", side: 0, why: "Firm-commitment underwriting is investment banking." },
      { t: "Continuously quoting bid 99.20 / ask 99.35 on a government bond", side: 1, why: "Standing ready to buy and sell from inventory is market making." },
      { t: "Buying a target's shares after a takeover is announced", side: 2, why: "Risk arbitrage is a trading strategy." },
      { t: "Advising a Thai conglomerate on an acquisition", side: 3, why: "M&A advisory." },
      { t: "Placing a bond issue with three insurance companies", side: 0, why: "A private placement is investment banking." },
      { t: "Computer-driven trading of whole baskets of stocks", side: 2, why: "Program trading." },
      { t: "Buying at 99.20 from one dealer and selling at 99.35 to another at once", side: 2, why: "Pure arbitrage is trading." },
      { t: "Sweeping client cash into a money market account", side: 3, why: "Cash management is a service line." },
      { t: "Clearing and settling client trades", side: 3, why: "Back-office services." },
      { t: "Holding a big bond position as a bet on falling rates", side: 2, why: "Position trading." }
    ] },
  c5: { title: "Mutual fund or hedge fund?", prompt: "Which does each feature describe best?",
    sides: ["Mutual fund", "Hedge fund"],
    items: [
      { t: "Redeems units daily at NAV", side: 0, why: "Open-end mutual funds redeem at NAV." },
      { t: "“2 and 20” fees", side: 1, why: "A management fee plus a performance fee is the hedge fund model." },
      { t: "Open only to accredited investors", side: 1, why: "Pre-2010 exemptions depended on accredited or fewer than 100 investors." },
      { t: "Charges a 12b-1 distribution fee", side: 0, why: "12b-1 fees are a mutual fund feature." },
      { t: "Must appoint a chief compliance officer reporting to the board (2004)", side: 0, why: "An SEC mutual fund rule." },
      { t: "Often domiciled in the Cayman Islands", side: 1, why: "Offshore centres are typical for hedge funds." },
      { t: "Market-neutral strategy with heavy leverage", side: 1, why: "Leverage and hedged strategies define hedge funds." },
      { t: "A Thai ESG tax-deductible fund", side: 0, why: "A retail mutual fund regulated by SEC Thailand." },
      { t: "Long-Term Capital Management", side: 1, why: "LTCM was a hedge fund rescued in 1998." },
      { t: "Offers load and no-load share classes", side: 0, why: "Loads and share classes are mutual fund pricing." },
      { t: "Historically exempt from SEC registration", side: 1, why: "Until Dodd-Frank, most hedge fund advisers were exempt." }
    ] }
};
